### ISSUE TITLE
Problem starting the software on Ubuntu

### ISSUE THREAD

**Issue by Lenglemetz** [lencx/ChatGPT#100]
With KDE, the software doesn't launch, I have to go through a terminal and run the command to start openai.

**Comment by lencx** [comment]
I am not very familiar with the ubuntu system, so if possible, you can clone the code and build it yourself, and I can assist you.

**Comment by lencx** [comment]
There are a few ubuntu issues that overlap with this one, so I'll close this one and you can reopen it if you still have problems.
