### ISSUE TITLE
Missing minimize and close buttons

### ISSUE THREAD

**Issue by Digital-Coder** [lencx/ChatGPT#103]
I can only create new chat in this window
![image](https://user-images.githubusercontent.com/31192965/209983740-9afdf2df-ccaf-4699-9d45-93f657b26b3b.png)

**Comment by lencx** [comment]
I don't understand what you mean, this is the tray window. Can't the main window be opened?

**Comment by Digital-Coder** [comment]
so when I click on  the tray icon, it opens this mini window, but it does not have minimize or close buttons. The only way to minimize it is to click again on a tray icon or right click tray icon to close it.

**Comment by Digital-Coder** [comment]
and when I click close on the main window, it minimizes to the bottom, but I would expect it to completely close it and minimize it to the system tray icons
![image](https://user-images.githubusercontent.com/31192965/210138523-a015349d-e9a5-4fee-8a3b-45409eed28df.png)

**Comment by lencx** [comment]
Your question was answered here https://github.com/lencx/ChatGPT/issues/93

**Comment by mtw20** [comment]
OP pointed out that the popup in tray window can only be closed / hidden by clicking tray again - missing buttons.

**Comment by lencx** [comment]
@mtw20 This window I hide three buttons on purpose because it is a bad experience. I can't put a particular button alone.
