### ISSUE TITLE
Can't close application on Windows 10

### ISSUE THREAD

**Issue by skin27** [lencx/ChatGPT#104]
On Windows 10 when closing windows (X Close Window) nothing happens. I can only close it through task manager.

**Comment by lencx** [comment]
The default close window is disabled and is to prevent accidental closures. You need to use `Menu Quit` or the shortcut `Ctrl+Q` to exit. Because once the main window is closed, the whole system will exit (including the system tray).

**Comment by skin27** [comment]
@lencx  Thanks for the tip. I do however would find it more logical that it works like other applications like Chrome or Word. I also seen some apps that show a notification when you close the application to tray. Now it's a bit strange that when you choose "Close window" with right-click on the taskbar that the application stays on the taskbar. I think, it would be more logical if it 'closes' to the tray only (with a notification on first time maybe) and not stay available in the taskbar. Just my thoughts. Keep up the good work.

**Comment by lencx** [comment]
I answered this question here https://github.com/lencx/ChatGPT/issues/93#issuecomment-1366791192
