### ISSUE TITLE
Error: Undefined

### ISSUE THREAD

**Issue by jrman28** [lencx/ChatGPT#106]
Chat GPT wrapper keeps crashing every time I click log in or sign in. I have uninstalled and reinstalled via the terminal. I also have done the same with downloading the macOS package the traditional way and still got the same result. 
![Screen Shot 2022-12-29 at 7 01 52 PM](https://user-images.githubusercontent.com/12195826/210025649-89926792-fb0e-41b5-8901-bc240ff183e4.png)

**Comment by Shmeeg** [comment]
> Chat GPT wrapper keeps crashing every time I click log in or sign in. I have uninstalled and reinstalled via the terminal. I also have done the same with downloading the macOS package the traditional way and still got the same result. ![Screen Shot 2022-12-29 at 7 01 52 PM](https://user-images.githubusercontent.com/12195826/210025649-89926792-fb0e-41b5-8901-bc240ff183e4.png)

Mine doesn't even show, just won't load. I rolled back to previous version which still works.

**Comment by lencx** [comment]
> Chat GPT wrapper keeps crashing every time I click log in or sign in. I have uninstalled and reinstalled via the terminal. I also have done the same with downloading the macOS package the traditional way and still got the same result. 
> 
> ![Screen Shot 2022-12-29 at 7 01 52 PM](https://user-images.githubusercontent.com/12195826/210025649-89926792-fb0e-41b5-8901-bc240ff183e4.png)
> 
> 

This is a network problem, not related to the app.
