### ISSUE TITLE
Feature request: set different global hotkey to show/hide ChatGPT app

### ISSUE THREAD

**Issue by heldheld** [lencx/ChatGPT#110]
Right now it's ctrl+shift+o but I'd love to be able to change this in the settings/control center.

**Comment by lencx** [comment]
Please discuss here, I'll close this issues first, they are the same issue https://github.com/lencx/ChatGPT/issues/110

**Comment by heldheld** [comment]
oh, that's very coincidentally submitted around the same time, thanks!
