### ISSUE TITLE
[Feature] could you move the "export" button to somewhere else

### ISSUE THREAD

**Issue by zhoujinzhoujin** [lencx/ChatGPT#1102]
### Feature description

I often click on the "export" button by accident, since it is so close to the text box
Each time I click on that, the window gets stuck on "Exporting..." without a cancel option. I have to wait for 10 minutes or close the entire software

**Comment by lduperval** [comment]
Which version do you have?  On my version the export button is just above my account name, in the left sidebar

**Comment by zhoujinzhoujin** [comment]
I use 1.1.0
![Screenshot 2023-10-18 105754](https://github.com/lencx/ChatGPT/assets/27711989/d9946735-7c3b-486a-ba43-207e73620472)
These buttons actually appear occasionally, which is weird

**Comment by lduperval** [comment]
Interesting. This is how they appear for me on Windows:

![image](https://github.com/lencx/ChatGPT/assets/73903942/a04d8dbc-c338-4e32-8383-625797ecbee8)

Are all your scripts up-to-date? You can see in the Control Center under Preferences.

**Comment by zhoujinzhoujin** [comment]
I updated the scripts and the problem was solved. Thank you!!
