### ISSUE TITLE
error -> libssl on linux Mint 

### ISSUE THREAD

**Issue by zednaked** [lencx/ChatGPT#111]
im getting this error:

chat-gpt: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by lencx** [comment]
There is a relevant discussion here https://github.com/tauri-apps/tauri/issues/4470

**Comment by lencx** [comment]
I am trying to fix this issue, please install v0.7.4 to verify.

**Comment by lencx** [comment]
I hope this summary will be helpful to you https://github.com/lencx/ChatGPT/issues/107#issuecomment-1368223813

**Comment by lencx** [comment]
@zednaked It has been verified that appImage works well, you can try it https://github.com/lencx/ChatGPT/releases/download/v0.7.4/chat-gpt_0.7.4_amd64.AppImage
