### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by YorkZ** [lencx/ChatGPT#112]
Failed with the following error after typing `yarn dev`:

```
   ...
   
   Compiling chatgpt v0.0.0 (~/src/ChatGPT/src-tauri)
   Compiling gdk-pixbuf v0.15.11
   Compiling soup2 v0.2.1
   Compiling gdk v0.15.4
   Compiling libappindicator v0.7.1
   Compiling webkit2gtk v0.18.2
   Compiling tauri-plugin-positioner v1.0.4
   Compiling tauri-plugin-log v0.1.0 (https://github.com/tauri-apps/tauri-plugin-log?branch=dev#b58475bb)
    Finished dev [unoptimized + debuginfo] target(s) in 3m 16s
thread 'main' panicked at 'Failed to load ayatana-appindicator3 or appindicator3 dynamic library
libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
libappindicator3.so.1: cannot open shared object file: No such file or directory
libayatana-appindicator3.so: cannot open shared object file: No such file or directory
libappindicator3.so: cannot open shared object file: No such file or directory', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/libappindicator-sys-0.7.3/src/lib.rs:41:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Could you please let me know what I'm missing?

Thank you

**Comment by lencx** [comment]
The error looks like an environmental problem, please check the documentation for details. https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux

**Comment by YorkZ** [comment]
Thanks for your fast response. Looks like it would be easier to install this app using `Homebrew` right? If using Homebrew, can it be installed user wide? How do I undo the operation of `yarn` and the unsuccessful `yan dev`, and maybe reverse any changes in `~/.cargo`?

**Comment by lencx** [comment]
To work in development mode, you first need to make sure that the rust and node.js environments are working properly. tauri's dependencies may vary from platform to platform, so you need to refer to the official website for configuration (I've only touched the mac configuration so far). You don't need to undo anything, if configured correctly, `yarn` and `~/.cargo` will be overwritten again when you start `yarn dev`.

**Comment by YorkZ** [comment]
Thank you for your reply. I don't want to work in development mode at the moment. I noticed that something had been installed in `~/.cargo`, and was wondering whether it would be possible to delete the files that had been installed in `~/.cargo`.

**Comment by lencx** [comment]
Can be deleted, they are cache dependencies.

**Comment by YorkZ** [comment]
Because I also have other files in `~/.cargo`, if I delete everything in this directory, would it break other applications? If it would, how can I delete only the files that was installed from running `yarn` and `yaan dev` in the `ChatGPT` directory? Thanks again.

**Comment by lencx** [comment]
It is recommended that you go through the rust basics, and I can only say sorry to you because chatgpt's rust dependencies are also cached in it.

**Comment by YorkZ** [comment]
> It is recommended that you go through the rust basics

What did you mean and could you add more details about this? Would you suggest that the effect of running `yarn` and `yarn dev` in your `ChatGPT` directory is irreversible?

**Comment by lencx** [comment]
There is nothing irreversible, isn't it normal for software development to download dependencies? You want to remove dependencies this is not something I need to help you with, you need to look at the rust and tauri documentation. The yarn installation dependencies are not in the `~/.cargo` directory.

**Comment by YorkZ** [comment]
Thank you for your response. While it is true that software development often involves downloading dependencies, it is also important to consider the ease of uninstallation for the end user. In this case, as an Arch Linux user, I would typically be able to easily remove an application and its dependencies using the `pacman -Rns` command. However, since this application was not installed through `pacman`, I am unable to use this method to uninstall it and its dependencies.

I understand that every software installation is theoretically removable, but the fact that I have to spend significant time reading documentation and manually uninstalling dependencies adds an unnecessary level of complexity for the user. In my opinion, this is a poor design and implementation of the application installation process. I hope that in the future, the installation process can be streamlined to make uninstallation easier for users.

**Comment by lencx** [comment]
I think you are misrepresenting the facts because this is a build that you perform locally, not a download of the application.
<img width="600" alt="yarn dev" src="https://user-images.githubusercontent.com/16164244/210160332-4e3f8af8-6e82-44db-958e-0e14f251a9f9.png">

Here is the download link to install the application (https://github.com/lencx/ChatGPT/releases). You need to be responsible for yourself if you want to perform the build locally, because I don't have enough time to go through how to build the project for everyone. That's not my job.

**Comment by yixinBC** [comment]
> Thank you for your response. While it is true that software development often involves downloading dependencies, it is also important to consider the ease of uninstallation for the end user. In this case, as an Arch Linux user, I would typically be able to easily remove an application and its dependencies using the `pacman -Rns` command. However, since this application was not installed through `pacman`, I am unable to use this method to uninstall it and its dependencies.
> 
> I understand that every software installation is theoretically removable, but the fact that I have to spend significant time reading documentation and manually uninstalling dependencies adds an unnecessary level of complexity for the user. In my opinion, this is a poor design and implementation of the application installation process. I hope that in the future, the installation process can be streamlined to make uninstallation easier for users.

I must point it out that you totally confused the concepts of ***install*** and ***build***.what you do while running `pacman` is to ***install*** an app that already has been ***built***. Now what you are doing is ***building*** the app on your computer. It's not necessary for most of us.for **Arch linux users**,if you want to simply **use** this application, you just need ***install*** instead of ***build***.So you can just download and run the AppImage file in the [release page](https://github.com/lencx/ChatGPT/releases)

**Comment by YorkZ** [comment]
I think the issue with the build process of this application is that it conflates the process of installing a development environment with the build process itself. In my opinion, these should be separate processes. The problem is that I didn't realize that building this application would also install its development environment, and some of the dev dependencies (in `~/.cargo`) were not easy to uninstall. As I don't plan to involve myself in the development of this app at this point and prefer to keep my system clean, I hope I can safely remove the files in `~/.cargo` that were installed by the build process without disrupting my existing `Rust` applications. However, it seems that even the author of this app was unable to determine exactly which files were installed in `~/.cargo` during the build process without some investigation.

I believe the build process should not install any development tools or libraries without the user's explicit consent, especially if they are difficult to uninstall. A better practice would be to separate the process of setting up the dev environment from the process of building the application.

Your statement that "what you do while running pacman is to install an app that already has been built" is not entirely accurate. In fact, in the case of the Arch Linux `AUR` system, applications are actually built from source before being packaged and installed. However, users can still easily uninstall the application and its dependencies.

Lastly, thank you for the suggestion to use the `AppImage` file instead of building the application myself. I will consider this option in the future.

**Comment by YorkZ** [comment]
> I think you are misrepresenting the facts because this is a build that you perform locally, not a download of the application. <img alt="yarn dev" width="600" src="https://user-images.githubusercontent.com/16164244/210160332-4e3f8af8-6e82-44db-958e-0e14f251a9f9.png">
> 
> Here is the download link to install the application (https://github.com/lencx/ChatGPT/releases). You need to be responsible for yourself if you want to perform the build locally, because I don't have enough time to go through how to build the project for everyone. That's not my job.

I apologize if my previous message misrepresented the facts. I understand that building the application locally is different from downloading it. However, I think it would be helpful if the instructions for building the application locally were more clear and complete, as it was not easy for me to understand what was happening during the build process or how to uninstall the files that were installed as a result.

I understand that it is not the author's job to go through the build process with every user, but providing clear instructions and documentation can be beneficial for those who choose to build the application locally.

Thank you for providing the download link to install the application. I will consider using this option in the future.

**Comment by lencx** [comment]
About how to build the project, I think it is necessary for the user to learn from tauri documentation, because if the user wants to build it by himself, then by default he has already mastered some basics. Otherwise, along your lines, should I start with computer basics?

**Comment by YorkZ** [comment]
> About how to build the project, I think it is necessary for the user to learn from tauri documentation, because if the user wants to build it by himself, then by default he has already mastered some basics. Otherwise, along your lines, should I start with computer basics?

Thank you for your response. While I understand that it is necessary for users to learn from the `Tauri` documentation in order to build the project, my main concern was not with understanding the build process itself. As a senior developer who is new to `Rust` and `Node.js`, I found the build process to be confusing and not clearly documented.

What I was seeking was information on which files were installed on my system as a result of building the application, as I wanted to ensure that I could safely uninstall these files without disrupting my other `Rust` applications.

I do not think it is appropriate to suggest that someone needs to learn computer basics because they are having difficulty with a particular project. I was simply seeking clarification and additional documentation to help me understand the build process better.

I appreciate your suggestion to refer to the `Tauri` documentation, but I hope that in the future, the instructions for building the project can include information on which files are installed and how to safely uninstall them. This would be helpful for users who are new to the technologies being used and who may not have the time or resources to investigate these issues on their own.

**Comment by lencx** [comment]
I'm sorry, but I haven't seen a similar project on github so far that would describe in detail the dependencies created during the development of the software and how to go about removing them.

**Comment by YorkZ** [comment]
Thank you for your responses. After considering my experience with this project, I have decided to stay away from it due to the unconstructive, unhelpful, and unprofessional behavior that I have encountered.

I understand that developing software can be a challenging and time-consuming process, but it is important to communicate and interact with users in a respectful and professional manner.

I hope that in the future, the instructions for building the project can be improved and made more clear and complete for those who are new to the technologies being used. This can help users understand the build process better and avoid any potential issues or confusion.

Thank you for your time, and I wish you the best of luck with your project.

**Comment by lencx** [comment]
I respect your decision, because software was never meant to satisfy everyone. If it doesn't suit you you can leave it and I can't cater to everyone because I don't have that much time.

**Comment by yixinBC** [comment]
> > I must point it out that you totally confused the concepts of install and build.what you do while running pacman is to install an app that already has been built. Now what you are doing is building the app on your computer. It's not necessary for most of us.for Arch linux users,if you want to simply use this application, you just need install instead of build.So you can just download and run the AppImage file in the [release page](https://github.com/lencx/ChatGPT/releases)
> 
> I think the issue with the build process of this application is that it conflates the process of installing a development environment with the build process itself. In my opinion, these should be separate processes. The problem is that I didn't realize that building this application would also install its development environment, and some of the dev dependencies (in `~/.cargo`) were not easy to uninstall. As I don't plan to involve myself in the development of this app at this point and prefer to keep my system clean, I hope I can safely remove the files in `~/.cargo` that were installed by the build process without disrupting my existing `Rust` applications. However, it seems that even the author of this app was unable to determine exactly which files were installed in `~/.cargo` during the build process without some investigation.
> 
> I believe the build process should not install any development tools or libraries without the user's explicit consent, especially if they are difficult to uninstall. A better practice would be to separate the process of setting up the dev environment from the process of building the application.
> 
> Your statement that "what you do while running pacman is to install an app that already has been built" is not entirely accurate. In fact, in the case of the Arch Linux `AUR` system, applications are actually built from source before being packaged and installed. However, users can still easily uninstall the application and its dependencies.
> 
> Lastly, thank you for the suggestion to use the `AppImage` file instead of building the application myself. I will consider this option in the future.

That's my fault.I just view `pacman` as the Arch version `apt`, but now I clarify it via [wikipedia](https://en.wikipedia.org/wiki/Arch_Linux#AUR).If you are just looking forward to a so-called `PKGBUILD scripts` for Arch, I think you might could open an new issue for these feature request, and then hang out until there's a commit to add this feature.I don't think it will have high priority on the author's todo list(there are still many core functions to be implemented, and the author obviously not master Linux).But you can still implement it by yourself and then open a pr. As a open sourse project, there's no reason to reject such a pr :)
