### ISSUE TITLE
[Doc] Apologies for a dumb question, but where'd the export buttons go?

### ISSUE THREAD

**Issue by mharris1319** [lencx/ChatGPT#1142]
### Provide a description of requested docs changes

Can't seem to find hide-nor-hair of the buttons that allow you to export to PDF, TXT, etc.  I don't see any documentation or other place on the Internet that suggests where they went.  Can you advise?

**Comment by chunbo129** [comment]
我遇到了同样的问题，导出按钮不见了，找了各种设置，没有发现如何找回那几个按钮。


I encountered the same problem, the export button disappeared. I've looked through various settings but haven't found how to retrieve those buttons.

**Comment by mharris1319** [comment]
我想到了。 您转到“首选项”菜单，然后选择“控制中心”。 然后您选择脚本。 您需要更新所有脚本（包括export.js），然后重新启动应用程序

I figured it out.  You go to the Preferences menu, and pick Control Center.  You then select Scripts.  You'll want to update all the scripts, including export.js, and restart the application.

**Comment by chunbo129** [comment]
> 我想到了。 您转到“首选项”菜单，然后选择“控制中心”。 然后您选择脚本。 您需要更新所有脚本（包括export.js），然后重新启动应用程序
> 
> I figured it out. You go to the Preferences menu, and pick Control Center. You then select Scripts. You'll want to update all the scripts, including export.js, and restart the application.

谢谢你的回答，不过我的问题仍然没有解决。
我试过了卸载并重新安装，也试了你说的方法，仍然不显示到处按钮。

Thank you for your response, but my problem is still not resolved. I have tried uninstalling and reinstalling, as well as the method you mentioned, but the export button still does not show up.

**Comment by mharris1319** [comment]
我发现答案已在这里得到解决：https://github.com/lencx/ChatGPT/issues/1156

您基本上需要替换 export.js 的第 209-225 行 - 当前脚本让它出现在不再存在的区域中。

I found that the answer has been addressed here:

https://github.com/lencx/ChatGPT/issues/1156

You basically need to replace lines 209-225 of export.js - the current script has it appear in an area that no longer exists.
