### ISSUE TITLE
Feature request : make it work with DALL-E also :>

### ISSUE THREAD

**Issue by Habibb156** [lencx/ChatGPT#120]
I dont have much knowledge about this but i know that its not easy to do so. but if you can that would be epic !

**Comment by lencx** [comment]
I don't understand, what is this feature?

**Comment by Habibb156** [comment]
there is an option in the setting to change the link for the page i was wondering if you can edit this to work with  the link of DALL-E properly

**Comment by lencx** [comment]
You can try `Menu -> Preferences -> Control Center -> General -> Switch Origin`.

**Comment by lencx** [comment]
Is this the feature you want? https://github.com/lencx/ChatGPT/issues/122
