### ISSUE TITLE
[Bug] flashback on windows 11

### ISSUE THREAD

**Issue by DaphneOdera17** [lencx/ChatGPT#1202]
### Non-ChatGPT bug

- [X] This issue does not occur on chat.openai.com and only occurs on this app.

### Version

v1.1.0

### Bug description

When I open the chatgpt app, the software flashes back. And there is no application running in the background. I have tried deleting and reinstalling the software as well as restarting the computer, but it doesn't work.

### OS

Windows 11

**Comment by Fishlulu1314** [comment]
I have the same question! And I use it normally just few days ago!

**Comment by riku4707** [comment]
idk
