### ISSUE TITLE
[Bug] Messages are not being sent

### ISSUE THREAD

**Issue by FuckingSherlock** [lencx/ChatGPT#1219]
### Non-ChatGPT bug

- [X] This issue does not occur on chat.openai.com and only occurs on this app.

### Version

1.1.0

### Bug description

Probably, after updating openai, I had a crash, because of which chat messages simply were not sent, disappearing without any reaction. I solved this problem on the web version by deleting all cookies associated with openai. However, deleting cookies in this app via dev tools did not solve the problem, as did reinstalling. It also bothers me that even after deleting all related files `C:\Users\user\.chatgpt`, the app remembers my username. Maybe I couldn't find any files that should have been deleted?

### OS

Windows 10

**Comment by jigang-amax-zhong** [comment]
same problem on my chatgpt client on Mac. there's no response from chat gat after send any text

**Comment by wo0o0ow** [comment]
same on windows11.find some error in toggle developer tools:
![image](https://github.com/lencx/ChatGPT/assets/46042818/24b10d1d-d087-4bd2-b1f4-be8ace939aca)

**Comment by FuckingSherlock** [comment]
> то же самое в windows11. обнаружена ошибка в переключении инструментов разработчика: ![изображение](https://private-user-images.githubusercontent.com/46042818/311158745-24b10d1d-d087-4bd2-b1f4-be8ace939aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODYxMzcsIm5iZiI6MTcwOTg4NTgzNywicGF0aCI6Ii80NjA0MjgxOC8zMTExNTg3NDUtMjRiMTBkMWQtZDA4Ny00YmQyLWIxZjQtYmU4YWNlOTM5YWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZTMzNjMyOGM5MGUyMDcyZjM4YmI3ZmQwYzVmNzAzY2VhYjczNDFkMjhjNTcyM2YzYWQ0MDU2ODUxOTg3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3IXmbpcRGPVtpGC8dyVB3t_1yDpoGgJq3CCZ7BMcUfw)

**Comment by mitch133** [comment]
Hi, same problem here.
Except I have 3 PCs with different behaviors...

1) Everything still works fine with the ChatGPT 1.1.0 client for Windows (Windows 10)
2) Cannot send any message with the ChatGPT 1.1.0 client for Windows (Windows 11)
3) I can send messages, but I get no answer at all, the ChatGPT 1.1.0 client for Windows gets stuck after sending the message, it seems like its processing the prompt but it remains processing forever...

I don't understand this suddent and random behavior depending on the PC...

**Comment by wangengzheng** [comment]
same problem

**Comment by CODER-ZHM1997** [comment]
i found that i cannot lost gpt

**Comment by FuckingSherlock** [comment]
> i found that i cannot lost gpt

What??

**Comment by FuckingSherlock** [comment]
> > Hi, same problem here. Except I have 3 PCs with different behaviors...
> > 
> > 1. Everything still works fine with the ChatGPT 1.1.0 client for Windows (Windows 10)
> > 2. Cannot send any message with the ChatGPT 1.1.0 client for Windows (Windows 11)
> > 3. I can send messages, but I get no answer at all, the ChatGPT 1.1.0 client for Windows (Windows 10) gets stuck after sending the message, it seems like its processing the prompt but it remains processing forever...
> > 
> > I don't understand this suddent and random behavior depending on the PC.. The web version of ChatGPT works fine on the 3 PCs
> 
> On web doesn't work at me and the same thing with the client v1.1.0 but not on my android smartphone (Pixel 7 Pro).

It's easy to fix on the web.  Just delete all openai data in your browser, including all subdomains.

**Comment by thierry-laval** [comment]
**It works for me.**

MacOS Sonoma system
ChatGPT Application Version 1.1.0 (20230803.134227)

My solution:
In the application, I used the console to clear the cache, deleted the preferences folder (.chatgpt) via the Finder on my Apple system, restarted the application which asked me for my access codes. And the chat started working normally again.

**Comment by JinchaoC** [comment]
You are right @thierry-laval . The author gave the solution in his wechat aricle [here](https://mp.weixin.qq.com/s/p5pjKRqJ5QE7MU_KOy7lXw).

**Comment by JinchaoC** [comment]
![屏幕截图 2024-03-09 215209](https://github.com/lencx/ChatGPT/assets/137679394/6e610562-6fee-4de3-8404-83cffc7ea2d6)
Here is the solution. You guys can also find the solution [here](https://mp.weixin.qq.com/s/p5pjKRqJ5QE7MU_KOy7lXw)

**Comment by FuckingSherlock** [comment]
> You are right @thierry-laval . The author gave the solution in his wechat aricle [here](https://mp.weixin.qq.com/s/p5pjKRqJ5QE7MU_KOy7lXw). 

It says that the problem only occurs in Chinese, but I have English.  I also tried deleting ALL application data, as well as reinstalling the application itself.  I also tried rebooting without cache and resetting cookies through dev tools. I previously said this at the beginning of the issue.

**Comment by jigang-amax-zhong** [comment]
> **It works for me.**
> 
> MacOS Sonoma system ChatGPT Application Version 1.1.0 (20230803.134227)
> 
> My solution: In the application, I used the console to clear the cache, deleted the preferences folder (.chatgpt) via the Finder on my Apple system, restarted the application which asked me for my access codes. And the chat started working normally again.

it works. thanks.

**Comment by FuckingSherlock** [comment]
In my case, I solved the problem by deleting not only cookies and C:\Users\Professional\.chatgpt folder, but also local storage in dev tools -> application

**Comment by mitch133** [comment]
Works again today on my 3 PC's.
Did nothing in particular... The ways of the ChatGPT client seem to be inscrutable! :)
