### ISSUE TITLE
Feature request: A model to fetch images from the internet or a model to generate the images?

### ISSUE THREAD

**Issue by Irene-123** [lencx/ChatGPT#122]
Fetching images or generating images at a basic level would be a helpful feature. I researched, `how to fetch images from Google with the help of AI` and also `How to generate images with the help of AI`. <br>
Currently, fetching images would be a start and I was wondering if people are already working on either model. I want to be a part of and contribute to the AI model for images. 

### ChatGPT does not access the data on the internet. 

ChatGPT does not access the data until requested for text answers. This creates a hindrance to fetching the images from the internet and this will make lose the charm and ideology of chatGPT and inclines towards building a model to generate the images.

**Comment by lencx** [comment]
I don't understand what you mean, can `chat.openai.com` currently generate images? The ChatGPT desktop application is just a wrapper for the `chat.openai.com` website.

**Comment by Irene-123** [comment]
Nah, It can't yet. A feature request.

![image](https://user-images.githubusercontent.com/58950467/210165245-3d221b4c-a615-41ee-b6de-a4c4c53afb41.png)

And it would be nice if chatGPT could generate basic images like the above. 

## Idea for a feature request.

- A model to fetch model from the internet. 
- A model to generate images (AI)

**Comment by lencx** [comment]
So based on the descriptors generated by chatgpt then search for images on the internet?

**Comment by Irene-123** [comment]
Yes, exactly what I meant. I tried it on this [site](https://labs.openai.com/e/KghPjQUVSrw12oTmCYbNmV2c) can we integrate this is into chatGPT or people are already working on it? : D

**Comment by lencx** [comment]
I can try it, it may take some time.

**Comment by Irene-123** [comment]
How can I contribute to it?

**Comment by lencx** [comment]
This project is built using [tauri](https://tauri.app/), which requires both rust and js related technologies. I'm not quite sure about your programming experience.

**Comment by Irene-123** [comment]
I'm not unknown to Rust and Js, yes indeed a beginner. I can try my best to help some seniors with building, testing, references, ideas, readmes, and documentation. Here's my [social profile](https://www.linkedin.com/in/kirtidineshpurohit/) for a quick idea about me.

**Comment by lencx** [comment]
I read your profile and it was excellent. I don't have much experience either and this project is just an amateur attempt.
