### ISSUE TITLE
[Bug]输入没有反应，点击提供的四个选项也没有反应。控制台有报错

### ISSUE THREAD

**Issue by wo0o0ow** [lencx/ChatGPT#1220]
### Non-ChatGPT bug

- [X] This issue does not occur on chat.openai.com and only occurs on this app.

### Version

1.1.0

### Bug description

输入得不到反应，但是openai官网正常。打开控制台发现有报错
![6014e992509df690e10bfd2559ca1be](https://github.com/lencx/ChatGPT/assets/46042818/4d382f73-9b3e-45e2-b526-729227abb296)

### OS

Windows11

**Comment by liyaodev** [comment]
官网也是这个错，不确定是不是今天升级Google的原因，有没有前端同学指导一下？

**Comment by Calvin-Shen** [comment]
今天貌似，输入不能发送了，没有回复

**Comment by wo0o0ow** [comment]
> 官网也是这个错，不确定是不是今天升级Google的原因，有没有前端同学指导一下？

官网能使用的，应该就是程序出啥问题了

**Comment by jigang-amax-zhong** [comment]
官网可以的，这个客户端现在输入得不到响应

**Comment by caroyou** [comment]
使用无痕模式可以使用，尝试清楚缓存看看吧

**Comment by cqsbreathyou** [comment]
软件端输入消失无法发送，查了网上相关信息，清空了浏览器缓存和使用无痕模式后可以在网页端使用

**Comment by liyaodev** [comment]
> 官网也是这个错，不确定是不是今天升级Google的原因，有没有前端同学指导一下？

已确认，无痕模式可以

**Comment by TangGitHub888** [comment]
![1709968213490](https://github.com/lencx/ChatGPT/assets/162779858/0e5e6ef4-8252-40f0-980f-4e54308e3eab)
Nothing happens when typing, nor does clicking on the four options provided. No error is displayed on the console

**Comment by HL-Light** [comment]
好像是官方的bug，需要清楚cookie并切换语言重新刷新，或者用无痕模式，不知道这个软件端怎么解决

**Comment by thierry-laval** [comment]
It works for me.

MacOS Sonoma system
ChatGPT Application Version 1.1.0 (20230803.134227)

My solution:
In the application, I used the console to clear the cache, deleted the preferences folder (.chatgpt) via the Finder on my Apple system, restarted the application which asked me for my access codes. And the chat started working normally again.

**Comment by caroyou** [comment]
我的处理方式是，打开 help-toggle developer tools -应用程序-清除所有的cookies和本地存储，会话存储，重新登陆后可以继续使用。我的系统是win10

**Comment by lp1018** [comment]
> 我的处理方式是，打开 help-toggle developer tools -应用程序-清除所有的cookies和本地存储，会话存储，重新登陆后可以继续使用。我的系统是win10

it was helpful

**Comment by JustinJustinJustinJustinJustin666** [comment]
> ![屏幕截图 2024-03-09 215209](https://private-user-images.githubusercontent.com/137679394/311441840-6e610562-6fee-4de3-8404-83cffc7ea2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMzY5NzcsIm5iZiI6MTcxMDAzNjY3NywicGF0aCI6Ii8xMzc2NzkzOTQvMzExNDQxODQwLTZlNjEwNTYyLTZmZWUtNGRlMy04NDA0LTgzY2ZmYzdlYTJkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwMjExMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjhkODE4Yzk4YjUyY2JiNTAyZjBiYjM2OTUzNmNjNjE1ZDFjYzAyYWUyNDc5Y2ZkZDIxYTFhNTViODU3YWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MFfeEBgY-HTx5W06AfHPjnwhbUs-eIK8DYiQE-HTB4A) Here is the solution. You guys can also find the solution [here](https://mp.weixin.qq.com/s/p5pjKRqJ5QE7MU_KOy7lXw)

This method works

**Comment by wo0o0ow** [comment]
Here is the solution. You guys can also find the solution[https://mp.weixin.qq.com/s/p5pjKRqJ5QE7MU_KOy7lXw](url)

**Comment by wo0o0ow** [comment]
> > ![屏幕截图 2024-03-09 215209](https://private-user-images.githubusercontent.com/137679394/311441840-6e610562-6fee-4de3-8404-83cffc7ea2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMzY5NzcsIm5iZiI6MTcxMDAzNjY3NywicGF0aCI6Ii8xMzc2NzkzOTQvMzExNDQxODQwLTZlNjEwNTYyLTZmZWUtNGRlMy04NDA0LTgzY2ZmYzdlYTJkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwMjExMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjhkODE4Yzk4YjUyY2JiNTAyZjBiYjM2OTUzNmNjNjE1ZDFjYzAyYWUyNDc5Y2ZkZDIxYTFhNTViODU3YWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MFfeEBgY-HTx5W06AfHPjnwhbUs-eIK8DYiQE-HTB4A) Here is the solution. You guys can also find the solution [here](https://mp.weixin.qq.com/s/p5pjKRqJ5QE7MU_KOy7lXw)
> 
> This method works

thanks

**Comment by zljn** [comment]
官网的话，可以将点击左下角头像，将那里Settings中的Language (Alpha)改成英文后，刷新网页。(*/ω＼*)

**Comment by wo0o0ow** [comment]
已解决，请参考以上解决办法。
