### ISSUE TITLE
[Bug]mac m1 版本安装完成后，打开时提示文件已损坏

### ISSUE THREAD

**Issue by jkl0898** [lencx/ChatGPT#1228]
### Non-ChatGPT bug

- [X] This issue does not occur on chat.openai.com and only occurs on this app.

### Version

v1.0.0

### Bug description

下载mac aarh 架构的dmg 文件在mac m1 系统安装完成后，打开chatgpt时提示文件已损坏无法使用。

### OS

mac pro m1

**Comment by Zephyr0ne** [comment]
终端打开   输入xattr -cr (一定有个空格)  然后在访达里面打开应用程序 把这个app拖进来 点回车就可以了

**Comment by jkl0898** [comment]
> 终端打开 输入xattr -cr (一定有个空格) 然后在访达里面打开应用程序 把这个app拖进来 点回车就可以了

<img width="823" alt="image" src="https://github.com/lencx/ChatGPT/assets/14175165/b35efdfa-0d00-47fc-a054-2144eb81a524">
<img width="598" alt="image" src="https://github.com/lencx/ChatGPT/assets/14175165/df7ed8c3-f9a9-4b6a-ad57-d33dc41e6efb">

你好。根据建议，在终端里面输入xattr -cr 时提示参数不足。然后安装完chatgpt 后打开时报文件已损坏。 请问可以详细说明下具体如何操作吗？ 谢谢！

**Comment by jkl0898** [comment]
> 终端打开 输入xattr -cr (一定有个空格) 然后在访达里面打开应用程序 把这个app拖进来 点回车就可以了
已解决了，谢谢～ 解决方法同时参考以下文档：
https://github.com/lencx/ChatGPT/blob/main/README-ZH_CN.md
<img width="1072" alt="image" src="https://github.com/lencx/ChatGPT/assets/14175165/8db86ba8-562b-4d01-9e6a-1cd44e5c1beb">
