### ISSUE TITLE
Limit response length

### ISSUE THREAD

**Issue by thewh1teagle** [lencx/ChatGPT#124]
Is there a way to limit the response length? 
Sometimes chatGPT can response back with huge text, which cost more. 
Is there a way to limit it? like we have in the playground of OpenAI website?

**Comment by lencx** [comment]
It is only a wrapper for chat.openai.com and cannot restrict the results

**Comment by Manamama** [comment]
An end-user tip: you can use the prompt itself, see the examples of the in-built [Awesome prompts](https://github.com/f/awesome-chatgpt-prompts).

**Comment by yl1321183** [comment]
您的邮件已收到，谢谢！
