### ISSUE TITLE
[Bug] Can't pass the auth.openai.com

### ISSUE THREAD

**Issue by emako** [lencx/ChatGPT#1242]
### Non-ChatGPT bug

- [X] This issue does not occur on chat.openai.com and only occurs on this app.

### Version

v1.1.0

### Bug description

Can't pass the auth.openai.com but I can use my Google Chrome browser to login.

![image](https://github.com/lencx/ChatGPT/assets/24737061/c9ca8833-4fbf-4444-a278-f395b863c200)

### OS

Windows11 23H2

**Comment by zsp1756291108** [comment]
how to solve this problem??

**Comment by mxdlzg** [comment]
Maybe need to update the project Tauri version?

**Comment by GoBooth** [comment]
same issue.. I think the Dev abondoned this project, "noi" is the replacement for this.

**Comment by tenderzada** [comment]
+1

**Comment by yitianlian** [comment]
i also meet with this issue

**Comment by CJwens** [comment]
same question  一样的问题

**Comment by emako** [comment]
最近发现，gpt支持不登录就使用以来，大量基于Chrome核心的浏览器都不能PASS真人检测了，老实用最新的Chrome浏览器吧
---
Recently, it was found that gpt support is used without logging in, and a large number of browsers based on Chrome core cannot pass the real person detection, so let's use the latest Chrome browser
