### ISSUE TITLE
Did my prompt sent to any server?

### ISSUE THREAD

**Issue by miguelgargallo** [lencx/ChatGPT#125]
When I prompt, does this app send my prompt and answer to a server outside the official and my computer? Just a question.

**Comment by lencx** [comment]
Your prompts will only be sent to the official website (`chat.openai.com`) and the application will not save any of your personal data to be transferred to third parties. The configuration data are saved as files in your operating system (if there is still doubt, you can check the source code, it is completely open source, please feel free to use it).

**Comment by miguelgargallo** [comment]
Thanks
