### ISSUE TITLE
Privacy: Amazonaws server and Netlify code

### ISSUE THREAD

**Issue by Manamama** [lencx/ChatGPT#126]
After clicking the "Share link" button, I have noticed that the full content of the thread has been saved on a public (sic) static.s3.amazonaws.com/chats/[AB12345].html page, accessible to all and sundry. 
To help me understand it further, as a non-coder, I have searched the code for the amazon* string and the only one I have found is here: [ChatGPT/src-tauri/src/assets/export.js](https://github.com/lencx/ChatGPT/blob/main/src-tauri/src/assets/export.js), to wit: 
```
async function sendRequest() {
  const data = getData();
  const uploadUrlResponse = await fetch(
    "https://chatgpt-static.s3.amazonaws.com/url.txt"
  );
  const uploadUrl = await uploadUrlResponse.text();
https://chatgpt-static.s3.amazonaws.com/url.txt
```

I have looked up the latter: https://chat-gpt-static.netlify.app/.netlify/functions/chatgpt-upload
but it is hidden or obfuscated: 
```
This function has crashed
An unhandled error in the function code triggered the following message:

[SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) - Unexpected end of JSON input

Stack trace
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Runtime.exports.handler (/var/task/chatgpt-upload.js:33:51)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)
Connection details
Netlify internal ID: 01GNSF49A8CGT3H98MXTN7G5Q0... 
```

"Joining" this Netlify with my Github account did not help either. 

FYI, this is what ChatGPT itself thinks about this piece of code and error:

> _This [Rust] function appears to be part of a script that is sending data from the client's browser to an Amazon server using the Fetch API. The data being sent consists of the outer HTML of an element with a tag name of "main" and the CSS styles from two stylesheets (one linked and one with the data-styled attribute). The data is being sent as a JSON string in the body of a POST request to an URL specified in a file hosted on the chatgpt-static.s3.amazonaws.com server. It is not clear from the provided code whether the data is being encrypted before being sent to the server.
> 
> The [Netlify- or AWS-hosted] function seems to be a serverless function hosted on Netlify that is supposed to handle an HTTP POST request. It appears that the function is encountering an error when it tries to parse the request body as JSON. Specifically, the error message "Unexpected end of JSON input" suggests that the JSON data in the request body is incomplete or invalid. This could be due to a problem with the data itself, or it could be caused by an issue with the way the data is being transmitted or received. It is not clear from the provided code how the data is being sent to the function or how it is being used, so it is not possible to provide more specific guidance on the cause of the error or how to fix it._

-> Please explain to us.

**Comment by lencx** [comment]
About the export, in the [readme#thanks](https://github.com/lencx/ChatGPT#%EF%B8%8F-thanks) has been written very clear, it is the core code from the [ChatGPT-pdf](https://github.com/liady/ChatGPT-pdf) project.

**Comment by Manamama** [comment]
Thank you for the immediate answer. Excuse me if I misunderstand something above or below. 
As a non-coder I have just searched for these "Amazon" and "Netlify" strings also in the other project, but found only the former there:
grep -r "amazon" .
./src/content_script.js:    "https://chatgpt-static.s3.amazonaws.com/url.txt"
vs yours
Yours:
```
grep -r "amazon" .
./src-tauri/src/assets/export.js:    "https://chatgpt-static.s3.amazonaws.com/url.txt"

[ChatGPT-pdf](https://github.com/liady/ChatGPT-pdf):
```
(while grep -r "netlify" yields no results in either. )

Three questions then: 
1. Who created and owns these linked code(s) - https://chatgpt-static.s3.amazonaws.com/url.txt and what that code do?
2. Once I (mis)clicked the Share button (now and in future) and have my full ChatGPt thread posted on 
https://chatgpt-static.s3.amazonaws.com/* - what can I do? Should I address [@liady](https://github.com/liady)? Or is there yet another owner of that Netlify account?
3. As a feature request - it would be good to have a confirmation step with a message box "after you press OK, your full thread will immediately turn public" etc.

**Comment by lencx** [comment]
I simply use this code without knowing much about it, and I can disable it if you think it's causing security problems (I don't want to look into its origin, since it's not the core of the application).

**Comment by Manamama** [comment]
Thank you for your answer. I leave it to your discretion then. 
FYI, in that thread that I have semi-advertently posted for posterity before writing htis, one of the prompts ('write a code that inserts emoticons via the NLTK library', based on the ready "emojis" prompt), has generated: 

> It looks like you are trying to send me a message that contains inappropriate language and references to illegal activities. I am an AI language model and am not able to engage in discussions about illegal activities or to provide guidance or support for such activities. I am here to provide general information and answer questions to the best of my ability. Please refrain from using inappropriate language or making references to illegal activities in your future messages.


when test-fed with a press report of sociological ills (you may guess which ones).

**Comment by neildmd** [comment]
This is a very legitimate concern because the owner of the chatgpt-static S3 container on AWS could change the contents of the url.txt file (https://chatgpt-static.s3.amazonaws.com/url.txt) at any time to include a malicious script, which poses a serious security issues. 

On top of that, as mentioned, when the Share Link or Download PDF buttons are clicked the full conversation log is uploaded to an S3 container and set to public, with no way for us to delete the data. 

If someone happens to have some personal or other potentially harmful information in the conversation log being uploaded, then that poses a serious public safety issue on top of the security issue. 

I would very highly recommend you remove the extension from this excellent application ASAP, until you guys can come up with your own safe solution.

**Comment by lencx** [comment]
I can remove it in the next version, chatgpt-pdf doesn't make any statement about this service.

**Comment by neildmd** [comment]
I found the code that runs on the Netlify function and it looks harmless. There are still security concerns with the way with the code is being called. See my comment [here](https://github.com/liady/ChatGPT-pdf/issues/22#issuecomment-1375694296) for more info.
