### ISSUE TITLE
Feature Requests: 'open on system startup' and 'hide on startup'

### ISSUE THREAD

**Issue by heldheld** [lencx/ChatGPT#131]
As title states, two options:
-Open on system startup: Start the app when the OS starts
-Hide on startup: When you start the app, start it hidden or immediately push the underlying command that executes when you press the 'global shortcut'.

The 'hide on startup' option is more important, since we can of course just put a shortcut of the app in the startup folder on Windows, and I'm sure there are similar options on Linux and macOS.

**Comment by Manamama** [comment]
A tip: you can just start it minimized. Here is what Mr ChatGPT itself advises about this topic: 

> There are a few different ways to start an application minimized on startup:
> 
> If you are using Windows, you can create a shortcut to the application and then specify the shortcut to run minimized by right-clicking on the shortcut and selecting "Properties", then going to the "Shortcut" tab and checking the "Run: Minimized" option under "Run". You can then place the shortcut in the Startup folder to have the application start minimized when you log in.
> Some applications have a command line option that allows you to start them minimized. For example, you could use the start command in Windows and specify the minimized argument to start an application minimized: start /min app.exe. [Yes, this is what you propose here.]
> If you are using a third-party application launcher, such as AutoHotkey or RocketDock, you can use the tools provided by that application to start other applications minimized. For example, in AutoHotkey you can use the Run command with the minimized option to start an application minimized: Run, app.exe, , minimized.
> If you are using a desktop environment, such as Gnome or KDE, you may be able to specify that certain applications should start minimized by default in the desktop settings.

**Comment by heldheld** [comment]
> A tip: you can just start it minimized. Here is what Mr ChatGPT itself advises about this topic:
> 
> > There are a few different ways to start an application minimized on startup:
> > If you are using Windows, you can create a shortcut to the application and then specify the shortcut to run minimized by right-clicking on the shortcut and selecting "Properties", then going to the "Shortcut" tab and checking the "Run: Minimized" option under "Run". You can then place the shortcut in the Startup folder to have the application start minimized when you log in.
> > Some applications have a command line option that allows you to start them minimized. For example, you could use the start command in Windows and specify the minimized argument to start an application minimized: start /min app.exe. [Yes, this is what you propose here.]
> > If you are using a third-party application launcher, such as AutoHotkey or RocketDock, you can use the tools provided by that application to start other applications minimized. For example, in AutoHotkey you can use the Run command with the minimized option to start an application minimized: Run, app.exe, , minimized.
> > If you are using a desktop environment, such as Gnome or KDE, you may be able to specify that certain applications should start minimized by default in the desktop settings.

Just tried all the methods mentioned, none seem to work for me on Windows 10.

**Comment by heldheld** [comment]
I mean, I can make it minimize with an AHK script that sends the designated 'global shortcut' after the app starts, but that's not really the point of this feature request. It should be a native option, not a hacky solution.

**Comment by Manamama** [comment]
Sorry that I won't help you by checking it directly - last time I used Windows was a year ago. 
Let us ask Ms Google, feeding her with one of the answers of Mr ChatbotGPT. 
Voila, the fourth hit, with screenshots:
https://www.ghacks.net/2015/10/12/how-to-start-windows-program-minimized/
It thus seems to be in-built in Windows (and so is in Ubuntu).

**Comment by heldheld** [comment]
> Let us ask Ms Google, feeding her with one of the answers of Mr ChatbotGPT.
> Voila, the fourth hit, with screenshots:
> https://www.ghacks.net/2015/10/12/how-to-start-windows-program-minimized/
> It thus seems to be in-built in Windows (and so is in Ubuntu).

This does not work. I've already tried this, tried it once again for the new 0.8 version, and it still does not work. It works on most other applications, but it does NOT work on this ChatGPT application. The ChatGPT application just opens like normal. The maximized option also does not affect the opening of the application. If this did work, of course I would have never opened up this issue in the first place.


> Oh! It seems to be fixed in the latest 0.8 release!
> 
> ```
> fix:
>     close the main window and hide it in the tray (windows systems)
> ```

This is a separate issue. I'm glad to see that issue resolved, but has nothing to do with _this_ issue.

**Comment by heldheld** [comment]
Why has this been closed as completed? The issue has not been addressed. Either address it, or close it as 'won't fix'.

**Comment by heldheld** [comment]
Then please close it as 'won't fix' because this is misleading.
