### ISSUE TITLE
[Build Error] [vite:css] [postcss] Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by Irene-123** [lencx/ChatGPT#137]
### Error message

Running the `yarn dev` command gives me this error.

![image](https://user-images.githubusercontent.com/58950467/210363357-77bdf544-bd89-474f-b448-6ff99073692f.png)

So I searched on Google as it seemed a generic error and found this [link](https://stackoverflow.com/questions/74791058/sanity-io-vite-internal-server-error-postcss-cannot-read-properties-of-unde) to fix it. 

Therefore, I added a file named `tailwind.config.js` in the root folder and pasted the recommended code over there. And it builds almost all packages but threw me an error at the end regarding the `tauri private key`.

![image](https://user-images.githubusercontent.com/58950467/210363839-8ef7f268-08fc-4c1e-8692-ed34691078b7.png)

I went through the `.gitignore` to check for a `.env` file if in case `private key` is being used by the developers. And I tried generating a `private key` by tauri installation but I'm not able to generate a private key or, maybe I don't know whether I need to use it or going on the right path to fix it. 

Also, yes I found this [issue](https://github.com/tauri-apps/tauri/discussions/4451) on the `tauri apps repository`, but I couldn't understand what file I need to create. 

Thankyou. 

### OS

Windows 11

**Comment by lencx** [comment]
Regarding the private key, as I answered here, it can be completely ignored because it doesn't affect the build (it's a signature verification for automatic updates of the application) https://github.com/lencx/ChatGPT/issues/123

**Comment by Irene-123** [comment]
Yes, I've added the `tailwind.config.js` and after that, it gives me the error to `private key`

**Comment by lencx** [comment]
The private key error can be ignored, is there an installation package generated?

**Comment by Irene-123** [comment]
Do you mean, `installation package error`?  Else works fine, but this private key error doesn't the `yarn build` process complete.

**Comment by lencx** [comment]
You can set `updater > active` to `false` in `tauri.conf.json`.

**Comment by Irene-123** [comment]
Works. Thank you.

**Comment by lencx** [comment]
It only exists in your local development environment, because if you turn off `updater`, the application will disable automatic updates
