### ISSUE TITLE
[Bug] Unacceptable TLS certificate

### ISSUE THREAD

**Issue by ndaidong** [lencx/ChatGPT#138]
### Version

v0.7.4

### Bug description

After success login, it opens a blank page with error "Unacceptable TLS certificate".

![Screenshot from 2023-01-03 22-20-34](https://user-images.githubusercontent.com/1809619/210386822-0297ca10-35c4-49ea-8852-41f9931bb382.png)

### OS

Debian 11.6

### Environment

- Kernel 5.10.0-20-amd64
- Gnome 3.38.5
- Graphic card NVIDIA GeForce MX250

**Comment by Manamama** [comment]
A tip: it may be due to the backend https://chat.openai.com/chat outages, which have happened +5 times today.

**Comment by ndaidong** [comment]
Today it puts up a notice "ChatGPT is at capacity right now". It seems that @Manamama is right, the issue relates to ChatGPT server, not this app's problem.
