### ISSUE TITLE
[Bug]Win11 arm 安裝錯誤

### ISSUE THREAD

**Issue by Grasseed** [lencx/ChatGPT#139]
### Version

v0.7.4

### Bug description

![image](https://user-images.githubusercontent.com/44409920/210413248-a12acd9f-0ca4-46c0-9b37-d23753fe4fee.png)
![image](https://user-images.githubusercontent.com/44409920/210413363-05b5d4a5-accc-4fa9-89e3-2505a82717f2.png)
下載.msi安裝時出現錯誤

### OS

windows11 arm64

**Comment by lencx** [comment]
windows10 以后的版本安装 .msi 或 .exe 的出现 2503、2502 等错误主要是因为系统权限受限。百度百科中有操作视频可以查看 https://jingyan.baidu.com/article/cdddd41c97e94853ca00e17e.html
