### ISSUE TITLE
ChatGPT Desktop Application: Cannot logout

### ISSUE THREAD

**Issue by aggelosy** [lencx/ChatGPT#1392]
My account was asked to change password and after changing the desktop application stayed in this screen (even after uninstalling and reinstalling it):

**Update:**
I found a workaround by using the Developer Tools Shortcut to Clear Cookies and it led me to the login page after a refresh.

![image](https://github.com/user-attachments/assets/d420e6d1-56a3-4976-9fc1-61f092e67ad0)

**Comment by obarak** [comment]
For anyone landing here: recent ChatGPT Windows app (Nov. 24) wouldn't open Developer Tools using the common methods I could find. But it turns out they added a "Log Out" command when right clicking on the app's taskbar icon and that works perfectly.
