### ISSUE TITLE
[Feature][Track] publish package to winget 

### ISSUE THREAD

**Issue by yixinBC** [lencx/ChatGPT#142]
### Feature description

this issue tracks #129 
All updates about the [winget-pkgs pr status](https://github.com/microsoft/winget-pkgs/pull/92812) and the implemention/development of auto-release scripts will be discussed here first.

**Comment by manudss** [comment]
- [ ] Version 0.7.4 publishing in progress : https://github.com/microsoft/winget-pkgs/pull/92812 
- [ ] Updates docs to explain how to install with winget
- [ ] Updates release script, to publish new version in winget repository.

**Comment by lencx** [comment]
@manudss Thank you very much for your contribution. Can you tell me what command I need to execute if I want to write `winget` install application in readme?

**Comment by yixinBC** [comment]
> There seems to be a collision between this package and https://github.com/sonnylazuardi/chatgpt-desktop/. They both install to `C:\program files\chatgpt\chatgpt.exe`, or `ChatGPT.exe` but since Windows is case insenstive one overwrites the other (last installed wins).

Does this issue happen when you use the `winget` installation?If not, I don't think that we should talk about that topic in this issue.
I read some `winget` documentations and found that it will install the packages into a specific directoty,obviously not `C:\Program files`.

**Comment by manudss** [comment]
Hi, the version was already published, you can find it here : https://winstall.app/apps/lencx.ChatGPT 

The command to install is : `winget install --id=lencx.ChatGPT  -e`

**Comment by lencx** [comment]
@manudss Thanks, we've updated it in the readme.

**Comment by yixinBC** [comment]
> @manudss Thanks, we've updated it in the readme. I have a question, there are two spaces before `-e`, I formatted it as one space, will it have any effect?

one space is enough.

**Comment by yixinBC** [comment]
have a look at the [github actions detail](https://github.com/lencx/ChatGPT/actions/runs/3860620937/jobs/6581195731), and I think we encountered an error.

**Comment by manudss** [comment]
Hi @yixinBC, sorry for the delay in response, I didn't have time to look before. It's an access problem, the Github token doesn't have the rights to access the repos:

`  remote: Permission to lencx/winget-pkgs.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/lencx/winget-pkgs.git/': The requested URL returned error: 403`
--- 
In the script for the releaser, https://github.com/vedantmgoyal2009/winget-releaser it specifies that the token must have the following rights: (Is this the case?)

> The token should have the public_repo scope.
> Note Do not directly put the token in the action. Instead, create a repository secret containing the token and use that in the workflow. See [using encrypted secrets in a workflow](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) for more details.

**Comment by lencx** [comment]
@manudss token I have modified, just not released a new version to verify.

**Comment by manudss** [comment]
The version 0.8 have already been published by someone else : https://github.com/microsoft/winget-pkgs/pull/93238

**Comment by lencx** [comment]
The script is already working properly https://github.com/microsoft/winget-pkgs/pull/93598

**Comment by JoscarTheDane** [comment]
### I fixed this by instructing an uninstall and then a reinstall:

Installer failed with exit code: 1603
Installer log is available at: C:\Users\jshev\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-lencx.ChatGPT.0.11.0-2023-02-25-12-01-15.773.log
(base) PS C:\Users\jshev> winget uninstall chatgpt
Found ChatGPT [lencx.ChatGPT]
Starting package uninstall...
Successfully uninstalled
(base) PS C:\Users\jshev> winget uninstall sonnylab.chatgpt
No installed package found matching input criteria.
(base) PS C:\Users\jshev> winget uninstall chatgpt
No installed package found matching input criteria.
(base) PS C:\Users\jshev> winget install --id=lencx.ChatGPT -e --version 0.11.0
Found ChatGPT [lencx.ChatGPT] Version 0.11.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Successfully installed
(base) PS C:\Users\jshev>
