### ISSUE TITLE
[Bug]Google sign in problem. This browser or app may not be secure. 此浏览器或应用可能不安全。

### ISSUE THREAD

**Issue by BertramRay** [lencx/ChatGPT#143]
### Version

v0.7.4

### Bug description

使用谷歌账号登陆时提示浏览器或应用不安全。
英文提示：Couldn’t sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
中文提示：无法登录
此浏览器或应用可能不安全。
请尝试使用其他浏览器。如果您使用的是受支持的浏览器，可以重新尝试登录。

### OS

Windows11

**Comment by lencx** [comment]
应用使用的是操作系统内置浏览器，出现这种提示大概率是系统相关设置的问题，和应用本身无关。

**Comment by lencx** [comment]
你尝试设置一个 `user agent` 试试，在 `Control Center` 里。

**Comment by BertramRay** [comment]
> 你尝试设置一个 `user agent` 试试，在 `Control Center` 里。

很好地解决了问题。具体而言，我修改了User Agent (Window)的配置，将其改为了我在自己的Chrome浏览器中用到的User-Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**Comment by hayoial** [comment]
我的chatgpt账号也是用google oauth登录的，多次尝试无法使用本软件。

环境：win 安装了 proxifier+clash, 本软件设置了 user-agent。

为什么：登录的时候一选 google，还是报错。
提示”accounts.google.com 重定向次数过多。“
或者"accounts.google.com 花了太长时间进行响应"。

**Comment by buzz998** [comment]
> > 你尝试设置一个 `user agent` 试试，在 `Control Center` 里。
> 
> 很好地解决了问题。具体而言，我修改了User Agent (Window)的配置，将其改为了我在自己的Chrome浏览器中用到的User-Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

请问具体怎么修改？小白

**Comment by BertramRay** [comment]
需要更改在Control Center 里的User Agent。不过目前我已经没有在使用该客户端，相关信息可能已经落伍。

**Comment by BertramRay** [comment]
> 

需要更改在Control Center 里的User Agent。不过目前我已经没有在使用该客户端，相关信息可能已经落伍。

**Comment by BertramRay** [comment]
> > > 你尝试设置一个 `user agent` 试试，在 `Control Center` 里。
> > 
> > 
> > 很好地解决了问题。具体而言，我修改了User Agent (Window)的配置，将其改为了我在自己的Chrome浏览器中用到的User-Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
> 
> 请问具体怎么修改？小白

需要更改在Control Center 里的User Agent。不过目前我已经没有在使用该客户端，相关信息可能已经落伍。
