### ISSUE TITLE
[Bug] start chat-gpt from console on ubuntu : "22.04.1 LTS (Jammy Jellyfish)"

### ISSUE THREAD

**Issue by xbaker** [lencx/ChatGPT#146]
### Version

v0.7.3

### Bug description

Hi, 
when i start chat-gpt from the terminal i got this error:

[2023-01-04][08:57:50][chatgpt::app::setup][INFO] stepup
[2023-01-04][08:57:50][chatgpt::app::setup][INFO] global_shortcut_start
[2023-01-04][08:57:50][chatgpt::app::setup][INFO] is_registered: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlobalShortcut(InvalidAccelerator("Unable to register global shortcut"))', src/app/setup.rs:36:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Runtime(FailedToSendMessage)', src/app/window.rs:23:14

### ENV
chat-gpt_0.7.3_amd64.deb

OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### OS

ubuntu 22.04

**Comment by lencx** [comment]
Please try version v0.7.4, which fixes this issue.
