### ISSUE TITLE
[Bug] Previous chats do not show up

### ISSUE THREAD

**Issue by kuanyong-wong-partior** [lencx/ChatGPT#158]
### Version

0.7.4

### Bug description

Previous chats do not show up in the side bar.
![gnome-shell-screenshot-NKOMY1](https://user-images.githubusercontent.com/119275985/210940598-00ab6f37-f7ac-4855-a6ec-7aafc90942c3.png)

### OS

Debian GNU/Linux 11

**Comment by lencx** [comment]
Try refreshing the page, or reopening the app, they don't sync.

**Comment by kuanyong-wong-partior** [comment]
I already tried it.

[simplescreenrecorder-(2).webm](https://user-images.githubusercontent.com/119275985/211538807-e0e1d298-7c25-4902-b87f-088cf78509b5.webm)

**Comment by lencx** [comment]
The data synchronization needs to be done by openai itself and is not related to the app. You can refresh the page via the right mouse button menu. You can now download version v0.9.2.
