### ISSUE TITLE
Checking if the site connection is secure

### ISSUE THREAD

**Issue by Gutreja** [lencx/ChatGPT#159]
### Version

v1.8

### Bug description

stuck at "Verify if you are human"
chat.openai.com needs to review the security of your connection before proceeding.

### OS

macOS ventura

**Comment by lencx** [comment]
If you are a user in China, you can check here (https://github.com/lencx/ChatGPT/discussions/133), most of the reasons for not being able to access are caused by the network.

**Comment by Gutreja** [comment]
I am based in USA. I was able to access till yesterday, not working since today morning

**Comment by lencx** [comment]
It is possible that openai has updated its security policy and this is not caused by the application.

**Comment by Gutreja** [comment]
How should I proceed then?

**Comment by lencx** [comment]
Network problems, I can not help you.
