### ISSUE TITLE
[Feature] multiple chat gpt accounts 

### ISSUE THREAD

**Issue by darvin** [lencx/ChatGPT#161]
### Feature description

support multiple chat gpt accounts simulatinously

**Comment by Manamama** [comment]
A tip: run it in separate environments. 
See the code or use "Toggle Developer's Tools" from the menu - it is [an "API"](https://github.com/lencx/ChatGPT/issues/162).

**Comment by neildmd** [comment]
This might actually be straight forward to implement using the profiles feature of the Edge platform that this app is built upon.

**Comment by Manamama** [comment]
Do consider [OpenAI's ToUs](https://openai.com/terms/) then, current and future, especially its 2 C (vii), e.g. the rate limitation.

**Comment by Manamama** [comment]
FYI, I am running more and more into
`Too many requests in 1 hour. Try again later.`
but then I had created a couple of OpenChat AI accounts some months ago, somehow in violation of their ToUs, see above.  (A tip for the cognoscenti: yopmail.com plus e.g. the "2nd number" app ;).
