### ISSUE TITLE
[Feature] api 

### ISSUE THREAD

**Issue by darvin** [lencx/ChatGPT#162]
### Feature description

provide HTTP or web sockets API for communicating with chatGPT running in the window

**Comment by Manamama** [comment]
?
But this program is the "API". Your request would make it a "double API". 
-> Just modify the code to do what you wish (with acknowledgement etc.)

**Comment by neildmd** [comment]
@Manamama This program is not an API. It is an edge based browser modification in which the ChatGPT website runs. He is requesting additional functionality to interface with OpenAI's API directly. Please look up what API means, it is an interface for programs to interact with, kind of line a command line that software can use behind the scene to send commands or make requests from a server.

**Comment by Manamama** [comment]
@neildmd You are right. While I (think I have) understood what an API is (see also [my other, more technical comments or bug reports in here](https://github.com/lencx/ChatGPT/issues)), I used the "API" (consciously placed in quotes there) in _sensu largo_. 

To self-check and self-learn how it may be understood and as a meta-experiment, I have fed also this conversation to our "uncle ChatGTP" itself, below. You are right and I was wrong in not being precise: 

> It appears that @darvin is requesting an API for the ChatGPT program, while @Manamama is misunderstanding the request and suggesting that the ChatGPT program itself is an API. @neildmd correctly explains that ChatGPT is not an API, but rather a program that interacts with OpenAI's API.
> 
> It is possible that Manamama is using the term "API" metaphorically to refer to an interface or a means of communication between two programs or systems. However, in the context of this conversation, it seems that the term "API" is being used to specifically refer to an application programming interface, which is a set of rules and protocols for building software and applications that allows them to communicate with one another.

I stand corrected.

**Comment by neildmd** [comment]
@Manamama Just for further clarity, it's response was referring to the ChatGPT website as the program which interfaces with the API, not this specific program we're commenting under called ChatGPT. It just has no context to understand this, so it assumes we're taking about the website. 

Personally I think this application needs a slight name change: 1) To avoid trademark issues. 2) To make it more clear what the application is. "ChatGPT Enhanced GUI" or something along those lines.

**Comment by Manamama** [comment]
I agree. 
As for the (brand) names themselves, see [my comment](https://github.com/lencx/ChatGPT/issues/161#issuecomment-1374819519).
