### ISSUE TITLE
[Feature] Flatpak (Flathub) packaging

### ISSUE THREAD

**Issue by ajvsol** [lencx/ChatGPT#163]
### Feature description

Would be great to have this app available via Flatpak.

### Motivation

Many people prefer/need Flatpak for apps, such as immutable distros, or want it for the automatic updates, or sandboxing, etc.

**Comment by lencx** [comment]
Nowadays, there are too many installation methods, which is a complicated thing for maintenance. We prefer to use the download link, because the application has built-in automatic updates, and all subsequent installation can be completed by the update prompt.

**Comment by IntoTheVoid-900** [comment]
If thats the case, I still think you should replace AppImage with Flatpak, Flatpaks are more secure, integrate with the host system better, and work on immutable distros like SteamOS (on the Steam Deck), Fedora Silverblue and VanillaOS.

**Comment by lencx** [comment]
Flatpak related build I have limited ability and need to learn it. I hope someone with this ability can contribute PR.
