### ISSUE TITLE
Application Error on macOS [Bug]

### ISSUE THREAD

**Issue by ZackonMac** [lencx/ChatGPT#164]
### Version

0.7.4

### Bug description

When I launch this application on macOS Mojave, I get a blank page with the following message: Application error: a client-side exception has occurred (see the browser console for more information).

This problem occurred after several failed connections on my ChatGPT account from the software. However, my account works perfectly from a browser.

### OS

macOS Mojave

**Comment by lencx** [comment]
Please provide screenshots, and the `~/.chatgpt/chatgpt.log` file.

**Comment by ZackonMac** [comment]
Here is what happens as soon as you open the software, there is a series of connection errors as you can see in the two attached screenshots :
![Capture d’écran 2023-01-07 à 10 09 53](https://user-images.githubusercontent.com/122095543/211143137-b4e2fb4f-8a72-4138-81c4-7cd1c59e6862.jpg)
![Capture d’écran 2023-01-07 à 10 11 12](https://user-images.githubusercontent.com/122095543/211143138-4d46b1b3-e020-4620-abe5-13ca74a1b85f.jpg)

**Comment by lencx** [comment]
These errors are from `chat.openai.com`, not related to the application.

**Comment by ZackonMac** [comment]
Thank you !
