### ISSUE TITLE
Do you have any script which we can import our WordPress website to create Website like ChatGPT 

### ISSUE THREAD

**Issue by nk076** [lencx/ChatGPT#166]
### Feature description

Do you have any script which we can import our WordPress website to create Website like ChatGPT

**Comment by lencx** [comment]
Do you mean to package WordPress as chatpgt-like application?

**Comment by nk076** [comment]
Yes sir

**Comment by lencx** [comment]
I'm working on this to turn it into a super app that aggregates various websites, and chatgpt is just a sub-module in the future.

**Comment by lencx** [comment]
Please install v0.10.0 version, then add the URL in `Control Center -> Awesome` and set the main application window via `Switch Origin` in `Settings`.
