### ISSUE TITLE
[Build Error] tauri.conf.json has unknown property package

### ISSUE THREAD

**Issue by SteveOlsonFSP** [lencx/ChatGPT#167]
### Error message

> yarn dev
yarn run v1.22.19
$ yarn tauri dev
$ tauri dev
[tauri]: running dev
 ERROR: tauri.conf.json has unknown property package +0ms
 ERROR: tauri.conf.json > tauri has unknown property systemTray +0ms
 ERROR: tauri.conf.json > tauri has unknown property updater +1ms
 ERROR: tauri.conf.json > tauri > allowlist['globalShortcut'] should be boolean +0ms
 ERROR: tauri.conf.json > tauri > allowlist['fs'] should be boolean +0ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property macOS +0ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property windows +1ms
 ERROR: tauri.conf.json > tauri > security > csp should be string +0ms
error Command failed with exit code 1.

### OS

Windows 10 

### Environment

VS Code Terminal

Strange, any help would be appreciated. Thank you.

**Comment by lencx** [comment]
It requires a dependency on the rust environment to build, does it exist in your environment?
