### ISSUE TITLE
[Bug] keyboardarrow keys to select the slash commands are not working

### ISSUE THREAD

**Issue by granin** [lencx/ChatGPT#168]
### Version

 0.6.10 (20221225.010727)

### Bug description

On macOS  the keyboard ⇧ (arrow up) and ⇩ (arrow down) keys to select the slash commands are not working

### OS

macOS

### Environment

M1 macOS 13.0.1

**Comment by lencx** [comment]
Please install v0.7.4, version 0.6.x does not support this feature.
