### ISSUE TITLE
v0.1.7 - Checking if the site connection is secure

### ISSUE THREAD

**Issue by Memories-SlowFever** [lencx/ChatGPT#17]
The client login has been verifying whether it is a robot, and it has not passed, but it can be done on the web page

**Comment by lencx** [comment]
Is it showing this?
<img width="500" alt="chat verifying" src="https://user-images.githubusercontent.com/16164244/206944814-3eca39ab-312b-44d8-b00c-51281cdce6dc.png">

**Comment by Memories-SlowFever** [comment]
yes，verified many times but still failed

**Comment by Memories-SlowFever** [comment]
> Is it showing this? <img alt="chat verifying" width="500" src="https://user-images.githubusercontent.com/16164244/206944814-3eca39ab-312b-44d8-b00c-51281cdce6dc.png">


yes，verified many times but still failed

**Comment by lencx** [comment]
Browser access will also be authenticated first, I'm looking for a solution.
<img width="600" alt="check" src="https://user-images.githubusercontent.com/16164244/206945991-930f89cc-9ca0-42bf-9ebe-5edb2755de7f.png">

**Comment by lencx** [comment]
I have found a solution, it can be solved by modifying `user agent`. I'll let the user customize it with a menu item.

**Comment by Memories-SlowFever** [comment]
> I have found a solution, it can be solved by modifying `user agent`. I'll let the user customize it with a menu item.

that would be great

**Comment by lencx** [comment]
Please upgrade to `v0.2.0` version, if the application cannot be opened, try to clear the configuration file directory `~/.chatgpt`, and then restart.

**Comment by Hobart10** [comment]
> Please upgrade to `v0.2.0` version, if the application cannot be opened, try to clear the configuration file directory `~/.chatgpt`, and then restart.

Still keep verifying in my case. I tried to delete all related files and folders and then reinstall.

**Comment by lencx** [comment]
You can try to edit the user agent, it is in the menu at this location `Menu -> Preferences -> User Agent`, how to input can refer to the browser `console -> navigator.userAgent`.
![image](https://user-images.githubusercontent.com/16164244/206984921-eb6e2f5d-f721-483a-954f-0aed0d9c3116.png)

**Comment by Hobart10** [comment]
> You can try to edit the user agent, it is in the menu at this location `Menu -> Preferences -> User Agent`, how to input can refer to the browser `console -> navigator.userAgent`. ![image](https://user-images.githubusercontent.com/16164244/206984921-eb6e2f5d-f721-483a-954f-0aed0d9c3116.png)

It worked. Thank you!

**Comment by Hobart10** [comment]
> You can try to edit the user agent, it is in the menu at this location `Menu -> Preferences -> User Agent`, how to input can refer to the browser `console -> navigator.userAgent`. ![image](https://user-images.githubusercontent.com/16164244/206984921-eb6e2f5d-f721-483a-954f-0aed0d9c3116.png)

It worked. Thank you!

**Comment by LeinadUchiha** [comment]
I am having the same problem with the latest version but I don't know where to find the folder you mention "~/.chatgpt".

**Comment by ashoklathwal** [comment]
Check if this help you: https://wealthquint.com/fix-chatgpt-keeps-checking-if-the-site-connection-is-secure-62248/
