### ISSUE TITLE
[Bug]Header and menu of the ChatGPT app remains light even when selecting Dark Theme

### ISSUE THREAD

**Issue by Kitty1313** [lencx/ChatGPT#172]
### Version

v.0.8.0

### Bug description

<img width="601" alt="2023-01-07 15_23_32-ChatGPT" src="https://user-images.githubusercontent.com/122160376/211152914-263d1812-ba01-4462-a14a-b8cc6d569de1.png">
Header and menu of the ChatGPT app remains light even when selecting Dark Theme. Can it be set up to get dark too?

### OS

Windows 10 Home Edition

**Comment by lencx** [comment]
Regarding the menu theme color, no solution has been found yet.
