### ISSUE TITLE
[Feature] add button to export html

### ISSUE THREAD

**Issue by MagnoAlberto** [lencx/ChatGPT#175]
### Feature description

Add a button for exporting to HTML, similar to exporting PDF, with the option of saving the file with the name of the Thread title.

### Motivation

I believe that the use of HTML is much more practical in many situations than in PDF.

**Comment by lencx** [comment]
I am implementing an export markdown function, which may make more sense than html, and I can provide a markdown editing preview interface specifically for it.

**Comment by Manamama** [comment]
See my quick tip for this [here](https://github.com/lencx/ChatGPT/issues/187#issuecomment-1380830018) - maybe too obvious.

**Comment by lencx** [comment]
Please try v0.9.0
