### ISSUE TITLE
[Bug] dalle2 cannot login

### ISSUE THREAD

**Issue by lencx** [lencx/ChatGPT#176]
### Version

v0.8.0

### Bug description

Click on login will jump to the web page, the app still shows not logged in.

### OS

mac m1

**Comment by lencx** [comment]
Appeared by chance, now everything seems to be fine.

**Comment by Manamama** [comment]
In my case (Linux, see the other posts here for full specs), for +24 hours the resulting "Chat & DALL-E 2" window has popped up empty, apart from the menu. Even toggle developers tools shows nothing. 

Speaking of which, see [my comment](https://github.com/lencx/ChatGPT/issues/161) re such brands itself, and cf. [the case of "Dalle Mini"](https://huggingface.co/spaces/dalle-mini/dalle-mini)
(And sorry for being a wet blanket here and there.)

**Comment by lencx** [comment]
> In my case (Linux, see the other posts here for full specs), for +24 hours the resulting "Chat & DALL-E 2" window has popped up empty, apart from the menu. Even toggle developers tools shows nothing.

It seems that the network is the reason, and the file is very large, my side also loaded very slow.

**Comment by Manamama** [comment]
FYI, e.g. today: 
1. Dalle window seems to time out: nothing even after +2 hours online. 
2. The main ChatGPT window - intermittent:
> We're experiencing exceptionally high demand. Please hang tight as we work on scaling our systems.

-> It may be good to provide such a "deadhand mechanism", timer with the resulting 404 or such in the code.

**Comment by lencx** [comment]
I am implementing the last relatively large function (export markdown) of this project, and it will be finished for the time being. If there are new changes to this website in the future, I will decide whether to continue adding features. I am going to develop a new project, chatgpt has a lot of restrictions, I want to make a more general website desktop tool, and then provide some system capabilities.
