### ISSUE TITLE
Remove Icon from menu bar

### ISSUE THREAD

**Issue by Erik262** [lencx/ChatGPT#178]
### Version

0.8

### Bug description

Like millions of other apps that want a place on the shiny side of the menu bar, getting rid of the app icon in the menu bar is impossible.

### OS

macOS 13.1

**Comment by lencx** [comment]
Make it configurable as a new feature, not a bug.

**Comment by carpusmedia** [comment]
Please add this as a feature

**Comment by nhershy** [comment]
Menu bar icon still exists. I don't see a way to disable it. This feature has not been complete.

**Comment by nhershy** [comment]
For clarification, we are referring to the MacOS menu bar at the top of the screen where time/battery percentage/etc is located. Because I noticed other bugs listed here mentioned "menu bar" as the bar at the top of the application windows.

**Comment by lencx** [comment]
`Preferences -> System Tray`

**Comment by av-dotcom** [comment]
Was this feature taken off? I don't see any `System Tray` option in `Preferences/Settings`.
I'm on `MacOS Sonoma 14.5` and my chatGPT version is `1.2024.179 (1720463250)`

**Comment by hxeo** [comment]
For now I am just quitting the app with cmd + q. Its a pity one cant toggle this in the preferences.

**Comment by jimsmith** [comment]
This is for Native ChatGPT

ChatGPT > Settings > App > Show ChatGPT - click the drop down menu 🎩 

![image](https://github.com/user-attachments/assets/99b2fd1e-e272-474f-8c33-2c0fe53103ce)

<img width="243" alt="image" src="https://github.com/user-attachments/assets/5c45516d-5199-4b6a-934f-88b836a7bef8">

<img width="142" alt="image" src="https://github.com/user-attachments/assets/b1444a19-3b56-429c-897d-fc8fc33ec091">

**Comment by henryhsue** [comment]
I've re-enabled the menubar icon after realizing it's needed for the hotkey to work, unless you have the main ChatGPT window open.

**Comment by hhsue** [comment]
I've re-enabled the menubar icon after realizing it's needed for the hotkey to work without the app window open.
