### ISSUE TITLE
[Bug] Left sidebar breaks in 4K resolution

### ISSUE THREAD

**Issue by Zeioth** [lencx/ChatGPT#181]
### Version

DEC 15 version

### Bug description

On 4K resolution, the left sidebar displays broken.
![screenshot_2023-01-09_07-47-57_913209582](https://user-images.githubusercontent.com/3357792/211253716-4b5cdd8b-b4e2-438c-992f-962dac8a1a50.png)

### OS

archlinux

**Comment by lencx** [comment]
Is this problem with `openai` itself? Is it normal to visit `chat.openai.com` in the browser?

**Comment by Zeioth** [comment]
It looks fine on the browser. It's just the arch app.

**Comment by lencx** [comment]
Sorry, close it first, I can't find a solution for now either. You can try the latest version to verify that it works.

**Comment by hleft** [comment]
https://github.com/lencx/ChatGPT/issues/487 same problem
