### ISSUE TITLE
[Bug] Export PDF don't works

### ISSUE THREAD

**Issue by mike37510** [lencx/ChatGPT#185]
### Version

0.8.0

### Bug description

[Bug] Export PDF don't works on Windows 10 with 0.8.0.

### OS

Windows 10

**Comment by KutsuyaYuki** [comment]
I have the same bug on MacOS 13.1 on a M1 processor,

**Comment by lencx** [comment]
I reproduced the problem and if there is already a chat log it fails. If a new one is created everything is fine. This is because the scenario of opening an existing record was not considered before, this will be fixed in the next version.

**Comment by lencx** [comment]
Please try v0.8.1
