### ISSUE TITLE
[Feature] Black mode.

### ISSUE THREAD

**Issue by ANONYMOUSEJR** [lencx/ChatGPT#186]
### Feature description

Basically adding an extra option that allows the user to make the background fully black.

### Motivation

Use of the program late at night where lighter tones mess with night vision and sleep.

### Alternatives

Perhaps this feature is already somehow implemented in the inject script feature though i am ignorant as to how that works or how to use it.

### Additional context

Maybe similar to how reddit has a light, dark and black mode (o-led for mobile devices).

**Comment by lencx** [comment]
I don't understand what you mean, doesn't the site have a dark mode?

<img width="401" alt="dark mode" src="https://user-images.githubusercontent.com/16164244/211709487-05b9e57e-c417-4f41-9669-95b872ca1815.png">

**Comment by briannarenni** [comment]
They may mean more like this (which is actually the Dark Reader plugin in Firefox):

<img width="1099" alt="new-screen" src="https://user-images.githubusercontent.com/69635579/211881814-5e4a5085-0688-4a78-9787-2fb105b5683b.png">

**Comment by ANONYMOUSEJR** [comment]
> They may mean more like this (which is actually the Dark Reader plugin in Firefox):
> 
> <img width="550" alt="new-screen" src="https://user-images.githubusercontent.com/69635579/211881814-5e4a5085-0688-4a78-9787-2fb105b5683b.png">
> 

Hello, yes, that was what i meant.
Sorry for not replying sooner, studying for school.
