### ISSUE TITLE
[Feature] Save data as markdown file, support secondary editing

### ISSUE THREAD

**Issue by lencx** [lencx/ChatGPT#187]
Due to the recent, and supposedly temporary removal of history, I would love to see history, per chat, synchronized/saved in unique folders named after the chat name on the tab, and all dialog accessible offline like an auto-save. Then, if ChatGPT is down like it was earlier, I could go into that local chat conversation folder **on my drive**, and retrieve any portion of that prompt/response chain. Date/Time stamping would be helpful, as well as the 1/3, 2/3, 3/3 versions of a prompt.

Losing a thread to your history is like losing everything to a neurodivergent. We have thousands of waffle-pockets interconnected by these threads. If we lose the thread, we might as well have lost the storage locker because we'll keep trying to use a key on doors that can't be opened, and all be we have a shimmer of a memory that the key opens "something", and then it become an obstacle in front of any other form of productivity we have. I have 1000 posted notes with information on them. I may not need them for days/months/years, but I know exactly where to go when I do. If the note pile is missing, it can take me weeks/months to recover. 

Having said the last part, maybe an additional way to save history in this manner could be in the cloud and as suggested above. This would be a feature I would pay for even though this project is free.

_Originally posted by @Humpmonkey in https://github.com/lencx/ChatGPT/discussions/37#discussioncomment-4651981_

**Comment by beer15** [comment]
it's a very good idea to save the data locally to avoid losing all our research, I wanted to save my data with the export options in PDF and image but I noticed that when there are several repositories the options do not work

**Comment by Manamama** [comment]
A quick FYI, even after this "purge" the new threads are being created, since 11 JAN (I timestamped this change). Before and now you can thus relogin via the browser and then save to any format or tools to your content. You can even automate it via ready (GitHub etc.) scripts etc.
