### ISSUE TITLE
[Bug] The icons on the dialog box flickers continuously when generating a response with ChatGPT

### ISSUE THREAD

**Issue by hbzhangPinka** [lencx/ChatGPT#189]
### Error message

When I'm using ChatGPT and waiting for a reply, the three buttons 'Generate PNG/Download PDF/Share Link' next to 'Stop Generating' will keep disappearing and reappearing, with the same rhythm as ChatGPT's typing rhythm in the reply.

https://user-images.githubusercontent.com/112760330/211970697-a39a2ad1-3d27-413f-9f7f-9714327f2aff.mov

### OS

MacOS 13.0 (22A380)

**Comment by hbzhangPinka** [comment]
Version 0.8.0 (20230107.052907)

**Comment by lencx** [comment]
The page structure has changed, and I'm going to make it configurable in the next release so that I don't have to release a fix version.

**Comment by lencx** [comment]
Please try v0.8.1
