### ISSUE TITLE
我升级到最新版，但我为什么找不到导出的选项了呢？

### ISSUE THREAD

**Issue by zhl111** [lencx/ChatGPT#192]
### Version

0.81

### Bug description

我没发现这个功能，原来的版本的功能取消了吗？

### OS

win11

### Environment

打扰了。。。

**Comment by lencx** [comment]
有导出 PNG 和 PDF 按钮啊，但是移除了一个分享链接的按钮，因为它可能存在安全隐患。

**Comment by lencx** [comment]
你的问题已经固定在这个 issues (#195)，我先将它关闭了，中文 issues 不利于管理。
