### ISSUE TITLE
[Feature] Ability to use proxy

### ISSUE THREAD

**Issue by Argimko** [lencx/ChatGPT#194]
### Feature description

ChatGPT block access from some countries. So could you please add an ability to set proxy connection for your app. Thank you!

### Additional context

![2023-01-13_00001](https://user-images.githubusercontent.com/3511036/212162321-cdef3379-37a0-4040-9580-473774f98c03.png)

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/574
