### ISSUE TITLE
Export button was not working

### ISSUE THREAD

**Issue by lencx** [lencx/ChatGPT#195]
It was listed that exporting the conversation was a feature, or did I read that incorrectly? If it is a feature, how do I export the conversation? Aside from copy, paste I guess. Thanks for your worrk.

_Originally posted by @rustyorb in https://github.com/lencx/ChatGPT/discussions/37#discussioncomment-4674437_

Because the page layout was updated on the official website last night, the export button was not working.

**Comment by Manamama** [comment]
Thank you @lencx for working on a fix of also this side issue so soon. 
(For a sanity check, I have just looked into my ChatGPT.log and indeed it was working fine until yesterday: 
`[2023-01-12][15:27:19][chatgpt::utils] ... open_file: [...]chatgpt-1673537239555.png)`

By the way: 
> 中文 issues 不利于管理 
- we can also handle Chinese if only to understand yous better, the grateful end-users that we are: 即使我们不会在其中说话或书写 - 人工智能的乐趣！

**Comment by Vigilence** [comment]
I used to see icons on the bottom of the responses, but as of the latest update, no longer.  This is even with new chats, after updating the software.

**Comment by lencx** [comment]
Please try v0.9.0
