### ISSUE TITLE
[Feature] Playground wrapper when chatgpt is down

### ISSUE THREAD

**Issue by tiagoefreitas** [lencx/ChatGPT#198]
### Feature description

ChatGPT is down a lot lately, so I use playground instead. Would be great to have a wrapper around that that simplifies it in the same app as ChatGPT. Could even be a custom UI using the API instead of web wrapper.

**Comment by lencx** [comment]
No alternative website has been found, and the cost of re-developing based on api is too high, so no plans will be made for the time being.

**Comment by tiagoefreitas** [comment]
So you can't just wrap the openai playground on beta.openai.com/playground?
