### ISSUE TITLE
[Feature]對話期間禁用審核檢查

### ISSUE THREAD

**Issue by ixvjlv** [lencx/ChatGPT#199]
### Feature description

https://github.com/4as/ChatGPT-DeMod
希望能在桌面板繼續使用此功能，我嘗試複製Script到Inject Script 但沒有生效，我不知道該如何做。

**Comment by lencx** [comment]
注入脚本需要一定的编程知识。在菜单栏 Help 里可以打开开发者工具，辅助你进行代码调试。
