### ISSUE TITLE
这只是单存套了个壳吧？科学上网、账号还是需要自己解决，那为何不直接用网页版呢。

### ISSUE THREAD

**Issue by aoxiang594** [lencx/ChatGPT#2]

**Comment by lencx** [comment]
解决的问题不一样，这个后期会扩展别的功能。tauri 不是简单的套壳，它可以和系统进行通信，就有很多事情可以去做。

**Comment by aoxiang594** [comment]
好吧，我不了解 Tauri,只是单纯好奇这个产品是希望能解决什么问题。目前来看似乎并没有网页更方便。方便展开讲讲您后续的构思？

**Comment by lencx** [comment]
我现在还没有一个具体的规划，如果感兴趣可以对项目保持关注。
