### ISSUE TITLE
.[Bug]

### ISSUE THREAD

**Issue by Aklesa** [lencx/ChatGPT#201]
### Version

0.8.1

### Bug description

Depuis pratiquement 2 semaines ChatGpt ne fonctionne plus du tout et j aimerai bien avoir quelques solutions pour rémidier à ce problème. Merci en avance pour vos avis

### OS

Windows 11

**Comment by Manamama** [comment]
Tell us what does work first. No need to thank in advance for something which is thus likely not to happen.
