### ISSUE TITLE
[Feature] Preventing Multiple Instances of the Program

### ISSUE THREAD

**Issue by Broccoli187** [lencx/ChatGPT#203]
### Feature description

As a user, I would like to request a **feature that prevents multiple instances of the program** from being opened at the same time. This **would help to avoid clutter in the toolbar** and make it easier to navigate the program. The function or setting should be implemented in a way that if the user tries to open another instance of the program while one is already running, it will bring the already running instance to the front instead of opening a new one.

**Comment by lencx** [comment]
Is it linux? This problem seems to be difficult to deal with, I am not familiar with linux environment.

**Comment by Broccoli187** [comment]
@lencx No, it's not Linux. It's a Windows environment and it's extremely frustrating to have multiple instances open at the same time. It clutters the toolbar and makes navigation difficult. Implementing a feature that prevents this would greatly improve the user experience.

> Is it linux? This problem seems to be difficult to deal with, I am not familiar with linux environment.

**Comment by tddschn** [comment]
Actually I'd like to see the app supporting opening up multiple windows, so that I could chat in different sessions in different windows. 

Jumping between conversations in the ChatGPT's chat history sidebar is slow and frustrating if you need to do it often, but switching between windows is fast.
