### ISSUE TITLE
[Bug] custom commands not work

### ISSUE THREAD

**Issue by beer15** [lencx/ChatGPT#207]
### Version

0.9.0

### Bug description

sometimes the custom commands don't appear, I haven't found the reason yet

My setup

![852c66495d4f4385f843e8fbc271556c](https://user-images.githubusercontent.com/50250811/212490682-1199a4f5-8506-4070-8464-e237348bfb28.png)
![22e2777d83968697975751268d188b40](https://user-images.githubusercontent.com/50250811/212490685-9f78428d-d240-410d-a179-a4baf32c0e8c.png)
![3c842776d842e1b9fc75f77f21a8ecb3](https://user-images.githubusercontent.com/50250811/212490686-fb0d0433-5b9c-4f3c-ba7a-c0c6e6a000c0.png)

### OS

windows 10 pro

**Comment by lencx** [comment]
It seems that the script injection failed due to a network problem, try refreshing the page.

**Comment by mattkbach** [comment]
Having the same problem

**Comment by Tritaya** [comment]
Same problem on windows 11

**Comment by lencx** [comment]
I reproduced the problem and I will fix it as soon as possible.

**Comment by lencx** [comment]
Please try v0.9.2

**Comment by beer15** [comment]
> Please try v0.9.2

work for the moment thanks you :)

**Comment by beer15** [comment]
I have a last question, when we click on TAB and when we mark what we want in the variable, in our text it is not possible to put a space?

**Comment by lencx** [comment]
Spaces will conflict with events that enter spaces to fill data, and are not supported at this time. All additional functionality is now implemented via script injection, which can cause many other problems if it is too complex. You can trigger a data fill by a space and then manually modify the text variable in the input box.
