### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by davidany** [lencx/ChatGPT#209]
### Feature description

hey,ty for adding the md export, i missed the html export, but understand why you removed it.
Would it be possible to name the file, whatever the history tab is called?

### Motivation

save time when saving not having to copy and paste and then rename the file

### Alternatives

if that would be too much of pain, maybe name it with date-time-seconds so easily see when it was saved to have better idea of what file is

**Comment by lencx** [comment]
It is here
<img width="900" alt="export markdown" src="https://user-images.githubusercontent.com/16164244/212520039-c293f9b3-1340-424c-9317-256e7e55c03f.png">
