### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by stamatgeorge** [lencx/ChatGPT#210]

**Comment by lencx** [comment]
Command + Q

**Comment by stamatgeorge** [comment]
Command + W & Command + Q are not the same.
I want to close the window. I don't want to Quit the app :)

**Comment by lencx** [comment]
Clicking the Close button is minimizing the program, it has no shortcut keys for now. There is more discussion of closing windows here. https://github.com/lencx/ChatGPT/discussions/205
