### ISSUE TITLE
[Bug] Export PDF & PNG unresponsive for existing chats

### ISSUE THREAD

**Issue by dairefagan** [lencx/ChatGPT#211]
### Version

v0.9.0

### Bug description

As per #185 there is no response when clicking on the export PDF or PNG buttons for an existing chat although Markdown does work great. Everything also works for new chats. Same issue, at least with export PDF, in v0.8.1.

### OS

Ubuntu 20.04.5 LTS

### Environment

Gnome 3.36.8

**Comment by lencx** [comment]
0.8.1 is a buggy version, please install 0.9.0.

**Comment by dairefagan** [comment]
This bug report is for that version, I just mentioned it was also an issue in the previous version.

> ### Version
> v0.9.0

**Comment by lencx** [comment]
v0.9.2

**Comment by lencx** [comment]
What do you mean by unresponsive?

**Comment by dairefagan** [comment]
> What do you mean by unresponsive?

When I click the buttons nothing happens.

**Comment by lencx** [comment]
Please try 0.9.2, the 0.9.0 script has problems running.

**Comment by BastianRn** [comment]
I just updated to 0.9.2 and the export problem/bug still exists. Pressing on download Pdf, export PNG, and generate markdown, opens up a windows explorer on my PC with no save button/option. Any suggestion?

**Comment by lencx** [comment]
- Check the `~/chatgpt/chatgpt.log` file
- Open the debugging tools in the help menu and check the `console` for errors

**Comment by merrickw** [comment]
I think the issue here, on Windows machines, is the path contains a mix of forward and back slashes.
Then the Open command just opens an Explorer window, but can't open the full path.

Example, from my log file I see:
`open_file: C:\Users\MXX\.chatgpt\download/pdf/fq2fbm.pdf`

I think this fails because of the forward slashes - this is my guess.

**Comment by lencx** [comment]
Please try v0.10.0
