### ISSUE TITLE
[Bug] problem with the export button

### ISSUE THREAD

**Issue by beer15** [lencx/ChatGPT#215]
### Version

0.9.2

### Bug description

when I click on an export button (MD, PNG, PDF) I only have the file explorer that opens without going into the folder, I looked where the files go and they go here: "C:\Users\NamePC\ .chatgpt" I don't know where the problem comes from

### OS

windows 10 pro

**Comment by neildmd** [comment]
Same issue here, same environment. I have to manually browse to the folder to find the exported content. We can just view them in Control Center but it would be more convenient if the folder opens automatically.

**Comment by Vigilence** [comment]
I noticed that clicking on export only opens a window to the "This PC".  However if you check "C:\Users\**UserName**\.chatgpt you will find your files there.  

The pdf displays text a vertically squashed, due to exporting as an image and not actually text.

**Comment by lencx** [comment]
![image](https://user-images.githubusercontent.com/16164244/212579468-55021405-e70b-4598-872d-05fd3b293cad.jpeg)
