### ISSUE TITLE
[Bug] Proxy support for DNS

### ISSUE THREAD

**Issue by ltaupiac** [lencx/ChatGPT#218]
### Version

V9.2

### Bug description

Auto update doesn't work behind proxy because Chatgpt client tries to resolve lencx.github.io with the local DNS resolver instead of using the proxy for DNS requests.

### OS

macos 12.6.1

**Comment by lencx** [comment]
`lencx.github.io` can be ignored, it is the application requesting update information to get the latest version of the application.
