### ISSUE TITLE
[Feature] Can you be an identified Apple Developer ? 

### ISSUE THREAD

**Issue by LukyVj** [lencx/ChatGPT#219]
### Feature description

Since this app isn't from an identified developer, I cannot install it on my computer.

**Comment by lencx** [comment]
Sorry, I don't have an Apple Developer account. You can install it through the settings. 
https://github.com/lencx/ChatGPT#developer-cannot-be-verified
<img width="715" alt="setting" src="https://user-images.githubusercontent.com/16164244/212658326-97f6c753-d070-4cb8-973c-e3be359932aa.png">
