### ISSUE TITLE
[Feature] Remove DALLE link (one that pops up every time any text is selected)

### ISSUE THREAD

**Issue by dfynest** [lencx/ChatGPT#220]
### Feature description

Remove "DALLE" link every time any text is selected

### Motivation

I believe majority is using ChatGPT for what it is and are not interested in DALLE image generation.
I've personally clicked the link by mistake several times and just find it a bit of a nuisance.

### Alternatives

Just add it to right click menu for those who need it

**Comment by lencx** [comment]
Click on the `Popup-Search` menu to enable or disable it.
<img width="206" alt="Screenshot 2023-01-16 at 18 38 03" src="https://user-images.githubusercontent.com/16164244/212658564-27d2e9ce-ebbf-45d1-8be2-a8e5e42c6c28.png">

**Comment by dfynest** [comment]
I should have used better wording - not "remove" but rather "move" to right-click menu.

From UX standpoint I'd still argue that it would be less intrusive for new users but if it works, it works!

Thank you for your answer and great project!
