### ISSUE TITLE
Save as HTML

### ISSUE THREAD

**Issue by Dave1417** [lencx/ChatGPT#221]
### Feature description

 Its better to have save button for HTML.

**Comment by Manamama** [comment]
Again: just log into your OpenAI account from browser and you will have the threads in HTML, automatically saved since 11 JAN 2023. Read the previous related (non)issues below for details.

**Comment by Manamama** [comment]
Important update from OpenAI backend itself:

> Your previously unavailable conversation history has been restored! Your previous conversations can now be viewed and continued as normal. We apologize for any inconvenience caused by the recent outage. Thank you for your patience and understanding.

I have datestamped the 11 JAN cutoff date and indeed the pre-11 JAN 2023 queries are visible now again.
