### ISSUE TITLE
[Bug] Cannot reach chat.openai.com keeps reloading "Checking if the site connection is secure"

### ISSUE THREAD

**Issue by mydoom2010** [lencx/ChatGPT#222]
### Version

0.9.2

### Bug description

Unable to login to https://chat.openai.com

keeps on reloading 
"Checking if the site connection is secure"
even after i click on verify you are human 

my ip is not blocked as i can access ChatGPT via my browser 

![Screenshot from 2023-01-18 11-14-20](https://user-images.githubusercontent.com/3280312/213093848-b4dd78c0-2b60-4e42-9310-60205cc21e42.png)

### OS

Ubuntu 22.04.1 LTS

**Comment by SyedMuradAliShah** [comment]
This is the issue from the cloudflare, because openai using it and they definitely set cloudflare to strict mode.
