### ISSUE TITLE
[Feature] Add an ad blocker

### ISSUE THREAD

**Issue by zalox** [lencx/ChatGPT#225]
### Feature description

Could you add an ad blocker like ublock origin? It would enable the user to e.g. remove the banners OpenAI puts up.

**Comment by Manamama** [comment]
Oh, are they ad banners? 
I have never seen them, also in this tool. (But then I do have Ublock in all my browsers.)

**Comment by zalox** [comment]
Sorry for being unclear. I meant those annoying "We are experiencing high traffic"-banners.

**Comment by Manamama** [comment]
Them are very useful backend error alerts. Let us leave them.

**Comment by lencx** [comment]
The banner is from the website and is not a feature of the desktop application.
