### ISSUE TITLE
Export functions (markdown, png, pdf) do not work in desktop app v0.9.2 for windows

### ISSUE THREAD

**Issue by indigoswing** [lencx/ChatGPT#228]
### Version

v0.9.2

### Bug description

When I click on either the "Export Markdown", "Generate PNG" or "Download pdf" button in the ChatGPT desktop application, it just opens a Windows Explorer window but does not create a file.

### OS

Windows 11 22H2

**Comment by lencx** [comment]
https://github.com/lencx/ChatGPT/issues/215#issuecomment-1383328069
