### ISSUE TITLE
[Bug] DALL·E 2 功能如何使用

### ISSUE THREAD

**Issue by zasl** [lencx/ChatGPT#230]
### Version

9.2

### Bug description

请问window下的WALL-E 2功能如何使用？我在中文的帮助文档中也未找到解释，希望有会使用的说明一下。

### OS

windows11

**Comment by lencx** [comment]
在菜单 `Preferences -> Pop-up Search` 中启用后，通过划词（选中的内容）来触发弹层。点击弹层后会携带划词内容打开 `DALL·E 2` 窗口进行搜索，因为填充的数据无法直接触发按钮事件，所以需要在输入框中通过输入空格来让生成按钮可点击。

**Comment by zasl** [comment]
> 在菜单 `Preferences -> Pop-up Search` 中启用后，通过划词（选中的内容）来触发弹层。点击弹层后会携带划词内容打开 `DALL·E 2` 窗口进行搜索，因为填充的数据无法直接触发按钮事件，所以需要在输入框中通过输入空格来让生成按钮可点击。

非常感谢您的回答，我按照您的方法打开了Pop-up Search功能，然后在聊天对话当中随便选词也确实出现了弹层，但是点击弹层DALL·E 2后还是没有任何变化。请我我还需要做些什么吗？

**Comment by lencx** [comment]
并无其他操作了，正常点击弹层后就会新开一个窗口

**Comment by zasl** [comment]
非常感谢，在今天已经可以正常使用了。

**Comment by FranklyCai** [comment]
请问该如何使用，我点了dall e之后没有任何反应

**Comment by cxj007sos** [comment]
> 请问该如何使用，我点了dall e之后没有任何反应

我也碰到这个问题，点击DALL*E 2之后会有一个新弹窗，但是马上就消失了。

**Comment by Ziggizag** [comment]
Same here.

On MS Windows 10, the popup window just shows for a fraction of a second and then disappears immediately :(
