### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by jcfigueiredo** [lencx/ChatGPT#232]
### Feature description

Not an issue. Just want to express my appreciation. Feel free to close this. You should also consider creating a https://www.buymeacoffee.com/ account (I'm not related to them in any way)

**Comment by lencx** [comment]
Are you referring to this account? I wrote in the readme https://www.buymeacoffee.com/lencx

**Comment by jcfigueiredo** [comment]
Yup! Sorry I missed it. ;) Enjoy the coffee. 😌

**Comment by lencx** [comment]
Thank you for your support.
