### ISSUE TITLE
[Question]Checkpoint

### ISSUE THREAD

**Issue by Golddouble** [lencx/ChatGPT#236]
### Provide a description of requested docs changes

Hello,

What Checkpoint do you use? I have read, that it costs money to get a Checkpoint. So do you pay the Checkpoint for yourself?

Would be interested in an answer. Thank you.

**Comment by lencx** [comment]
Does `Checkpoint` refer to the paid version of chatgpt? I haven't purchased it yet.

**Comment by Golddouble** [comment]
Yes, I believe so.

Why did I ask you this question?
Answer: I first tried to log in to ChatGPT via https://chat.openai.com/auth/login. However, I was told that ChatGPT was overloaded. Then I tried using your Firefox extension WebChatGPT (https://addons.mozilla.org/de/firefox/addon/web-chatgpt/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search). This way I could log in without getting the message that ChatGPT was overloaded. I would have expected to get the message both times or not at all. 

Question of interest: Why can I log in via the Firefox extension but not via https://chat.openai.com/auth/login?

According to ChatGPT it could have several reasons:

> There are a few reasons why you may be able to log in via the WebChatGPT extension while the ChatGPT website is overloaded.
> 
> One of the reasons may be that the extension is accessing the ChatGPT API through another endpoint that is less busy, while the website may have an endpoint that is more busy.
> 
> Another reason may be that the extension has a different method of managing requests that ensures requests are only sent when resources are available, while the website may not have this type of management.
> 
> It is also possible that the website and the extension are using different versions of ChatGPT and the extension is using a newer version that scales better and is less prone to congestion.
> 
> It is also possible that the website and the extension are run by different providers and the extension has a better infrastructure that is less prone to overloads.
> 

Which one is applicable to your addon?

**Comment by lencx** [comment]
As you can see from the source code, it is a self-deployed service.
https://github.com/qunash/chatgpt-advanced/blob/2ec540b27f5f969ecee062b643203c51b97716db/src/content-scripts/api.ts#L7-L26

**Comment by Golddouble** [comment]
Thank you. So it is variant " the extension is accessing the ChatGPT API through another endpoint that is less busy" ?
