### ISSUE TITLE
[Bug]ChatGPT is at capacity right now

### ISSUE THREAD

**Issue by MikiTime** [lencx/ChatGPT#239]
### Version

0.9.2

### Bug description

When I open the application it just shows me that ChatGPT is at capacity right now. But when I access it from my browser its fine

### OS

Windows 11

**Comment by lencx** [comment]
This has nothing to do with the app, which is just a wrapper around `chat.openai.com`, and it is openai that restricts access.

**Comment by hz61p1** [comment]
@lencx I observe the same problem, through the browser works fine. Perhaps they have bot detection protection

**Comment by lencx** [comment]
You can try setting up `User Agent` in the `Control Center` menu, which may be improved.

**Comment by Manamama** [comment]
Both the browser and the lencx' "wrapper" versions work fine with the Openai's server, that is resulting sometimes in the same overcapacity errors. 
Connecting from Central Europe here so your mileage may vary.

**Comment by Manamama** [comment]
FYI, [today's press](https://interestingengineering.com/innovation/chatgpt-premium-rolls-out):
```
"While [the] free version is still available, for $42/month, you will get expanded capabilities like less finicky availability, faster response speeds, and priority access to new features."

Given that the cost of running the chatbot alone, according to OpenAI, is over $100,000 per day. As per Beliūnas, this adds to more than $3 million each month, which makes the $42 monthly subscription "actually a steal."
```
