### ISSUE TITLE
/ prompts not working in Mac

### ISSUE THREAD

**Issue by rohitmewada** [lencx/ChatGPT#243]
### Version

Version 0.9.2 (20230115.103310)

### Bug description

when i type / but no prompts come up. please help

### OS

Mac

**Comment by lencx** [comment]
Please check if you have synchronized or customized the slash command, which is empty by default.

**Comment by adminha** [comment]
are you using multiple keyboards/input languages?
-----------------------------
https://chatgpttalk.com/
