### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ralKun** [lencx/ChatGPT#244]
### Version

v0.9.2

### Bug description

Email addresses of ChatGPT accounts containing a '+' character are rejected by the desktop app making it useless for such accounts. 

### OS

Macos Ventura 13.1

**Comment by lencx** [comment]
Account login is handled by openai and is not application related.

**Comment by ralKun** [comment]
Thanks for the reply! It's then hard for me to understand why I'm unable to log in thru the desktop app with my email containing a '+' character when I can log in and use ChatGPT in Google Chrome browser…

**Comment by lencx** [comment]
Please provide a screenshot of the error.

**Comment by ralKun** [comment]
I succeeded now in logging in and this issue can be closed, thank you.
p.s. I still can't use the app because of another issue: While trying to use the bot, I can get only "An error occurred. If this issue persists please contact us through our help center at help.openai.com.".

**Comment by lencx** [comment]
> I succeeded now in logging in and this issue can be closed, thank you. p.s. I still can't use the app because of another issue: While trying to use the bot, I can get only "An error occurred. If this issue persists please contact us through our help center at help.openai.com.".

This problem comes from `openai` and has nothing to do with the application, you can try refreshing the page, shortcut: `Cmd + R`

**Comment by ysun** [comment]
![image](https://user-images.githubusercontent.com/1448148/216834067-f32d8633-59e6-429f-8a93-a833f8891470.png)
I got the same issue. I can login but can not get any response but "An error occurred”
screenshot attached.
