### ISSUE TITLE
[Bug] Main window and System Tray Tab in Control Center show an empty page

### ISSUE THREAD

**Issue by zenpeaky** [lencx/ChatGPT#248]
### Version

0.10.0

### Bug description

<img width="1202" alt="SCR-20230125-h3v" src="https://user-images.githubusercontent.com/47457477/214479572-f858808a-7348-4bc1-baac-a806dc80fc96.png">
<img width="1202" alt="SCR-20230125-h3a" src="https://user-images.githubusercontent.com/47457477/214479598-e1d9c34d-d690-47ca-bc4d-f57a96fb6835.png">

### OS

MacOS Ventura

**Comment by lencx** [comment]
The data is missing a part of the validation, I will fix it in the next version, you can try to add a data in the menu `Awesome` to access it properly.
