### ISSUE TITLE
Cloudflare "Network Error"

### ISSUE THREAD

**Issue by CorruptCreeper** [lencx/ChatGPT#25]
Upon entering a question that needs to be answered in more than 60 seconds, the AI will delete its answer after 60 seconds and show "Network Error".
I believe this is caused by Cloudflare limiting response time. If you could please fix it as soon as possible, that would be greatly appreciated. As half of the users are spamming the gpt-bugs channel on Discord. 
Heres an image of the error
![image](https://user-images.githubusercontent.com/120017792/207221594-c6862df6-440c-431f-a6ce-632dd0b8ea38.png)

**Comment by lencx** [comment]
You can try to edit the user agent, it is in the menu at this location `Menu -> Preferences -> User Agent`, how to input can refer to the browser `console -> navigator.userAgent`.
![image](https://user-images.githubusercontent.com/16164244/206984921-eb6e2f5d-f721-483a-954f-0aed0d9c3116.png)

_Originally posted by @lencx in https://github.com/lencx/ChatGPT/issues/17#issuecomment-1346009072_

**Comment by CorruptCreeper** [comment]
Sorry, I'm a little dumb, how could I use this to fix the Network error?

**Comment by lencx** [comment]
You can try to paste `Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1` into the two input boxes (`Menu -> Preferences -> User Agent`), then save.

**Comment by Chimmyj390j2** [comment]
You have chatgpt open as an app on mac? I only have it on chrome

**Comment by lencx** [comment]
This is viewed in the chrome browser. Using a custom `user agent` may improve the network, but it is not absolute.

**Comment by CorruptCreeper** [comment]
Sorry, this didn't fix the issue, it also wouldn't explain why many users had experienced this with only text over 60 seconds.
![image](https://user-images.githubusercontent.com/120017792/207252598-c0739c8e-7ebe-4d13-bbfc-e2e7c9368b18.png)
One discord user suggests it may be due to Cloudflare, your bot created a solution
![image](https://user-images.githubusercontent.com/120017792/207252853-1639f201-8d63-4efb-a820-055b63058ec5.png)
https://cdn.discordapp.com/attachments/1047566093641850980/1052038262832762940/image.png

**Comment by dopperdev** [comment]
Why won't you use web sockets for the chat with the bot?

**Comment by lencx** [comment]
> Sorry, this didn't fix the issue, it also wouldn't explain why many users had experienced this with only text over 60 seconds. 

If so, it has nothing to do with the chatgpt application.

**Comment by CorruptCreeper** [comment]
Does ChatGPT use Cloudflare as its CDN?

**Comment by CorruptCreeper** [comment]
Or is there a manual limit on the amount of words that can be written. 
![image](https://user-images.githubusercontent.com/120017792/207272158-97c4138d-b9e3-494c-8d49-7a72d7d60727.png)

**Comment by CorruptCreeper** [comment]
Oh, do you have any idea how i could fix that?

**Comment by lencx** [comment]
Two days ago, the openai upgrade website added Cloudflare verification to intercept robots. I think this may be a bug generated by them, and maybe they will fix it.

**Comment by LucioMansilla** [comment]
we need to wait for the official announcement.

**Comment by CorruptCreeper** [comment]
Do you know a way i could contact them? Thank you so much for your help btw
