### ISSUE TITLE
Unacceptable TLS certificate

### ISSUE THREAD

**Issue by rzaprianov** [lencx/ChatGPT#251]
### Version

v0.1.0

### Bug description

Hi there, I try to run Chat GPT on my MX Linux 21, but after installed DEB and download AppImage - both start with error "Unacceptable TLS certificate" How to fix that?

### OS

MX Linux 21 (Debian Bulleye)

**Comment by misterstrickland** [comment]
I am having the same issue on Fedora 35 using the AppImage. Downloaded on Jan 26.

**Comment by lencx** [comment]
I am not sure where the TLS is coming from, the application is not making any proxy requests, can you provide a screenshot?

**Comment by rzaprianov** [comment]
Yes, here you are! https://i.imgur.com/GXjfHf0.jpg

**Comment by rzaprianov** [comment]
I have installed the DEB package - same issue.

**Comment by lencx** [comment]
I don't have linux, but I searched for this question, you can try. https://itsfoss.com/unacceptable-tls-certificate-error-linux/

**Comment by yixinBC** [comment]
@lencx could it be caused by the libssl version?it seems that your build script use an old Ubuntu version and libssl1.1,but the  newer Ubuntu uses libssl3.Diffrent libssl may have some difference about TLS.

**Comment by lencx** [comment]
I'm not sure, maybe the next version can be built with the latest version of linux.

**Comment by yixinBC** [comment]
I hope that could be helpful：
https://forums.raspberrypi.com/viewtopic.php?t=191867

**Comment by rzaprianov** [comment]
This was the first thing I did 

```
sudo apt-get update
sudo apt-get -y --reinstall ca-certificates
```

I have digital signature and it use any SSL certificates for sure. I have checked and I saw that I have installed libssl1.1. Is that lib the problem?

**Comment by Tortue95** [comment]
I have the same problem... I have migrated to AIPRM :disappointed:

**Comment by dangnhdev** [comment]
Same here on Opensuse, AppImage version. The console throw error:
`Unhandled Promise Rejection: SecurityError: The operation is insecure.`

Is there any workaround for this?

**Comment by DonRichards** [comment]
Same error. Comment added to https://github.com/lencx/ChatGPT/issues/694

**Comment by richardstevenhack** [comment]
Same error latest openSUSE Tumbleweed.
