### ISSUE TITLE
Set the name of exported markdown files to the chat name assigned in ChatGPT

### ISSUE THREAD

**Issue by danrfletcher** [lencx/ChatGPT#260]
### Feature description

Currently markdown files are named randomly. It would be great if they could take the name of the chat as assigned in ChatGPT.
![image](https://user-images.githubusercontent.com/57096365/214980660-67159ed2-009d-4da0-bf6d-87034a503960.png)

### Motivation

This would enable markdown files to be exported in 1 click & become immediately searchable/useable in any markdown personal knowledge management tool e.g. Obsidian or Logseq.

### Alternatives

Copy the chat name in ChatGPT, rename the markdown file & move it into my personal knowledge management folder.

**Comment by lencx** [comment]
You can view the file name in `Control Center` -> Notes and rename it by clicking on Name. The reason for using a random string as the file name is to avoid that some text content as the file name (invalid) will cause the file to fail to be saved.

**Comment by 18106574249** [comment]
if name conflict,we will change name by ourself,you just give us a prompt ,so use a random string is not needed.

**Comment by lencx** [comment]
> if name conflict,we will change name by ourself,you just give us a prompt ,so use a random string is not needed.

Naming conflicts can cause file saving failure, it needs to provide input box for user to input file name and then check if the name is legal before saving. If you want to develop this feature you need to do a lot of things in the program and it is not as simple as it seems.
