### ISSUE TITLE
[Feature] Allow users / devs the ability to use thier own OpenAI API key

### ISSUE THREAD

**Issue by shaungt1** [lencx/ChatGPT#268]
### Feature description

With the growth of ChatGPT3 it seems a probable request to allow users or developers to add their own API key to not only avoid the constraints, access, and loads of the server times of multiple queries but to access resposnes quicker for testing and usage? seems maybe an input with a checkbox as an option could allow users to add thier API key to call the request using thier credetnitals? This is just an idea to potential speed up the application?

### Motivation

It seem probale to enhance the applications and it's speed /loadtime access to resources?

### Alternatives

N/A

### Additional context

N/A

**Comment by Manamama** [comment]
?
Don't we use our (implicit) API key when we log in to the ChatGPT interface(s)?

**Comment by ysun** [comment]
> ### Feature description
> With the growth of ChatGPT3 it seems a probable request to allow users or developers to add their own API key to not only avoid the constraints, access, and loads of the server times of multiple queries but to access resposnes quicker for testing and usage? seems maybe an input with a checkbox as an option could allow users to add thier API key to call the request using thier credetnitals? This is just an idea to potential speed up the application?
> 
> ### Motivation
> It seem probale to enhance the applications and it's speed /loadtime access to resources?
> 
> ### Alternatives
> N/A
> 
> ### Additional context
> N/A

support this idea! Like some browser plugin, the app can provide a option which can swich free mode and API key mode.

**Comment by Manamama** [comment]
1. Re:
`loads of the server times of multiple queries `
It breaks OpenAI ToUs - see my old posts here in the issues with details or read at source. 

2. Or check https://github.com/acheong08/ChatGPT/ - no comments of mine re this, yet I have tried and it works.

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/553

**Comment by lencx** [comment]
Support API Key: https://github.com/lencx/nofwl
