### ISSUE TITLE
[Doc] Refresh Application

### ISSUE THREAD

**Issue by truedeity** [lencx/ChatGPT#279]
### Version

v0.1.0

### Bug description

After awhile ChatGPT crashes, I don't think that has anything to do with this tool.  But what I usually do in this case is just exit the application and reopen it to restore ChatGPT functionality.  I wonder if there is a way to just have a refresh button that will restore ChatGPT functionality without having to close the app.

### OS

Windows 11

**Comment by lencx** [comment]
`Ctrl + R`
