### ISSUE TITLE
Feature request: proxy support

### ISSUE THREAD

**Issue by naosense** [lencx/ChatGPT#28]
For some countries like China, OpenAI's services are not available, so people in these countries can use it in the browser with a vpn, but ChatGBT is not aware of this. Is it possible to set or get proxy from browser?

**Comment by lencx** [comment]
This seems difficult to implement because tauri is underlying a call to the system webview and does not support browser plugins (or maybe I don't know enough about tauri at the moment).
Maybe using a mirror site is also a solution https://github.com/lencx/ChatGPT/issues/14.

**Comment by naosense** [comment]
Ok, I'll try mirror url. One more question, where to find a valid mirror url? Have not found documentation about it.

**Comment by lencx** [comment]
I also came across it by chance, and if a similar site appears again, I will maintain a list.

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/574

**Comment by wangzhongshun** [comment]
Please replace the node： https://w1.v2free.top/auth/register?code=BVa3
