### ISSUE TITLE
Keybnoard not working [Bug]

### ISSUE THREAD

**Issue by ThePandaKing94** [lencx/ChatGPT#283]
### Version

0.10.1

### Bug description

Like in title, Keybnoard not working? Works on PC otherwise, just not chatGPT code

### OS

Windows 10 wls ubunutu 20.04

**Comment by lencx** [comment]
Can you describe it in detail? Or can you provide a recorded screen.

**Comment by yixinBC** [comment]
> Windows 10 wls ubunutu 20.04

Do you mean the **Windows Subsystem for Linux**?What's your wsl version(wsl1 or wsl2)?Which graphical desktop environment(gnome,xfce,kde...) are you using?How did you connect to this graphical environment(VNC,rdp,Xserver...)?
