### ISSUE TITLE
GUI bug, rendering app unusable

### ISSUE THREAD

**Issue by accedie-xcd** [lencx/ChatGPT#284]
### Version

0.10.1

### Bug description

![ChatGPT-GUI-Bug](https://user-images.githubusercontent.com/120650529/215501631-64ee5b68-51f8-4ea3-9bba-8f3dc91182c8.png)

[ChatGPT.log](https://github.com/lencx/ChatGPT/files/10536566/ChatGPT.log)

I believe it happened after attempting to uninstall and reinstall the application.
Persisted through an attempt to use an older version (0.10.0)

### OS

Windows 10

### Environment

Possibly related, extremely bad internet for a while.

**Comment by yixinBC** [comment]
> Possibly related, extremely bad internet for a while.
I think that's the reason.This app is just a wrapper to the openai website.And your shortcut shows that the CSS file is broken,which always caused by the bad Internet.Refresh this page may be helpful.

**Comment by accedie-xcd** [comment]
> From the screenshot it looks like the page style is not loaded, you can try to refresh it, shortcut key: `Ctrl + R`.

Attempted, but unfortunately unfixed

**Comment by lencx** [comment]
You can try opening the console `Help -> Toggle Developer Tools` to see if there are errors in the request.

**Comment by accedie-xcd** [comment]
Here are the errors in the console:
![devtools](https://user-images.githubusercontent.com/120650529/215628403-2a0f336e-f9f6-44fa-b93a-c415b037d829.png)

**Comment by uhlhosting** [comment]
I got the same issue.

**Comment by atsepkov** [comment]
I'm seeing the same issue as of yesterday. The text does say Jan 30 version, so I'm guessing a broken version of the app was pushed yesterday. Ctrl+R doesn't fix the issue, Dev Tools console shows the following errors:
```
webpack-8e3487599c1f026f.js:1 Uncaught SyntaxError: Unexpected token '<'
framework-7a789ee31d2a7534.js:1 Uncaught SyntaxError: Unexpected token '<'
main-149b337e061b4d04.js:1 Uncaught SyntaxError: Unexpected token '<'
_app-cca043450d0dc72f.js:1 Uncaught SyntaxError: Unexpected token '<'
```

**Comment by accedie-xcd** [comment]
My app seems to be working now, so I'll share what happened, however keep in mind that I do not understand the implications of my actions, and I was unable to recreate the problem.

Problem:
![devtools](https://user-images.githubusercontent.com/120650529/216004919-8701571f-1543-4e7d-aad7-a424b4021cda.png)
![sources](https://user-images.githubusercontent.com/120650529/216005002-20069e2d-f0cf-4b55-932d-57bacd30f226.png)
They are present now, but the four files under 'sources' which correspond to the errors in 'console' were missing.

Actions I have taken:

I did two thing semi-simultaneously, so i'm not very sure which fixed the problem.

First action:
installed chatGPT with winget.
    winget install --id=lencx.ChatGPT -e
    
I received a message: Found an existing package already installed. Trying to upgrade the installed package...
No applicable upgrade found.

Second action:
![Elements2](https://user-images.githubusercontent.com/120650529/216007101-b23eba6c-58f6-45e8-a18e-400342990cd3.png)
Go to the elements tab, expand the <head> tag, then for all the files that correspond to the errors in 'sources' select them, click the '...' button on the left, and delete element.
Restart the app.


Once again, I don't really know what I did, but I hope this will be helpful.

**Comment by lencx** [comment]
> Here are the errors in the console: ![devtools](https://user-images.githubusercontent.com/120650529/215628403-2a0f336e-f9f6-44fa-b93a-c415b037d829.png)

I found the cause of the problem, but I haven't found a solution yet. https://github.com/tauri-apps/tauri/issues/6168#issuecomment-1411820198

**Comment by lencx** [comment]
I found the cause of the problem, it is a cache problem, clear the tauri browser cache can be. I'm not sure where the windows cache file is.

macOS: `~/Library/Caches/com.lencx.chatgpt`

**Comment by yixinBC** [comment]
> I found the cause of the problem, it is a cache problem, clear the tauri browser cache can be. I'm not sure where the windows cache file is.
> 
> macOS: `~/Library/Caches/com.lencx.chatgpt`

I searched the directory name on my Windows,and found it's in `~\AppData\Local\com.lencx.chatgpt`

**Comment by lencx** [comment]
It may have two files (ignore if it doesn't), best to clean them both, I'm not sure which one is wrong.

macOS:
- `~/Library/Caches/com.lencx.chatgpt`
- `~/Library/Caches/ChatGPT`

Windows:
- `~\AppData\Local\com.lencx.chatgpt`
- `~\AppData\Local\ChatGPT`

**Comment by atsepkov** [comment]
FYI, there is an easier way to clear cache, go to Chrome Developer Tools, Application tab, Storage section (3rd item on the list) and click "Clear site data", ctrl/option+R to refresh the page (depending if you're on MacOS or not) and page should start working again.
