### ISSUE TITLE
[Bug] Does Not close even with tray turned off

### ISSUE THREAD

**Issue by InfinteSial** [lencx/ChatGPT#298]
### Version

newest

### Bug description

When closing the application the window closes but you can see its still open from your taskbar as the dot is still under it, i have turned off system tray and it still is the same. closing from the quit from the first tab in the menu works

### OS

Windows 11 Pro 64 bit

**Comment by lencx** [comment]
The tray is created automatically when the application is started, it cannot be closed and you have to exit the application.
You can show or hide it by clicking on it, or you can disable it by `Preferences -> System Tray`.

**Comment by yixinBC** [comment]
> The tray is created automatically when the application is started, it cannot be closed and you have to exit the application. You can show or hide it by clicking on it, or you can disable it by `Preferences -> System Tray`.

It seems that we should improve our documentation for more clear user guide.
