### ISSUE TITLE
经常报错

### ISSUE THREAD

**Issue by zhl111** [lencx/ChatGPT#30]
通常说到一半时就出现这个问题，try again后又可以了。这是我网络的问题吗？

![image](https://user-images.githubusercontent.com/29135984/207540338-aec4c6ea-d5c7-4846-aea1-00c509c6a9fe.png)

**Comment by ex998** [comment]
这个问题太频繁出现了，需要高手解决

**Comment by lencx** [comment]
这是 OpenAI 为了拦截机器人，加了一层安全验证，之后就开始频繁报错了。没什么好办法，等官方 fix 吧。

**Comment by lencx** [comment]
或者可以考虑搞个界面，用户用自己的 key 玩？
