### ISSUE TITLE
[Feature]Enable set proxy

### ISSUE THREAD

**Issue by ssyzyg** [lencx/ChatGPT#303]
### Feature description

How can I set proxy for accessing chatGPT? I get "access denied" message. 

### Additional context

This is the error message
![WeCom Screenshot_20230203162914](https://user-images.githubusercontent.com/678857/216550171-82001761-f568-4654-afa1-5ab138f370fa.png)

Access denied
You do not have access to chat.openai.com.
The site owner may have set restrictions that prevent you from accessing the site.

**Comment by yixinBC** [comment]
As I have commented:https://github.com/lencx/ChatGPT/issues/280#issuecomment-1410377081,
But set the system-level proxy may help you to solve the problem.

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/574
