### ISSUE TITLE
thread 'main' panicked at 'Failed to load ayatana-appindicator3 or appindicator3 dynamic library

### ISSUE THREAD

**Issue by overtube** [lencx/ChatGPT#305]
### Version

v0.10.3

### Bug description

here a **RUST_BACKTRACE** **:** 

> thread 'main' panicked at 'Failed to load ayatana-appindicator3 or appindicator3 dynamic library
> libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
> libappindicator3.so.1: cannot open shared object file: No such file or directory
> libayatana-appindicator3.so: cannot open shared object file: No such file or directory
> libappindicator3.so: cannot open shared object file: No such file or directory', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libappindicator-sys-0.7.3/src/lib.rs:41:5

### OS

archlinux

**Comment by yixinBC** [comment]
Have you tried our [AppImage release](https://github.com/lencx/ChatGPT/releases/download/v0.10.3/chat-gpt_0.10.3_amd64.AppImage)?
It seems your OS are missing some dependencies,maybe you can install them using your package manager.

**Comment by yixinBC** [comment]
on https://aur.archlinux.org/packages/chatgpt-desktop-bin ,there's a comment that has the same issue,hope it could be helpful.

**Comment by overtube** [comment]
> Have you tried our [AppImage release](https://github.com/lencx/ChatGPT/releases/download/v0.10.3/chat-gpt_0.10.3_amd64.AppImage)? It seems your OS are missing some dependencies,maybe you can install them using your package manager.

Offcource and it not work too

**Comment by yixinBC** [comment]
`ayatana-appindicator3` or `appindicator3` dynamic library is required by [tauri](https://github.com/tauri-apps/tauri)'s GUI library [TAO](https://github.com/tauri-apps/tao) to enable system tray and more menu item variants on Linux,so you might install them to your computer by yourself.

**Comment by yixinBC** [comment]
```
sudo pacman -S libappindicator-gtk3
```

**Comment by overtube** [comment]
Great, all work, thank
