### ISSUE TITLE
[Security] - do not use or install this app - it may be trying to access your login details when oAUTh window presented

### ISSUE THREAD

**Issue by BlockchainPunks** [lencx/ChatGPT#306]
### Description

i installed app
then clicked login
it showed oauth to google and microsoft directly in webview inside app - this is insecure and can be used by hackers.

**Comment by Manamama** [comment]
If "hackers" can see your: 

> in webview inside app - this is insecure and can be used by hackers

then your box is compromised anyway. 

Or I do not understand something basic about ItSec and your description.

**Comment by yixinBC** [comment]
As mentioned in README: https://github.com/lencx/ChatGPT#is-it-safe
:)

**Comment by Manamama** [comment]
OK guys and gals: let us close it faster than usual, as it is a gross misunderstanding, even assuming no RTFM on the part of the original poster.
