### ISSUE TITLE
[Feature] Add ability to export complete chat history from all previous chat threads at once

### ISSUE THREAD

**Issue by eshack94** [lencx/ChatGPT#311]
### Feature description

Currently, one is required to export chat history one thread at a time. It's a great feature, but it would be useful if there was a feature that automated this (exposed via UI button), to export all of my chat history (including all previous conversations) at one time.

Ideally, a user would be able to click an "Export All" button, or perhaps it could be exposed via a setting in the Control Center.

Or maybe it would allow more granular export support to export only specific chat conversations from a specific time range (for example, one might be able to export all chats that took place withi

### Motivation

To save time, so one doesn't have to manually go through every single old conversation one at a time in order to export them.

This could be especially useful for programmers and other technical-minded people who use ChatGPT as a way to learn new concepts and skills. I imagine using this feature to quickly save all chats so that I can further refine them into learning notes for myself.

**Comment by Manamama** [comment]
IMHO, it is not needed, as you just log into your OpenAI ChatGPT account in a browser and there you have (after plugging one of the numerous ChatGPT enhancement Github projects), a sample one: 
![Screenshot from 2023-02-06 15-21-58](https://user-images.githubusercontent.com/78492008/216996749-34032e18-a783-4e3e-b759-7cae2e0c6369.png)

We could add it into the FAQ, in fact.

**Comment by eshack94** [comment]
@Manamama That would be great (adding it to the FAQ). I wasn't aware of such plugins. Could you let me know the name of the one(s) you are using in the screenshot you linked?

**Comment by Manamama** [comment]
I am not able to add anything to code or FAQ directly: just suggesting, as you. 
The actual extension is this one (yet there are many other ones): 
Superpower ChatGPT, [https://chrome.google.com/webstore/detail/superpower-chatgpt/amhmeenmapldpjdedekalnfifgnpfnkc](https://chrome.google.com/webstore/detail/superpower-chatgpt/amhmeenmapldpjdedekalnfifgnpfnkc)
