### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bxkdstar123** [lencx/ChatGPT#318]
### Version

chatgpt3.5

### Bug description

An error occurred. If this issue persists please contact us through our help center at help.openai.com.

### OS

windows

**Comment by lencx** [comment]
This problem is not application related, it is an openai problem.

**Comment by bxkdstar123** [comment]
When can this be fixed ?

**Comment by yixinBC** [comment]
> When can this be fixed ?

We can't fix it,you should ask this question to openai.This project is **just** a wrapper to ChatGPT website with some useful extensions.
:(

**Comment by bxkdstar123** [comment]
Ok, thanks

**Comment by lencx** [comment]
You can view it using the translator https://github.com/lencx/ChatGPT/discussions/133
