### ISSUE TITLE
[Bug]Mac顶部控制栏上点击icon，小窗出现在错误的屏幕上

### ISSUE THREAD

**Issue by hbzhangPinka** [lencx/ChatGPT#320]
### Version

Version 0.10.3 (20230203.063511)

### Bug description

我有两块屏幕，上下排布
当我点击下面屏幕顶部菜单栏的icon时，弹出的菜单出现在了上面屏幕的右下角，且部分UI超出屏幕
上方屏幕：
![Screen Shot 2023-02-06 at 14 01 38 (2)](https://user-images.githubusercontent.com/112760330/216895968-f5eeec14-0d04-47f7-aaf0-783898496a4d.png)

下方屏幕控制栏：
<img width="137" alt="Screen Shot 2023-02-06 at 14 02 37" src="https://user-images.githubusercontent.com/112760330/216895988-7397cd21-cac0-44a2-bead-b828b54d03c0.png">

### OS

MacOS 12.6.2 (21G320)

**Comment by lencx** [comment]
扩展屏幕如果通过上下滑入，自动计算位置会出问题，建议尝试修改成左右滑入尝试。

**Comment by hbzhangPinka** [comment]
> 扩展屏幕如果通过上下滑入，自动计算位置会出问题，建议尝试修改成左右滑入尝试。

所以这个问题在上下的多屏上暂时无解吗？
不是个很大的问题，不过我的工作环境就是上下分屏🤣

**Comment by lencx** [comment]
暂时无解，这个是用自动计算的，如果自己计算会更麻烦，而且扩展屏幕如何计算我也不清楚。

**Comment by hbzhangPinka** [comment]
> 暂时无解，这个是用自动计算的，如果自己计算会更麻烦，而且扩展屏幕如何计算我也不清楚。

get, 辛苦
