### ISSUE TITLE
[Bug]App does not close when clicking the close button. Arch Linux

### ISSUE THREAD

**Issue by ZeroDot1** [lencx/ChatGPT#326]
### Version

0.10.3

### Bug description

App does not close when clicking the close button.
The app is minimized instead of being closed.
![Bildschirmfoto vom 2023-02-06 19-51-14](https://user-images.githubusercontent.com/28985171/217059677-4cdd247a-62f1-4394-8b13-cfd91cad3630.png)

### OS

Arch Linux: 6.1.9-arch1-2

**Comment by daffywen** [comment]
also Windows11 🤯

**Comment by lencx** [comment]
Please use the shortcut `Ctrl + Q` or Quit in the menu to close the application, it is disabled to avoid users from touching it by mistake.

**Comment by reorx** [comment]
Clicking the ❎ button to close the window rather than quitting the app is a standard convention on MacOS, so I don't see this as a problem.

On Linux/Windows, if the "system tray" option is enabled, it is also a legit behavior to not quite the app when clicking the close button.
