### ISSUE TITLE
[Bug]This installation package could not be opened, Contact the application vendor to verify that this is a valid Windows Installer package,

### ISSUE THREAD

**Issue by bigplayer-ai** [lencx/ChatGPT#327]
### Version

any version

### Bug description

When I try to install your program on windwos 11 22h2 i receive this error:
This installation package could not be opened, Contact the application vendor to verify that this is a valid Windows Installer package,

### OS

windows 11 22h2

**Comment by DemGiran** [comment]
same, did u solve it?

**Comment by lencx** [comment]
Make sure you have administrative permissions. https://softwarekeep.com/help-center/there-is-a-problem-with-this-windows-installer-package

**Comment by navyfighter12** [comment]
> Make sure you have administrative permissions. https://softwarekeep.com/help-center/there-is-a-problem-with-this-windows-installer-package

why does the install need admin rights?
