### ISSUE TITLE
[Bug]mac 12.6.3 打开control center会卡死，只能重启。

### ISSUE THREAD

**Issue by b0pro** [lencx/ChatGPT#328]
### Version

V.10.3

### Bug description

mac 12.6.3 打开control center会卡死，只能重启,不知道是我系统原因还是bug，帮忙看下，谢谢
测试了下，如果非全屏模式是正常的，全屏模式会卡死

### OS

mac 12.6.3

**Comment by Dreamer-Paul** [comment]
是托盘图标还是系统右侧的控制中心？

**Comment by lencx** [comment]
我这边是正常的
