### ISSUE TITLE
Auto to update not work

### ISSUE THREAD

**Issue by cnscorpions** [lencx/ChatGPT#329]
### Version

v0.9.2

### Bug description

Auto-update prompt appears at app start but doesn't work after clicking 'yes'. Is there a solution? Thanks.

自动更新一直不成功，是网络的原因吗? 挂的全局梯子，也是一样... 

### OS

Win10 Pro

**Comment by lencx** [comment]
It needs to request installer resources in github, which is blocked in China, and you need to update it through the global (system) proxy.

**Comment by lencx** [comment]
This issue will be closed, if you still have problems, please reopen it.
