### ISSUE TITLE
[RPM version] We need an RPM version for Linux

### ISSUE THREAD

**Issue by mysticaltech** [lencx/ChatGPT#337]
### Feature description

It would be great to have RPM packages.

### Motivation

Half of Linux users are on distros that work with RPMs like OpenSUSE and RedHat, and Fedora (with Linus Torvalds himself uses).

### Alternatives

AppImage is not practical, it's cumbersome to launch and use and does not work with package managers so not easy to update upon new releases, it requires manual work

**Comment by yixinBC** [comment]
As answered in FAQ:https://app.nofwl.com/chatgpt/faq#why-does-this-program-not-support-xxx-architectureeg-mac-arm-archxxx-packagingeg-flatpack
We don't know much about the packaging of Linux,can you help us improve it?

**Comment by mysticaltech** [comment]
Ok, thanks! For the moment I do not have the time. But maybe someone else will be able to do so in the future.

Between, I tried converting the .deb to .rpm with `alien`, this worked, but the installation failed.
