### ISSUE TITLE
[Bug]-macos run error

### ISSUE THREAD

**Issue by brianzhang** [lencx/ChatGPT#339]
### Version

0.10.3

### Bug description

<img width="260" alt="image" src="https://user-images.githubusercontent.com/766999/217466547-ec52c189-9702-44be-bad6-90110e14371e.png">

### OS

macbook pro Ventura 13.0.1

**Comment by yixinBC** [comment]
https://app.nofwl.com/chatgpt/faq#developer-cannot-be-verified
