### ISSUE TITLE
依赖部分不完整

### ISSUE THREAD

**Issue by KevinYouu** [lencx/ChatGPT#34]
源代码引用了@ant-design/icons的图标，但是package.json没有此依赖，会导致无法运行，安装图标库后可以解决这个问题
<img width="723" alt="截屏2022-12-15 21 09 29" src="https://user-images.githubusercontent.com/46970005/207867231-9110c520-424c-4705-bd2e-212552ab2cdd.png">

**Comment by lencx** [comment]
你是本地在跑项目吗？我这边因为直接导入是 ok 的，就没有加入依赖，而且打包后也未出现问题，后面可以加一下依赖。
