### ISSUE TITLE
[Bug]窗口宽度小于750像素时，底部消息框的 发送按钮 被 Export Markdown按钮 遮挡

### ISSUE THREAD

**Issue by acccccccb** [lencx/ChatGPT#340]
### Version

v0.10.3

### Bug description

窗口宽度小于750像素时，底部消息框的 发送按钮 被 Export Markdown按钮 遮挡。

### OS

windows

**Comment by lencx** [comment]
我并没有复现该问题，你可以尝试清除应用缓存数据：
`C:\Users\<username>\AppData\Local\com.lencx.chatgpt`
