### ISSUE TITLE
[Feature] start chatgpt as minimized to system tray application.

### ISSUE THREAD

**Issue by bigplayer-ai** [lencx/ChatGPT#345]
### Feature description

Hey,
I want to start chatgpt minimized to system tray application so I can toggle it when i need to after system startup.

### Motivation

Hey,
I want to start chatgpt minimized to system tray application so I can toggle it when i need to after system startup.

### Alternatives

RBTRAY

### Additional context

Hey,
I want to start chatgpt minimized to system tray application so I can toggle it when i need to after system startup.

**Comment by Manamama** [comment]
Ctrl+F:
https://github.com/lencx/ChatGPT/issues?q=is%3Aissue+minimize+
and you will find the deja vu:
https://github.com/lencx/ChatGPT/issues/131

**Comment by bigplayer-ai** [comment]
Duplicate #131
