### ISSUE TITLE
Increase application-specific proxy settings, such as support for HTTP or SOCKS5 proxy.

### ISSUE THREAD

**Issue by blueicesir** [lencx/ChatGPT#346]
### Feature description

In mainland China, it is not possible to access openai's API without setting up a system proxy. Is it possible to add an independent proxy setting in the application instead of using a global proxy or PAC script configuration? Thank you!

**Comment by Will2top** [comment]
expecting too

**Comment by Jovines** [comment]
Also looking forward

**Comment by Ethkuil** [comment]
I think it's not so urgent because "append one line in PAC script" is not likely to be harder than "edit the proxy setting of this application". (It's for me. And if there are any entirely different situations I apologize. )

However, add such a feature may be much more tiring.

**Comment by ljhmily** [comment]
is the next version support proxy？

**Comment by ttimasdf** [comment]
https://github.com/lencx/ChatGPT/issues/280#issuecomment-1410377081

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/574
