### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mohdroslin** [lencx/ChatGPT#349]
### Version

0.10.3

### Bug description

app can't close. when i need to close i have to end task. 

### OS

windows 22H2

**Comment by lencx** [comment]
Currently 600k+ downloads of the installer and not seeing a lot of feedback, so I don't think it's a bad design. I can provide a configuration to choose how to close it, but minimizing will still be the default. I've also received feedback that I don't want to exit the app (whether the user is drunk or not is not something we need to discuss, I'd like to try and ask why you would choose to install the app when you already have a website), the use of the product would have modified some of the user's default habits, and if you think the software is seriously affecting your experience, I respect that you can leave it at any time.

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/359

**Comment by mrpeardotnet** [comment]
Still there is no option to close the app on X?
