### ISSUE TITLE
Hide Dock Icon + Main Window

### ISSUE THREAD

**Issue by PascalPixel** [lencx/ChatGPT#35]
Love the menubar dropdown, it's excellent! Can we get rid of the dock icon and main window altogether? 😄 It currently just 'hides' the main window when you click 'close'.

<img width="120" alt="Screenshot 2022-12-15 at 15 20 21" src="https://user-images.githubusercontent.com/3094044/207898570-bc499efa-e1fa-4860-870f-84b6b14655c2.png">

<img width="504" alt="Screenshot 2022-12-15 at 15 19 55" src="https://user-images.githubusercontent.com/3094044/207898459-6b88a48e-829f-4878-9e84-3dd1d341532f.png">

**Comment by lencx** [comment]
This is possible, but once implemented, both `dock` and `menu` will disappear (shortcuts will still be available, but without menus as hints, it will be difficult for users to remember them). If the menu is placed on the system tray, they would be stacked on top of each other, it will affect the user experience. I haven't thought of a good form of interaction yet.

<img width="436" alt="tray-menu" src="https://user-images.githubusercontent.com/16164244/207916954-8783c250-ea20-4c81-abb7-03c84e4e3a78.png">

**Comment by lencx** [comment]
I came up with a better form of interaction.
- If the app is still in the dock there are two ways to hide it:
   - Triggered by the menu item `Menu -> Preferences -> Hide Dock Icon`
   - triggered by a right-click event on the system tray icon
- When it needs to be in the dock there is only one way: it can only be restored by a right-click event on the system tray icon

Simply put, a right-click on the system tray icon is a two-way event (`show ⇋ hide`)

![chat-hide-dock](https://user-images.githubusercontent.com/16164244/208014889-c29b174b-4146-40ad-99b0-0ef7e2dd025a.gif)

**Comment by PascalPixel** [comment]
This is great! Some other macOS menubar apps I have that have the option to 'disable the dock icon and app switcher', seem to follow the pattern of:
- are you sure you want this mode? restart is required (ok)
- menu item left-click to toggle window
- menu item right-click to get app menu

**Comment by lencx** [comment]
If a system tray right-click menu is required, it would be a simple version of:
- Control Center
- Show Dock icon
- Exit

`Control Center` is important and I am implementing exciting features for it.

**Comment by PascalPixel** [comment]
Thanks @lencx !

**Comment by lencx** [comment]
You can check out readme, which also adds more exciting features, but was released in a bit of a hurry and is not yet fully adapted in the system tray.
