### ISSUE TITLE
ChatGPT pronounces word "nothing" wrong.

### ISSUE THREAD

**Issue by GamerTronky** [lencx/ChatGPT#355]
### Version

v0.10.3

### Bug description

I somehow get ChatGPT say "It's worth noting that..."

There's image that proves the bug.
![image](https://user-images.githubusercontent.com/110632033/218093028-5217ee40-3528-4897-b083-08ccf17793f0.png)

### OS

Windows 10

**Comment by MSandro** [comment]
This application is not responsible for the AI's responses and spellings. The application simply calls the ChatGPT website. You should report the issue there, not here.
