### ISSUE TITLE
Can't close ChatGPT from taskbar.

### ISSUE THREAD

**Issue by GamerTronky** [lencx/ChatGPT#356]
### Version

v10.3

### Bug description

I just can't close ChatGPT window from  taskbar (right click on icon and selecting "Close window"). I have to go to 

hidden icons menu  ![image](https://user-images.githubusercontent.com/110632033/218093726-877209f9-9598-4863-bfc7-4db9332dadbc.png) that it is in taskbar and right click on ChatGPT icon and select "Quit ChatGPT".

### OS

Windows 10

**Comment by GamerTronky** [comment]
@lencx But still that is a bug, and needs to be fixed, no matter the shortcuts.

**Comment by lencx** [comment]
> @lencx But still that is a bug, and needs to be fixed, no matter the shortcuts.

It's not a bug, it's a feature, and you can see why here. https://github.com/lencx/ChatGPT/issues/349#issuecomment-1423902228

**Comment by Ethkuil** [comment]
>  I have to go to hidden icons menu image that it is in taskbar and right click on ChatGPT icon and select "Quit ChatGPT".

It's a option to drag the icon outside.
