### ISSUE TITLE
[Build Error] run chat-gpt command error

### ISSUE THREAD

**Issue by Tabbleman** [lencx/ChatGPT#357]
### Error message

```
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by chat-gpt)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by chat-gpt)
```

### OS

Ubuntu 18.04

### Environment

i've download glibc2.29 on my computer
![image](https://user-images.githubusercontent.com/89694978/218101594-39f25b48-9f01-4876-bfe7-f0ac8883941f.png)
but still got error above(or below?im not sure where the error message's location),shall i add a soft link between /lib/x86_64-linux-gnu/libc.so.6 and /opt/glibc2.29/lib/libglibc/libc.so.6? caz i got a warnning when i build glibc2.29:
```
*** On GNU/Linux systems the GNU C Library should not be installed into
*** /usr/local since this might make your system totally unusable.
*** We strongly advise to use a different prefix.  For details read the FAQ.
*** If you really mean to do this, run configure again using the extra
*** parameter `--disable-sanity-checks'.

```

**Comment by yixinBC** [comment]
At any time, it is unwise to change the libc version of the Linux system by yourself, unless you  know **exactly** what this means and can handle the extensive link errors of executable files caused by it.
Other solusions include updating your Ubuntu version or build this app by yourself(my have other problems).

**Comment by Tabbleman** [comment]
> At any time, it is unwise to change the libc version of any GNU/Linux-based OS by yourself, unless you know **exactly** what this means and can handle the extensive link errors of executable files caused by it. Other solusions include updating your Ubuntu version or build this app by yourself(may have other problems).

thanks for your reply, i'm gonna try to build this app by my self...wish me good luck
