### ISSUE TITLE
The v0.10.3 can't sync prompts on the m1 macbook pro[Bug]

### ISSUE THREAD

**Issue by Levin000** [lencx/ChatGPT#362]
### Version

v0.10.0

### Bug description

Upon pressing the sync prompts button, the prompts remain pending and are unable to synchronize. Browsing the internet with ClashX global proxy enables normal access and utilization of ChatGPT. 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/23720899/218237045-63ff920f-ef90-4157-b9fb-8a35c1c233f9.png">

### OS

macOS Ventura 13.2

**Comment by lencx** [comment]
The proxy needs to be at the global (system) level. Make sure that you can proxy to all applications.

You can check if your proxy is successful by entering the following command in the terminal:

```bash
curl https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv
```

**Comment by Levin000** [comment]
> 

Thank you, it indeed cannot be accessed. My proxy is as follows, could you give me some suggestions?
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/23720899/218238634-441a7fac-53fd-4793-85af-b295a2092d93.png">

**Comment by Levin000** [comment]
Thank you. After the configuration is carried out, I can connect to a file using curl in the terminal. But how do I need to configure the chatgpt desktop application to sync prompts?
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/23720899/218239774-7606be97-dfba-433d-9007-aca3e09adef7.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/23720899/218239785-c5b283e9-2ec8-4dad-896c-ea88f4c5ea65.png">

**Comment by lencx** [comment]
https://github.com/lencx/ChatGPT/discussions/133#discussioncomment-4580724

**Comment by Levin000** [comment]
> 

Thank you, but this is ineffective for me. However, I resolved the issue through the following steps, serving as a reference for those who come after me.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/23720899/218393987-55ae0bf4-0793-44a6-bacc-8e2b37d38fb5.png">
