### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SupernovaCooper** [lencx/ChatGPT#363]
### Version

0.10.3

### Bug description

感谢大佬的作品。

遇到一个bug，点击主窗口的关闭按钮，主窗口是隐藏了，但是主窗口的任务栏（不是托盘区图标）却依然存在，依然霸占任务栏。
关闭主窗口是为了让他后台运行，因为已经有托盘图标了，通过托盘图标可以再次打开主窗口，要是任务栏关不掉，那托盘图标也就没意义了吧。所以这应该是个bug吧？其他类似的issue应该说的都是这个情况吧，可能他们没描述清楚？

望大佬改进一下。。它隐藏到托盘区方便之处就是可以随时点击打开用，不需要再次登录之类的，可是目前它一直待在任务栏上，太别扭了。

哦对了，因为我的任务栏是类似XP样式的，所有前台窗口都会在任务栏显示一个“窗口的标题”，不知道大佬是不是没测试过这种情况。

呃，之前没试过托盘图标，光注意任务栏了。。点了一下托盘图标，发现搞不懂交互逻辑。。怎么又出来一个单独的窗口，还需要登录啥的，就像是又开了一个实例。。。。同时，任务栏变成了两个“窗口的标题”。。。。

### OS

WindowsServer2012

**Comment by lencx** [comment]
这个 bug 早就存在，无法修复（牵扯的原因过于复杂）
