### ISSUE TITLE
[Bug] When I use the built-in Chinese input method on my Mac to type English words, it immediately sends when I press "Enter". 

### ISSUE THREAD

**Issue by cyhhao** [lencx/ChatGPT#369]
### Version

0.10.3

### Bug description

When I use the built-in Chinese input method on my Mac to type English words, it immediately sends when I press "Enter". 
But the Chat GPT web version doesn't immediately send.

我用Mac自带的中文输入法打英文字母，按回车直接发送出去了，正常应该是直接打出英文字母，不发送。输入法候选栏消失的时候按回车才会发送。ChatGPT 官网 web 页面是正常的交互。这个很影响使用，因为经常打字快了中英文混合着输入。

### OS

MacOS 13.1

**Comment by weicheng59** [comment]
遇到了相同的问题，非常困扰

**Comment by bananaza** [comment]
是的，我也遇到了同样的问题。

**Comment by cyhhao** [comment]
@lencx 找到问题了

ChatGPT 官方前端正确处理了中文输入法的问题，对 keydown 的 event.isComposing==true 进行了判断，输入法状态下按 Enter 不会发送消息。

但是因为在 MacOS 上 Tauri 默认使用的是 Safari 内核，而 Safari 的 event.isComposing 始终为 false，只有通过 keyCode 来判断是否为输入法状态。

因此只要全局阻止e.keyCode==229 就可以了

我提了一个PR：https://github.com/lencx/ChatGPT/pull/389
