### ISSUE TITLE
[Feature] built in DeepL or google translate

### ISSUE THREAD

**Issue by mochacat2001** [lencx/ChatGPT#370]
### Feature description

I can hardly use English. It would be very useful if I could translate what is displayed when I do something. I would appreciate it if you could implement this feature.

**Comment by Ethkuil** [comment]
Maybe you can try just use your mother language to talk with ChatGPT. And you can simply ask it to answer in the lang you want. And by the way, the ability to translate of ChatGPT is much stronger than Google Translate for me (I haven't used DeepL but I guess it would not do better than ChatGPT).

**Comment by mochacat2001** [comment]
Thank you very much.
