### ISSUE TITLE
[Bug]无法打开

### ISSUE THREAD

**Issue by lians0** [lencx/ChatGPT#374]
### Version

v0.10.3

### Bug description

无法打开
![image](https://user-images.githubusercontent.com/30581350/218359430-89c4c958-ccd7-4cdb-ba48-42e600c5a298.png)

浏览器：edge 110.0.1587.41 

### OS

Microsoft Windows 10 专业版 10.0.19044；内部版本 19044

**Comment by lencx** [comment]
你可以搜索 `status_invalid_image_hash` 查找解决方案，它来自于你的系统环境，与应用没有太大关系。或者可以查看这个链接 [microsoft Edge Error code: STATUS_INVALID_IMAGE_HASH](https://answers.microsoft.com/en-us/microsoftedge/forum/all/microsoft-edge-error-code-statusinvalidimagehash/070556a8-8d34-4b9c-ac3e-b84846098946)

**Comment by lians0** [comment]
好吧，应该是公司安全软件的问题。多谢解答
