### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by RyanHo97** [lencx/ChatGPT#375]
### Feature description

请问作品有无语言切换功能，想用中文版本的话该如何做

### Motivation

提升中文环境用户使用体验

**Comment by lencx** [comment]
你可以在 chatgpt 里发送：`请讲中文`，它会用中文和你对话。

**Comment by RyanHo97** [comment]
作者大佬，我指的是软件UI层面中英文的切换功能，比如加个Language这种，未来有想法吗？

**Comment by lencx** [comment]
做国际化比较麻烦，需要修改大量代码，暂时没有计划
