### ISSUE TITLE
[Bug] Markdown button starts to overlap send button on certain breakpoint

### ISSUE THREAD

**Issue by alwafor** [lencx/ChatGPT#379]
### Version

0.10.3

### Bug description

The gif file shows the bug.

![Bug ChatGPT markdown button](https://user-images.githubusercontent.com/79059092/218407533-fb5283d9-7073-4469-a84a-976b72217c84.gif)

### OS

Windows 10

**Comment by lencx** [comment]
The buttons are not recalculated when the window size is changed, and you can refresh the page after changing the window.

**Comment by lencx** [comment]
I can't reproduce this problem now, you can try to clear the cached data of the application.
`C:\Users\<username>\AppData\Local\com.lencx.chatgpt`

**Comment by alwafor** [comment]
I've cleared cache and signed in again, but button still blinks.

**Comment by alwafor** [comment]
![Bug ChatGPT 2](https://user-images.githubusercontent.com/79059092/219080352-a4794c6a-1180-4b46-95f9-c64065ff9a2a.gif)

**Comment by lencx** [comment]
Are you sure it's version 0.10.3?

**Comment by alwafor** [comment]
Yes it was, but now I updated the app to 0.11.0, cleared cache and the issue has gone.
