### ISSUE TITLE
[Feature] request macos arm64 version

### ISSUE THREAD

**Issue by vangie** [lencx/ChatGPT#380]
### Feature description

request macos arm64 version

**Comment by lencx** [comment]
The next version will support the mac aarch64 installer.

**Comment by RealAidanJoe** [comment]
> The next version will support the mac aarch64 installer.

I tried aarch64 version, and it is not available. macbook m1 shows me that ‘"ChatGPT.app" is corrupted and cannot be opened. You should move it to the wastepaper basket.’

**Comment by ugandasniper** [comment]
> > The next version will support the mac aarch64 installer.
> 
> I tried aarch64 version, and it is not available. macbook m1 shows me that ‘"ChatGPT.app" is corrupted and cannot be opened. You should move it to the wastepaper basket.’

same 😢

**Comment by lencx** [comment]
> > The next version will support the mac aarch64 installer.
> 
> I tried aarch64 version, and it is not available. macbook m1 shows me that ‘"ChatGPT.app" is corrupted and cannot be opened. You should move it to the wastepaper basket.’

You can try the steps in the link. https://support.apple.com/en-sg/guide/mac-help/mh40616/mac

**Comment by RealAidanJoe** [comment]
> > > The next version will support the mac aarch64 installer.
> > 
> > 
> > I tried aarch64 version, and it is not available. macbook m1 shows me that ‘"ChatGPT.app" is corrupted and cannot be opened. You should move it to the wastepaper basket.’
> 
> You can try the steps in the link. https://support.apple.com/en-sg/guide/mac-help/mh40616/mac

I tried the steps you send and it cannot fix that problem. when I followed these steps, there no the Open Anyway button in Privacy & Security settings shows... Im not sure its useful

**Comment by lencx** [comment]
> I tried the steps you send and it cannot fix that problem. when I followed these steps, there no the Open Anyway button in Privacy & Security settings shows... Im not sure its useful

I seem to have encountered a similar situation before, you can try the following steps.
- Click install and the move to wastepaper basket popup appears, do not close the popup at this point
- Then go to security and you should see a question asking if the application is allowed

**Comment by RealAidanJoe** [comment]
> > I tried the steps you send and it cannot fix that problem. when I followed these steps, there no the Open Anyway button in Privacy & Security settings shows... Im not sure its useful
> 
> I seem to have encountered a similar situation before, you can try the following steps.
> 
> * Click install and the move to wastepaper basket popup appears, do not close the popup at this point
> * Then go to security and you should see a question asking if the application is allowed

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/71580066/220243512-256797ae-6e05-489c-affd-70f15fb93152.png">
Yeah, I know this. but for this app I clicked and went to security, there is no question asking me if the application is allowed

**Comment by lencx** [comment]
> Yeah, I know this. but for this app I clicked and went to security, there is no question asking me if the application is allowed

Try this and see if it helps. https://github.com/lencx/ChatGPT/issues/461#issuecomment-1437795469

**Comment by RealAidanJoe** [comment]
> Try this and see if it helps. [#461 (comment)](https://github.com/lencx/ChatGPT/issues/461#issuecomment-1437795469)
> 
> ```shell
> xattr -r -d com.apple.quarantine /YOUR_PATH/ChatGPT.app
> ```

Finally!!! thank u, its work!
