### ISSUE TITLE
[Security] Mac Binary not signed

### ISSUE THREAD

**Issue by nevotheless** [lencx/ChatGPT#382]
### Description

<img width="845" alt="image" src="https://user-images.githubusercontent.com/779797/218424189-8ce546a9-8818-4960-bd48-d038e14a13da.png">

Howdy 👋🏽 
This is probably obvious to the devs, but i think distributing a non-signed binary that is bypassing the MacOS security mechanism isn't the best idea in this day and age. I would really appreciate to not have to bypass Mac OS Security to run this app.

**Comment by lencx** [comment]
I don't have an Apple account to post them.

**Comment by xilopaint** [comment]
This project is quite popular. I believe it could easily gather donations to support an Apple Developer membership, which costs $99 per year.
