### ISSUE TITLE
[Bug] UI broken for ChatGPT Plus user

### ISSUE THREAD

**Issue by sunnywhy** [lencx/ChatGPT#387]
### Version

0.10.3 

### Bug description

After updating to ChatGPT Plus user, the UI doesn't work well. See below:
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/7128338/218569562-14e4c9a0-1f0d-43cd-8482-d01d04905639.png">

### OS

MacOS Monterey

**Comment by lencx** [comment]
You can try clearing the cache and then restarting the application:
- `~/Library/Caches/com.lencx.chatgpt`
- `～/Library/WebKit/com.lencx.chatgpt`

**Comment by sunnywhy** [comment]
Thank you! Clearing cache works!
