### ISSUE TITLE
[Feature]能增加文本框里字数长度设置的功能吗？现在能显示的字数太少了

### ISSUE THREAD

**Issue by shlockfan** [lencx/ChatGPT#388]
### Feature description

能增加字数长度设置的功能吗？可以自己设置下字数或长度，不然经常会显示不全

### Motivation

比如我要chatGPT写个1000字的作文，写到一半就不显示了，很无语，忘改善

### Additional context

<img width="506" alt="image" src="https://user-images.githubusercontent.com/11747918/218674492-4ff85c28-c92e-486b-bd17-3c7c10261c43.png">
就像这样，还没写完呢，后面的内容就没了

**Comment by lencx** [comment]
这个不是桌面应用的问题，限制来自 openai，应用只是官网的包装。

**Comment by shlockfan** [comment]
> 这个不是桌面应用的问题，限制来自 openai，应用只是官网的包装。

好吧，了解了

**Comment by lencx** [comment]
你在浏览器可以发长文字？
