### ISSUE TITLE
[Bug] An error occurred. Try refreshing your browser

### ISSUE THREAD

**Issue by boozedog** [lencx/ChatGPT#392]
### Version

v0.10.3

### Bug description

I am able to login to ChatGPT, but no matter what request I make, I get response `An error occurred. Try refreshing your browser.`

### OS

Ubuntu 22.04.1

**Comment by boozedog** [comment]
I don't know if this is a factor but I'm a ChatGPT Plus user.

**Comment by BFeins88** [comment]
I am as well and that only started when I upgraded

**Comment by MyWay** [comment]
Same, on the official website too.

**Comment by boozedog** [comment]
> Same, on the official website too.

Well there's now an outage affecting all users of ChatGPT. So that's different. But earlier today I was able to access ChatGPT on the web but not via the lencx/ChatGPT app. That's what this ticket is about.

**Comment by boozedog** [comment]
Related issue #396

**Comment by boozedog** [comment]
> I am as well and that only started when I upgraded

So maybe this an issue only affecting ChatGPT Plus users ... hmmm

**Comment by lencx** [comment]
> Related issue #396

If you are using a proxy, you need to use a global proxy. If there is an error accessing the application when the network is fine, the problem comes from openai and the application is just a wrapper for the website.

**Comment by boozedog** [comment]
> > Related issue #396
> 
> If you are using a proxy, you need to use a global proxy. If there is an error accessing the application when the network is fine, the problem comes from openai and the application is just a wrapper for the website.

I wasn't using a proxy. But it's working today so I guess maybe OpenAI fixed whatever was broken on their side.
