### ISSUE TITLE
Inject Script not working

### ISSUE THREAD

**Issue by CaiozScripts** [lencx/ChatGPT#395]
### Version

v0.10.3

### Bug description

I get this error when I try to use Inject script. I'm Portuguese so the error is basically in another language, it says "console" is not defined
![https://caiozs-very-epic-image-uploading-website.shx.is/5VCp6NeyC](https://caiozs-very-epic-image-uploading-website.shx.is/5VCp6NeyC.png)
(I'm trying to get the image thingy)

### OS

Windows 7 64-bits

**Comment by CaiozScripts** [comment]
Nvm, I had to put in a prompt first.

**Comment by lencx** [comment]
You can delete everything in `main.js` and restart the application.

**Comment by Leo4242** [comment]
> You can delete everything in `main.js` and restart the application.

Thank you!Your method has solved my problem.
