### ISSUE TITLE
Can't open app in linux ubuntu20.04

### ISSUE THREAD

**Issue by 33YANG** [lencx/ChatGPT#4]

**Comment by lencx** [comment]
You can try to run the application (the path of the application) through the terminal, and you may see an error message. I don't have any other computers besides mac, and I hope that more people can participate to make the program more robust.

**Comment by 33YANG** [comment]
> You can try to run the application (the path of the application) through the terminal, and you may see an error message. I don't have any other computers besides mac, and I hope that more people can participate to make the program more robust.

Thanks the reply, I can't open the chat-gpt app with click the icon. so what's the chat-gpt application startup command in terminal

when i type below command

```bash
> chat-gpt -h 
chat-gpt: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

**Comment by 33YANG** [comment]
That's ok, I could try the windows version in another PC

**Comment by lencx** [comment]
I can't solve the problem of app running on linux and windows platforms for the time being. I can only build them through `github action`. I also hope that more people can participate in this project in the future to continuously improve it.

**Comment by lencx** [comment]
I released a new version, you can try.

**Comment by kadirnar** [comment]
Ubuntu 18.04
Install:
```
sudo apt install ./chatgpt.deb -y
```
Run:
```
chat-gpt
```
Error Message:
```
chat-gpt: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

**Comment by lencx** [comment]
@kadirnar I'm very sorry, I don't have a linux environment to verify, if you can, I would like you to clone the project and try to run it locally, I can assist you.

**Comment by xueweiwujxw** [comment]
@kadirnar You can clone this repository and compile manually.
This error message may be related to the ssl library linked during compilation.
I have compiled on Ubuntu 20.04 and chat-apt worked well.
And the appimage target may cost a lot of time. You can edit the `tauri.conf.json` as below.
```json
      "targets": [
        "deb",
        "msi",
        "dmg"
      ],
```
I also found some warning message.
```shell
warning: unused variable: `titlebar_menu`
  --> src/app/menu.rs:43:9
   |
43 |     let titlebar_menu = if chat_conf.titlebar {
   |         ^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_titlebar_menu`
   |
   = note: `#[warn(unused_variables)]` on by default
```
I add some cfg attributes.
```diff
diff --git a/src-tauri/src/app/menu.rs b/src-tauri/src/app/menu.rs
index 8cf63eb..7b3454a 100644
--- a/src-tauri/src/app/menu.rs
+++ b/src-tauri/src/app/menu.rs
@@ -29,6 +29,7 @@ pub fn init() -> Menu {
 
     let stay_on_top =
         CustomMenuItem::new("stay_on_top".to_string(), "Stay On Top").accelerator("CmdOrCtrl+T");
+    #[cfg(target_os = "macos")]
     let titlebar =
         CustomMenuItem::new("titlebar".to_string(), "Titlebar").accelerator("CmdOrCtrl+B");
     let theme_light = CustomMenuItem::new("theme_light".to_string(), "Light");
@@ -40,6 +41,7 @@ pub fn init() -> Menu {
     } else {
         stay_on_top
     };
+    #[cfg(target_os = "macos")]
     let titlebar_menu = if chat_conf.titlebar {
         titlebar.selected()
     } else {
```
