### ISSUE TITLE
[Bug] HomeBrew installation doesn't work for v0.11.0

### ISSUE THREAD

**Issue by vburojevic** [lencx/ChatGPT#419]
### Version

v0.11.0

### Bug description

```
❯ brew install --cask chatgpt --no-quarantine
==> Downloading https://github.com/lencx/ChatGPT/releases/download/v0.11.0/ChatGPT_0.11.0_
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'chatgpt' with message: Download failed: https://github.com/lencx/ChatGPT/releases/download/v0.11.0/ChatGPT_0.11.0_macos_arm64.dmg
```

### OS

macOS 13.2.1

**Comment by vangie** [comment]
already fixed by https://github.com/lencx/ChatGPT/pull/425

**Comment by elalemanyo** [comment]
@vangie now installation works, thank you for that.
But now the app won't start 😔 It says that the application is corrupted.

**Comment by sebastianromano** [comment]
I had the same issue as @elalemanyo but uninstalling (`brew uninstall chatgpt`) and installing it again solved it. 
Running `brew reinstall` did not. 
Remember to backup your settings in `/.chatgpt/chat.conf.json` and your notes `/.chatgpt/chat.notes.json` if those are important to you :)

**Comment by vburojevic** [comment]
I still get the same 404 message.

**Comment by vburojevic** [comment]
Works now, closing!
