### ISSUE TITLE
汉化支持

### ISSUE THREAD

**Issue by Leizhenpeng** [lencx/ChatGPT#42]
参考vscode chatgpt 插件

chatgpt作为语言模型,中文环境和英文环境区别很明显

所以提供一致的汉化界面支持很有必要~

**Comment by lencx** [comment]
汉化需要做的工作有点多，目前还在实现功能阶段，所以这种需求会靠后处理。而且应用的菜单虽然是英文（但是在 readme 里都有中文版的详细说明），并不会影响功能的使用。
`chatgpt 作为语言模型,中文环境和英文环境区别很明显` 这个不是通过汉化就可以做到的，因为它只是集成的官网链接，并不能对链接的内容进行汉化。

**Comment by lencx** [comment]
汉化并不需要支持，之前是我理解错误，如果你需要 chatgpt 讲中文，只需要对它说“请讲中文”即可。
