### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by erdengbing** [lencx/ChatGPT#427]
### Version

0.11.0

### Bug description

"Hide Dock Icon" is true and "Enable SystemTray" is false that DISASTER ～

### OS

MacOS 12.6

**Comment by lencx** [comment]
Why is it necessary to hide both the dock and the system tray?
You can use `Activity Monitor` to kill the application process.
Then open the configuration file and change one of them to `true` (`~/.chatgpt/chat.conf.json`):
```json
{
  "tray": true,
  "hide_dock_icon": true
}
```
In the next version, I will make sure that at least one of them is `true`.

**Comment by erdengbing** [comment]
Thanks a lot 
and I didn't mean to set it up this way, it just happened to be the case.
