### ISSUE TITLE
[Feature] Make chat window wider

### ISSUE THREAD

**Issue by janissimsons** [lencx/ChatGPT#430]
### Feature description

The area where ChatGPT responds is too narrow for me, there could be more words per line and code examples also could be wider, many times the code samples are truncated and need to be scrolled horizontally.

At least give us an option to change the area width ourselves.

### Motivation

Difficult to read responses, often need to scroll horizontally when code samples are posted. 
Also need to scroll vertically because the column is way too narrow for reading.

**Comment by CommanderLake** [comment]
This along with the other problems like the inability to insert a line break and the shadow at the bottom being in front of the scroll bar REALLY needs to be fixed!

**Comment by daveamour** [comment]
https://www.paxium.co.uk/PublicArticle/Article/3233

**Comment by janissimsons** [comment]
> https://www.paxium.co.uk/PublicArticle/Article/3233

That's for the web version. I am talking about the desktop application.

**Comment by HemulGM** [comment]
> > https://www.paxium.co.uk/PublicArticle/Article/3233
> 
> That's for the web version. I am talking about the desktop application.

Try my client)
https://github.com/HemulGM/ChatGPT

**Comment by janissimsons** [comment]
> > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > 
> > 
> > That's for the web version. I am talking about the desktop application.
> 
> Try my client) https://github.com/HemulGM/ChatGPT

No, I don't trust anything that comes from Russia.

**Comment by HemulGM** [comment]
> > > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > > 
> > > 
> > > That's for the web version. I am talking about the desktop application.
> > 
> > Try my client) https://github.com/HemulGM/ChatGPT
> 
> No, I don't trust anything that comes from Russia.

Build from source yourself. And do you think it is generally reasonable to be so biased on a national basis?

**Comment by HemulGM** [comment]
> > > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > > 
> > > 
> > > That's for the web version. I am talking about the desktop application.
> > 
> > Try my client) https://github.com/HemulGM/ChatGPT
> 
> No, I don't trust anything that comes from Russia.

Build from source yourself. And do you think it is generally reasonable to be so biased on a national basis?

**Comment by janissimsons** [comment]
> > > > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > > > 
> > > > 
> > > > That's for the web version. I am talking about the desktop application.
> > > 
> > > 
> > > Try my client) https://github.com/HemulGM/ChatGPT
> > 
> > 
> > No, I don't trust anything that comes from Russia.
> 
> Build from source yourself. And do you think it is generally reasonable to be so biased on a national basis?

I don't have time to go through the entire codebase. And regarding Russia, yes it is completely reasonable not to trust anything that comes from an aggressor country that's under strict sanctions.

**Comment by HemulGM** [comment]
> > > > > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > > > > 
> > > > > 
> > > > > That's for the web version. I am talking about the desktop application.
> > > > 
> > > > 
> > > > Try my client) https://github.com/HemulGM/ChatGPT
> > > 
> > > 
> > > No, I don't trust anything that comes from Russia.
> > 
> > Build from source yourself. And do you think it is generally reasonable to be so biased on a national basis?
> 
> I don't have time to go through the entire codebase. And regarding Russia, yes it is completely reasonable not to trust anything that comes from an aggressor country that's under strict sanctions.

Nonsense. Start thinking with your head. Here are the same people. And none of us "voted" for something happening.

**Comment by janissimsons** [comment]
> > > > > > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > > > > > 
> > > > > > 
> > > > > > That's for the web version. I am talking about the desktop application.
> > > > > 
> > > > > 
> > > > > Try my client) https://github.com/HemulGM/ChatGPT
> > > > 
> > > > 
> > > > No, I don't trust anything that comes from Russia.
> > > 
> > > 
> > > Build from source yourself. And do you think it is generally reasonable to be so biased on a national basis?
> > 
> > 
> > I don't have time to go through the entire codebase. And regarding Russia, yes it is completely reasonable not to trust anything that comes from an aggressor country that's under strict sanctions.
> 
> Nonsense. Start thinking with your head. Here are the same people. And none of us "voted" for something happening.

And yet you do nothing to protest and change the existing regime that is slaughtering and torturing innocent civilians. Your mentality is the problem - stick your head in the sand and pretend nothing is happening and that it's not your problem.

**Comment by HemulGM** [comment]
> > > > > > > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > > > > > > 
> > > > > > > 
> > > > > > > That's for the web version. I am talking about the desktop application.
> > > > > > 
> > > > > > 
> > > > > > Try my client) https://github.com/HemulGM/ChatGPT
> > > > > 
> > > > > 
> > > > > No, I don't trust anything that comes from Russia.
> > > > 
> > > > 
> > > > Build from source yourself. And do you think it is generally reasonable to be so biased on a national basis?
> > > 
> > > 
> > > I don't have time to go through the entire codebase. And regarding Russia, yes it is completely reasonable not to trust anything that comes from an aggressor country that's under strict sanctions.
> > 
> > Nonsense. Start thinking with your head. Here are the same people. And none of us "voted" for something happening.
> 
> And yet you do nothing to protest and change the existing regime that is slaughtering and torturing innocent civilians. Your mentality is the problem - stick your head in the sand and pretend nothing is happening and that it's not your problem.
> 
> 

This is your propaganda, not ours. You were told so. We, too, are constantly told that all Americans are bad. Only a reasonable person would not take a word for such statements.How much have you protested against the war in Afghanistan or Syria or Kosovo? And what came of it? Don't be an idiot.

**Comment by janissimsons** [comment]
> 

Ok. I see that you have been brainwashed by the Russian propaganda. There's no point in talking to you then.
Also, I am not from the USA, but from the EU.

**Comment by janissimsons** [comment]
> > > > > > > > > https://www.paxium.co.uk/PublicArticle/Article/3233
> > > > > > > > 
> > > > > > > > 
> > > > > > > > That's for the web version. I am talking about the desktop application.
> > > > > > > 
> > > > > > > 
> > > > > > > Try my client) https://github.com/HemulGM/ChatGPT
> > > > > > 
> > > > > > 
> > > > > > No, I don't trust anything that comes from Russia.
> > > > > 
> > > > > 
> > > > > Build from source yourself. And do you think it is generally reasonable to be so biased on a national basis?
> > > > 
> > > > 
> > > > I don't have time to go through the entire codebase. And regarding Russia, yes it is completely reasonable not to trust anything that comes from an aggressor country that's under strict sanctions.
> > > 
> > > 
> > > Nonsense. Start thinking with your head. Here are the same people. And none of us "voted" for something happening.
> > 
> > 
> > And yet you do nothing to protest and change the existing regime that is slaughtering and torturing innocent civilians. Your mentality is the problem - stick your head in the sand and pretend nothing is happening and that it's not your problem.
> 
> This is your propaganda, not ours. You were told so. We, too, are constantly told that all Americans are bad. Only a reasonable person would not take a word for such statements.How much have you protested against the war in Afghanistan or Syria or Kosovo? And what came of it? Don't be an idiot.

Ok. I see that you have been brainwashed by the Russian propaganda. There's no point in talking to you then.
Also, I am not from the USA, but from the EU.

**Comment by HemulGM** [comment]
> 

This was an example. And I kind of said that reasonable people don't listen to propaganda. Mind their own business and think for themselves. Unlike you. For some reason, I'm not ill-disposed against people from Europe or the West, but you - yes. So who is under the influence of propaganda?

**Comment by bread22** [comment]
> https://www.paxium.co.uk/PublicArticle/Article/3233

I cannot find the style in those 2 pictures in my browser, I am using chrome on windows 10

**Comment by daveamour** [comment]
> > https://www.paxium.co.uk/PublicArticle/Article/3233
> 
> I cannot find the style in those 2 pictures in my browser, I am using chrome on windows 10

Which version of chatGPT?

**Comment by mattinordstrom** [comment]
For anyone using the web version and want a bookmark to click on to make the content wider:
Name: 90% chat
URL:
`javascript:(function() { var style = document.createElement('style'); style.innerHTML = '.flex.p-4.gap-4.text-base.md\\:gap-6.md\\:max-w-2xl.lg\\:max-w-xl.xl\\:max-w-3xl.md\\:py-6.lg\\:px-0.m-auto { max-width: 90% !important; }'; document.head.appendChild(style); })();`

**Comment by daveamour** [comment]
Nice!

**Comment by bread22** [comment]
> For anyone using the web version and want a bookmark to click on to make the content wider: Name: 90% chat URL: `javascript:(function() { var style = document.createElement('style'); style.innerHTML = '.flex.p-4.gap-4.text-base.md\\:gap-6.md\\:max-w-2xl.lg\\:max-w-xl.xl\\:max-w-3xl.md\\:py-6.lg\\:px-0.m-auto { max-width: 90% !important; }'; document.head.appendChild(style); })();`

Sorry to be dumb, how do I use this javascript? Thanks

**Comment by bread22** [comment]
> > For anyone using the web version and want a bookmark to click on to make the content wider: Name: 90% chat URL: `javascript:(function() { var style = document.createElement('style'); style.innerHTML = '.flex.p-4.gap-4.text-base.md\\:gap-6.md\\:max-w-2xl.lg\\:max-w-xl.xl\\:max-w-3xl.md\\:py-6.lg\\:px-0.m-auto { max-width: 90% !important; }'; document.head.appendChild(style); })();`
> 
> Sorry to be dumb, how do I use this javascript? Thanks

never mind, I figured it out.
- 1. open chatGPT
- 2. click the newly created bookmark
- 3. now it is wider


Thank you so much

**Comment by whitmark** [comment]
Check out the browser plugin:
https://microsoftedge.microsoft.com/addons/detail/chatgpt-widescreen-mode/obnaaalnokmchdoagnhmllakaclaaooa

**Comment by Combinacijus** [comment]
Also you can use above code with [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en) chrome extension and it will widen automatically:

```
// ==UserScript==
// @name         WidenChatGPT
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Makes ChatGPT window wider!
// @author       You
// @match        https://chat.openai.com/c/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=openai.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    let max_width = "90%";

    let style = document.createElement('style');
    style.innerHTML = `.flex.p-4.gap-4.text-base.md\\:gap-6.md\\:max-w-2xl.lg\\:max-w-xl.xl\\:max-w-3xl.md\\:py-6.lg\\:px-0.m-auto { max-width: ${max_width} !important; }`;
    document.head.appendChild(style);
})();
```

**Comment by bigggmoustache** [comment]
> Check out the browser plugin: https://microsoftedge.microsoft.com/addons/detail/chatgpt-widescreen-mode/obnaaalnokmchdoagnhmllakaclaaooa

I just tried it and nothing changed 😭 I'm guessing it's a problem on my end, any advice?

**Comment by bigggmoustache** [comment]
> Try this version from the Chrome Web Store for MS Edge https://chrome.google.com/webstore/detail/chatgpt-widescreen-mode/jgnjpnmofkalfliddjelaciggjgnphgm/related

Ty so much. For whatever reason the MS Store version didn't work but the Chrome Web Store version did.

**Comment by whitmark** [comment]
I know, right?  The developer seems to be at-the-ready to make changes as the ChatGPT UI evolves.

**Comment by bigggmoustache** [comment]
Homie is an absolute legend.

**Comment by rsaim** [comment]
Chrome extension which supports widescreen and adjusting the width: [ChatGPT WideScreen Adjuster
](https://chrome.google.com/webstore/detail/chatgpt-widescreen-adjust/ioimfefhpfjpifdfijgjnbiojlneeiac)

**Comment by JWBrownie** [comment]
@HemulGM I agree with you mostly, international matters are a joke to regular citizens, they just lie to us and give us small chunks of information for us to rage about but they never say the truth, most powerful nations are horrible, humans as species is going towards destruction and annihilation, I can't believe we have the capacity of construct anything but we chose to construct systems for hoarding power using tools of destruction and fear. To me let's get rid of frontiers, money, and everything that is rotten, we need to evolve a whole new civilization paradigm.

**Comment by p3k22** [comment]
Well, while it was hilarious to read the whole Russian argument on a coding website, here's what worked for me using Firefox.

Download TamperMonkey as suggested by Combinacijus, but instead of using his script, just use this;
`// ==UserScript==
// @name         WidenChatGPT
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Makes ChatGPT window wider!
// @author       You
// @match        https://chat.openai.com/c/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=openai.com
// @grant        none
// ==/UserScript==

(function() { var style = document.createElement('style'); style.innerHTML = '.flex.p-4.gap-4.text-base.md\\:gap-6.md\\:py-6.lg\\:px-0.m-auto { max-width: 90% !important; }'; document.head.appendChild(style); })();`
as written by mattinordstrom

Thanks

**Comment by banagale** [comment]
Thanks for highlighting that, @p3k22. This adjustment is badly needed for reading code output.

If people only need this occasionally, the last line above can also be run in the console on any desktop web view of a chatgpt conversation for immediate, one time full width output.

```
(function() { var style = document.createElement('style'); style.innerHTML = '.flex.p-4.gap-4.text-base.md\\:gap-6.md\\:py-6.lg\\:px-0.m-auto { max-width: 90% !important; }'; document.head.appendChild(style); })();
```

**Comment by MMALI3287** [comment]
> https://www.paxium.co.uk/PublicArticle/Article/3233

Is there any permanent solution

**Comment by cimpok** [comment]
>  Mind their own business and think for themselves. 

@HemulGM   Exactly that's how you (Russians, all of you) raised your beloved leader who now threatens to destroy a whole country, - and if it weren't a laughably pathetic bluff, the world.   He was very much dependent on your votes, he even blew up houses to make a few percent more of you love him  (Рязанский сахар). 
And even now, he is so scared of you (people) that when a few hundred armed guys with trucks set off for Moscow, they were not even halfway there when the very next day he was in the bunker of Valday, fleeing like a madman.   Have the balls to deal with it, if you've already unleashed this jerk and yourselves on the world! What are you Russian men, p.ssies?
Why is it any of our business? if anyone here has anything to do with it, it's you.

 And yes, there should be hard consequences for a nation for what leaders they choose, raise and support (80% of Russians supported this war and still do).  as it was for the Germans: a devastated country.   They learned their lesson. you will too.   
and you deserve to be treated like a Russian.   

...by the way, what pissed me off is that you're the one who's dispensing the 'wisdom' here (is it your Русский мир?), where does this arrogance of great russian empire come from?  If you subtract the energy and raw materials (we can agree it does not require nor talent nor ingenuity) from Russia's GDP, with the rest you are on par with an African country.   Name one thing in the past 30 years we are using and was invented in Russia.   Shame on you, being that large sh.t of country, you contribute nothing to the well-being of the world.  ....and so much could and should be done.   ...you do not even care that your own people do not live like rats.

**Comment by slaughters85j** [comment]
I just spent all day with ChatGPT-4 and arrived at a solution.

It involves making two snippets in the console.  In Safari or Chrome, open the console and go to the sources tab.  Hit the + to create a new snippet.  Call it whatever you like; I named mine ChatGPT_Widen and ChatGPT_Padding.

### In the widen one, paste this:

**// Fetch the stylesheet content
fetch('https://chat.openai.com/_next/static/css/acfe05ae539c013f.css')
  .then(response => response.text())
  .then(cssContent => {
    // Replace instances of max-width:48rem with max-width:100%
    const updatedCssContent = cssContent.replace(/max-width: 48rem/g, 'max-width: 100%');

    // Create a Blob with the updated CSS content
    const blob = new Blob([updatedCssContent], { type: 'text/css' });

    // Create a URL for the Blob
    const url = URL.createObjectURL(blob);

    // Create a new <link> element with the updated stylesheet
    const linkElement = document.createElement('link');
    linkElement.href = url;
    linkElement.rel = 'stylesheet';

    // Replace the existing stylesheet with the updated one
    const existingLinkElement = document.querySelector('link[href*="acfe05ae539c013f.css"]');
    existingLinkElement.replaceWith(linkElement);

    console.log('Stylesheet updated.');
  })
  .catch(error => {
    console.error('Error updating stylesheet:', error);
  });**

### In the padding one, paste this:

**// Find the element by its class name
const targetElement = document.querySelector('.relative.flex.h-full.max-w-full.flex-1.overflow-hidden');

if (targetElement) {
  // Apply padding-left: 20px
  targetElement.style.paddingLeft = '20px';

  console.log('Padding added to element.');
} else {
  console.log('Element not found.');
}**


Safari seems to save automatically, but Chrome said I might lose them when closing the console, so you can right-click and save them as JavaScript documents.

Once you enter, hit the play button next to the snippet name in Safari or right-click and run in Chrome.  Viola

Naturally, a browser extension would be more straightforward, but there doesn't seem to be one for Safari, and the ChatGPT Widen one for Chrome is currently broken.

**Comment by Hdooster** [comment]
I noticed the previous bookmarklet didn't work anymore for me:
`javascript:(function() { var style = document.createElement('style'); style.innerHTML = '.flex.p-4.gap-4.text-base.md\\:gap-6.md\\:py-6.lg\\:px-0.m-auto { max-width: 90% !important; }'; document.head.appendChild(style); })()`

I found out how to update it that has it working again for me (warning, I know nothing about javascript, this code is unreadable to me):
`javascript:(function() { var style = document.createElement('style'); style.innerHTML = '.flex.flex-1.gap-4.text-base.mx-auto.md\\:gap-6.md\\:max-w-2xl.lg\\:max-w-\\[38rem\\].xl\\:max-w-3xl { max-width: 90% !important; }'; document.head.appendChild(style); })();`

**Comment by mattinordstrom** [comment]
@Hdooster this should be enough:
`javascript:(function() { var style = document.createElement('style'); style.innerHTML = '.flex.flex-1.gap-4.text-base.md\\:gap-6 { max-width: 90% !important; }'; document.head.appendChild(style); })();`

However there is no guarantee that it will work forever

**Comment by cimpok** [comment]
as of October 1st chatGPT changed something in the site structure, I guess no more styles.css is served, or I don't know.   My extensions began throwing a runtime error 
Uncaught DOMException: Failed to execute 'addRule' on 'CSSStyleSheet': Cannot access StyleSheet to insertRule.

Solution:   change the code to this

const styleSheet = document.createElement('style')
document.head.appendChild(styleSheet)
styleSheet.textContent = '.text-base { min-width: 100% !important; }'

**Comment by Cody-Stevens** [comment]
> as of October 1st chatGPT changed something in the site structure, I guess no more styles.css is served, or I don't know. My extensions began throwing a runtime error Uncaught DOMException: Failed to execute 'addRule' on 'CSSStyleSheet': Cannot access StyleSheet to insertRule.
> 
> Solution: change the code to this
> 
> const styleSheet = document.createElement('style') document.head.appendChild(styleSheet) styleSheet.textContent = '.text-base { min-width: 100% !important; }'

That worked perfect for me. I updated the manifest in a fork here is anyone needs the updated manifest version: https://gist.github.com/Cody-Stevens/df2fef41a11b083a39f452ad45906281

**Comment by scronge** [comment]
> Thanks to the below commenters, the more future-proof bookmarklet is: `javascript:(function() { document.styleSheets[0].insertRule('.text-base { max-width: 95% !important; }', 0);})()`

Unfortunately, it seems this does not work anymore.

**Comment by daveamour** [comment]
> > Check out the browser plugin: https://microsoftedge.microsoft.com/addons/detail/chatgpt-widescreen-mode/obnaaalnokmchdoagnhmllakaclaaooa
> 
> I just tried it and nothing changed 😭 I'm guessing it's a problem on my end, any advice?

They changed things

Try this

const style = document.createElement('style');
style.innerText = `
.text-base {
    max-width: 100% !important;
    padding-left: 20px !important;
    padding-right: 20px !important;
}
`;
document.head.appendChild(style);

**Comment by ROBERT-MCDOWELL** [comment]
why the heck we cannot stretch it even manually? for coding, it's hell to watch it as it needs the horizontal bar to see the end of the code although wide area on left and right of the page are empty!

**Comment by scronge** [comment]
Updated bookmarklet:

javascript:(function(){const ID='cgpt-wide-style';const s=document.getElementById(ID);if(s){s.remove();return}const css=':root{--cgpt-sidepad:20px}main [class*="max-w-"],main [class*="mx-auto"],main .prose,main [class*="prose"],main .text-base,main [class*="text-base"],main div[data-message-author-role]{max-width:100%!important}main .prose,main [data-message-author-role],main [class*="text-base"]{padding-left:var(--cgpt-sidepad)!important;padding-right:var(--cgpt-sidepad)!important}main .prose img,main .prose pre,main .prose code,main [data-message-author-role] img,main [data-message-author-role] pre{max-width:100%!important}';const el=document.createElement('style');el.id=ID;el.appendChild(document.createTextNode(css));document.head.appendChild(el)})();
