### ISSUE TITLE
[Bug] ChatGPT_0.11.0_macos_aarch64 Can Not open

### ISSUE THREAD

**Issue by raykle** [lencx/ChatGPT#434]
### Version

v0.11.0

### Bug description

`ChatGPT_0.11.0_macos_aarch64` can not open. 

`ChatGPT_0.11.0_macos_x86_64` is OK

![image](https://user-images.githubusercontent.com/3097366/219849073-f12ac009-6f93-476a-9c4f-3f473cb79c3f.png)

<img width="634" alt="image" src="https://user-images.githubusercontent.com/3097366/219849155-83cab26e-0cff-41bf-b52a-c74e01a725f7.png">

### OS

macOS 12.6.3 21G419 arm64

**Comment by lencx** [comment]
你需要在系统设置安全里开启信任第三方，因为它并没有发布到商店

**Comment by raykle** [comment]
@lencx 我是允许的任何来源，上方有截图。

**Comment by lencx** [comment]
你是 m1 还是 m2?

**Comment by szcharlesji** [comment]
用`brew install --cask chatgpt --no-quarantine` 不加`--no-quarantine`不行

**Comment by raykle** [comment]
@lencx  m1 pro，是直接下载的安装包，`brew install` 的方式之前没试。

今天在公司试了一下公司的电脑，m1 的，`ChatGPT_0.11.0_macos_aarch64` 的包下载下来安装打开是可以的，`brew install` 却显示不可用，不知道为啥

<img width="911" alt="image" src="https://user-images.githubusercontent.com/3097366/219991599-5aa38696-a7ef-455a-a045-2c1a4a2bfb35.png">

**Comment by szcharlesji** [comment]
> @lencx m1 pro，是直接下载的安装包，`brew install` 的方式之前没试。
> 
> 今天在公司试了一下公司的电脑，m1 的，`ChatGPT_0.11.0_macos_aarch64` 的包下载下来安装打开是可以的，`brew install` 却显示不可用，不知道为啥
> 
> <img alt="image" width="911" src="https://user-images.githubusercontent.com/3097366/219991599-5aa38696-a7ef-455a-a045-2c1a4a2bfb35.png">

看Readme, 要先`brew tap lencx/chatgpt https://github.com/lencx/ChatGPT.git`

**Comment by raykle** [comment]
@szcharlesji 好的，谢谢
