### ISSUE TITLE
Hello, the access has been denied in china, is there a way to solve it now? 

### ISSUE THREAD

**Issue by logicbai** [lencx/ChatGPT#437]
### Provide a description of requested docs changes

Hello, the access has been denied in china, and is there a way to solve it now?

**Comment by asmirbelkic** [comment]
a vpn can solve your problem

**Comment by logicbai** [comment]
> a vpn can solve your problem

Using  VPN, openai in chrome can work well. But, it can not work in this software.

**Comment by lencx** [comment]
The proxy software needs to be enabled in global (system) mode for this to work.
