### ISSUE TITLE
[Bug]openai chatgpt stuck on "Please stand by, while we are checking your browser..."

### ISSUE THREAD

**Issue by Harsh-15610** [lencx/ChatGPT#439]
### Version

browser

### Bug description

Whenever I go to chatgpt, 

it comes "Please stand by, while we are checking your browser..." 
then a button "verify you are human"
then Cloudflare verification 
and it repeats 

### OS

windows 10

### Environment

im from india

**Comment by Ethkuil** [comment]
#386 duplicate, openai

**Comment by RGH4600** [comment]
I'm having same issue.
Also if the Logon/sign up screen comes up - Clicking on either option nothing happens.

 Edition	Windows 10 Pro
Version	22H2
Installed on	‎24/‎12/‎2021
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0

Browser =
Google Chrome
Version 110.0.5481.178 (Official Build) (64-bit)

**Comment by djvs** [comment]
Relevant console output:

```Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. [normal](https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/f2281/0x4AAAAAAAAjq6WYeRDKmebM/light/normal)
Content Security Policy: The page’s settings observed the loading of a resource at blob:https://challenges.cloudflare.com/c911b1c8-70af-4888-801f-48212864a508 (“worker-src”). A CSP report is being sent. [normal](https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/f2281/0x4AAAAAAAAjq6WYeRDKmebM/light/normal)
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. [normal](https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/f2281/0x4AAAAAAAAjq6WYeRDKmebM/light/normal)
Content Security Policy: The page’s settings observed the loading of a resource at blob:https://challenges.cloudflare.com/c911b1c8-70af-4888-801f-48212864a508 (“worker-src”). A CSP report is being sent.```

**Comment by XavierDELPIERRE** [comment]
If you have an anti- tracking software he might prevent cloudfire to authorize you

**Comment by SwapnilSoni1999** [comment]
Happens to me many times but after few minutes if I try again then it works with bunch of console errors

**Comment by yellowdopamine** [comment]
> If you have an anti- tracking software he might prevent cloudfire to authorize you

so what should i do if i don't want to be tracked?
