### ISSUE TITLE
[Feature] Remember Window Size and Position

### ISSUE THREAD

**Issue by cvladan** [lencx/ChatGPT#453]
### Feature description

It is widely accepted and agreed upon by the entire world that every application should remember the position and size of its window when closed, and should open in the same place and size when reopened.

I do not understand why you have introduced "innovation" here and ask users to enter "Default Width" and "Default Height" in the "Main Window" settings. These options are in fact irrelevant, since the window always opens in a different location due to the way Windows works, so size doesn't seem to fix anything.

Moreover, it is completely absurd to expect me to enter the ChatGPT App options and adjust them every time I switch from a large desktop monitor to my 13-inch laptop screen.

Therefore, I kindly request that the author completely eliminate the meaningless Default Width and Height options and implement the behavior of the tool like any other application in the world.

Thanks!

### Motivation

I believe that the author has successfully seized the opportunity to create a valuable tool, and for that reason, I would like to suggest some areas that I believe are problematic and badly need improvement.

### Alternatives

Manually adjusting every time I switch monitors

### Additional context

I would like to express my sincere **gratitude to the author** for his effort in creating a completely free, yet very useful application.

**Comment by lencx** [comment]
These are the two feaure that you can enable by configuration to save the window state, it is not enabled by default.
![image](https://user-images.githubusercontent.com/16164244/219978860-b0d551ba-39f5-4525-b17a-14fcf4e2b4e5.jpeg)

**Comment by cvladan** [comment]
Yes, you are correct!
Unfortunately, it seems that the function is **currently non-operational**.

By the way, I had to conduct a search to uncover the identical fact that you just wrote here.

In my opinion, the current labeling of the option is misleading, especially when the function is not operational. The term "State" typically refers to the open or closed status of something, or to the state of its content. I would suggest renaming the option to something more descriptive, such as "Save Window Position" or "Save Window Position and Size". Given the amount of available space on the dialog, there should be no issue with using more explicit and informative labels.

**Comment by cvladan** [comment]
So I'll create bug report
