### ISSUE TITLE
MacOS macos_aarch64 seems broken

### ISSUE THREAD

**Issue by roger-richards** [lencx/ChatGPT#461]
### Version

v0.11.0

### Bug description

Current build aarch64 when installed and run - MacOS Ventura:
“ChatGPT.app” is damaged and can’t be opened. You should move it to the Trash.

### OS

MacOS 13.1 / M1

### Environment

Macbook Pro M1

**Comment by jtenniswood** [comment]
Same situation. The x86 one works fine though

**Comment by lipengzhou** [comment]
> ### Version
> v0.11.0
> 
> ### Bug description
> Current build aarch64 when installed and run - MacOS Ventura: “ChatGPT.app” is damaged and can’t be opened. You should move it to the Trash.
> 
> ### OS
> MacOS 13.1 / M1
> 
> ### Environment
> Macbook Pro M1

+1

**Comment by lencx** [comment]
How to Fix App “is damaged and can’t be opened. You should move it to the Trash” Error on Mac. https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

**Comment by detecti1914** [comment]
> * [How to Fix App “is damaged and can’t be opened. You should move it to the Trash” Error on Mac](https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/)
> * [How to Fix “App Is Damaged and Can’t Be Opened” on Mac](https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/)
> 
> Open a terminal and try the following command:
> 
> ```shell
> xattr -r -d com.apple.quarantine /YOUR_PATH/ChatGPT.app
> ```

This command works

**Comment by VictoryBlue** [comment]
`xattr -r -d com.apple.quarantine /YOUR_PATH/ChatGPT.app
`
Execute above code, and the interface can be opened, but there is nothing in the interface

**Comment by VictoryBlue** [comment]
`xattr -r -d com.apple.quarantine /YOUR_PATH/ChatGPT.app
`
Execute above code, and the interface can be opened, but there is nothing in the interface
