### ISSUE TITLE
[Bug]is:issue is:open  i paid for the extra feature so if chatgpt was in high demand i would still be able to use chatgpt now i paid and its not letting me use it why is this happening 

### ISSUE THREAD

**Issue by 420G13** [lencx/ChatGPT#467]
### Version

i dont no

### Bug description

is:issue is:open  i paid for the extra feature so if chatgpt was in high demand i would still be able to use chatgpt now i paid and its not letting me use it why is this happening 

### OS

windows 10

### Environment

i dont think so ?

**Comment by lencx** [comment]
Access restrictions come from openai and are not related to this application.
