### ISSUE TITLE
Implement topbar CharGPT icon for dark mode environment in Linux

### ISSUE THREAD

**Issue by D3vil0p3r** [lencx/ChatGPT#47]
Hello,
I'm using Arch Linux with GNOME 43 in Dark Mode and when I run the AppImage on Linux for running it, the small icon of the application hides on the dark color of the topbar (it is the second icon in black (almost invisible)):

![image](https://user-images.githubusercontent.com/83867734/208316010-9675c8ae-8043-4aae-8a21-6d92f47bc447.png)

It is possible to use a ChatGPT icon similar to the one in the client (so with white colors?
![image](https://user-images.githubusercontent.com/83867734/208316097-d268ffdf-d78e-4b1a-a1a5-9f2483a4282b.png)

Since in the settings of the client the user can choose between Light or Dark environment in the Control Center, is it possible to set as default the Desktop environment? For example, if my Desktop Environment is already Dark, also ChatGPT client will have the Theme value set as Dark by default.

Thank you

**Comment by lencx** [comment]
It cannot be changed dynamically, you can try to redo the icon in white:
`tauri.conf.json -> tauri -> systemTray -> iconPath`

**Comment by D3vil0p3r** [comment]
> It cannot be changed dynamically, you can try to redo the icon in white: `tauri.conf.json -> tauri -> systemTray -> iconPath`

Thank you. It is useful. I'm closing the issue.
