### ISSUE TITLE
Login button not working (Windows) [Bug]

### ISSUE THREAD

**Issue by fraygl** [lencx/ChatGPT#471]
### Version

0.11.0

### Bug description

Good afternoon! I have such a problem. When trying to click on the login button, it doesn't seem to be pressed, I also tried pressing enter or ctrl + mouse click. Reinstalled the program, but alas, it also did not help. If you need additional information, I will be happy to present it, thank you!

You can see an example of reproducing the problem at the uploaded gif file
![Video_2023-02-21_202912](https://user-images.githubusercontent.com/13598334/220430904-6cf8c496-cda8-4997-91e9-8330b49e1b47.gif)
[ChatGPT.log](https://github.com/lencx/ChatGPT/files/10796577/ChatGPT.log)

### OS

Windows 11 Pro 22H2

**Comment by gg943** [comment]
I also encountered the same problem, my system is Windows 10, unfortunately, I did not solve the problem.

**Comment by qeez3** [comment]
I also have this same issue, I am using windows 10 too.

**Comment by lencx** [comment]
It looks like compatibility is causing the problem, but I don't have the same OS to verify this.

**Comment by provisota** [comment]
The **platform** is not only **Windows**!
I got the same issue on **Mac** 🙁 
macOs Monterey (version 12.6.3 (21G419)).
Browser Opera (version: 96.0.4693.20 (x86_64))

During loading the page has a lot of error messages in the console:

<p>
<details>
<summary>Browser console errors</summary>
<pre>
<code>745-f60cd68f2406c19f.js:1 Uncaught SyntaxError: Unexpected token '<' (at 745-f60cd68f2406c19f.js:1:1)
_app-dedfe8ecfffebe40.js:13          POST https://o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.react%2F7.21.1 429
(anonymous) @ _app-dedfe8ecfffebe40.js:13
u @ _app-dedfe8ecfffebe40.js:13
add @ _app-dedfe8ecfffebe40.js:13
send @ _app-dedfe8ecfffebe40.js:13
_sendEnvelope @ _app-dedfe8ecfffebe40.js:13
sendEvent @ _app-dedfe8ecfffebe40.js:12
sendEvent @ _app-dedfe8ecfffebe40.js:13
(anonymous) @ _app-dedfe8ecfffebe40.js:12
(anonymous) @ _app-dedfe8ecfffebe40.js:1
(anonymous) @ _app-dedfe8ecfffebe40.js:1
_executeHandlers @ _app-dedfe8ecfffebe40.js:1
(anonymous) @ _app-dedfe8ecfffebe40.js:1
u @ _app-dedfe8ecfffebe40.js:1
then @ _app-dedfe8ecfffebe40.js:1
_processEvent @ _app-dedfe8ecfffebe40.js:12
_captureEvent @ _app-dedfe8ecfffebe40.js:12
captureEvent @ _app-dedfe8ecfffebe40.js:12
(anonymous) @ _app-dedfe8ecfffebe40.js:1
_withClient @ _app-dedfe8ecfffebe40.js:1
captureEvent @ _app-dedfe8ecfffebe40.js:1
eK @ _app-dedfe8ecfffebe40.js:13
(anonymous) @ _app-dedfe8ecfffebe40.js:13
M @ _app-dedfe8ecfffebe40.js:7
R.onerror @ _app-dedfe8ecfffebe40.js:7
error (async)
(anonymous) @ _app-dedfe8ecfffebe40.js:7
N @ _app-dedfe8ecfffebe40.js:7
eZ @ _app-dedfe8ecfffebe40.js:13
setupOnce @ _app-dedfe8ecfffebe40.js:13
(anonymous) @ _app-dedfe8ecfffebe40.js:12
(anonymous) @ _app-dedfe8ecfffebe40.js:12
setupIntegrations @ _app-dedfe8ecfffebe40.js:12
bindClient @ _app-dedfe8ecfffebe40.js:1
(anonymous) @ _app-dedfe8ecfffebe40.js:13
(anonymous) @ _app-dedfe8ecfffebe40.js:13
37244 @ _app-dedfe8ecfffebe40.js:13
f @ webpack-d6a410b1bf4d686f.js:1
(anonymous) @ _app-dedfe8ecfffebe40.js:1
(anonymous) @ main-149b337e061b4d04.js:1
Promise.then (async)
onEntrypoint @ main-149b337e061b4d04.js:1
l @ main-149b337e061b4d04.js:1
32980 @ _app-dedfe8ecfffebe40.js:1
f @ webpack-d6a410b1bf4d686f.js:1
t @ _app-dedfe8ecfffebe40.js:16
(anonymous) @ _app-dedfe8ecfffebe40.js:16
f.O @ webpack-d6a410b1bf4d686f.js:1
(anonymous) @ _app-dedfe8ecfffebe40.js:16
i @ webpack-d6a410b1bf4d686f.js:1
(anonymous) @ _app-dedfe8ecfffebe40.js:1
24The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_SansSerif-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/SohneMono-Buch.otf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Script-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Size3-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Size2-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Math-BoldItalic.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Main-BoldItalic.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/Signifier-Regular.otf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_SansSerif-Italic.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Fraktur-Bold.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Math-Italic.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Fraktur-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Caligraphic-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/Sohne-Halbfett.otf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/SohneMono-Halbfett.otf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_SansSerif-Bold.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Size1-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Main-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Main-Italic.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Caligraphic-Bold.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Size4-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Main-Bold.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/Sohne-Buch.otf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
login:1 The resource https://chat.openai.com/fonts/KaTeX_Typewriter-Regular.woff was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.</code>
</pre>
</details>
</p>
But, it works fine under the Opera "incognito mode"! 🙂 

Clearing of cache and cookies for ```chat.openai.com``` didn't help.

**Comment by gg943** [comment]
我的该问题解决了，我把它的缓存关掉就好了，再打开控制台就没有错误了，禁止它缓存

**Comment by limty3899** [comment]
I have the same issue on 0.12.0

**Comment by Solitarygd** [comment]
> 我的该问题解决了，我把它的存档关掉就好了，再打开控制台就没有错误了，禁止它存档
![image](https://user-images.githubusercontent.com/119871707/226674195-ccc71663-190b-4d00-b45f-fb052ca92593.png)
Thanks, it worked with your method.
The problem I encountered was that after I entered https://chat.openai.com into the login interface in Google Chrome, the web page strangely did not respond after clicking the login button.
According to the method you said to disable caching, I press F12 to open the developer mode, select the network, and click Disable caching.
Refresh the interface when you're done, and lo and behold, it's back to work now, awesome.

**Comment by limty3899** [comment]
> > 我的该问题解决了，我把它的存档关掉就好了，再打开控制台就没有错误了，禁止它存档
> > ![image](https://user-images.githubusercontent.com/119871707/226674195-ccc71663-190b-4d00-b45f-fb052ca92593.png)
> > Thanks, it worked with your method.
> > The problem I encountered was that after I entered https://chat.openai.com into the login interface in Google Chrome, the web page strangely did not respond after clicking the login button.
> > According to the method you said to disable caching, I press F12 to open the developer mode, select the network, and click Disable caching.
> > Refresh the interface when you're done, and lo and behold, it's back to work now, awesome.

Thanks! It worked!

**Comment by chopinx** [comment]
On a mac, you can fix this problem by disabling the cache of the embedded browser inside the app, please follow these steps:

Click on Help -> Toggle Developer Tools
Enable the Network tab
Tick the "Disable cache" checkbox
Right-click on the login interface and click "Reload"
