### ISSUE TITLE
Some menu entries are empty

### ISSUE THREAD

**Issue by D3vil0p3r** [lencx/ChatGPT#48]
Hello,
I'm using the AppImage file for running ChatGPT desktop client and I note that some menu entries are empty. For example `Edit` does not spawn a list with entries:
![image](https://user-images.githubusercontent.com/83867734/208318359-690a5f44-217e-4ef3-817c-0c1f013765ea.png)

and `Window` spawns a rectangular window but with no entries:
![image](https://user-images.githubusercontent.com/83867734/208318397-4afc2f10-5d57-442a-8479-2c5a73466d04.png)

Furthermore, if I click on the menu "ChatGPT" -> "About ChatGPT", I get a window with no information:
![image](https://user-images.githubusercontent.com/83867734/208318448-f0d6965a-d164-4d94-b639-2100a814b71d.png)

OS: Arch Linux with GNOME 43
ChatGPT client version: 0.5.0

**Comment by lencx** [comment]
This is a basic feature provided by tauri, perhaps you should go to the tauri community and ask for compatibility with the relevant platform.

**Comment by lencx** [comment]
Menu Doc: https://docs.rs/tauri/1.2.2/tauri/struct.Menu.html

**Comment by lencx** [comment]
There is already a menu code in the project https://github.com/lencx/ChatGPT/blob/main/src-tauri/src/app/menu.rs
