### ISSUE TITLE
账号登陆逻辑

### ISSUE THREAD

**Issue by soysaucemo** [lencx/ChatGPT#49]
RT，我是用Microsoft的账号连入openai的，已经有账号并可以正常访问网页端chat（登陆是全局proxy），但是这个软件一直提示无法使用，感觉有点奇怪，可能和登陆逻辑有点关系，请教一下
网页访问
![image](https://user-images.githubusercontent.com/34964159/208333128-f3a4055c-827d-415f-86a5-be6ff97567f2.png)

本rep的软件访问
![image](https://user-images.githubusercontent.com/34964159/208332813-b6521321-cbcd-49ab-9b28-a6fbc550dd8d.png)

**Comment by lencx** [comment]
openai 限制地区是因为你的代理只在部分应用生效，并未代理到全系统。应用调用的是系统内置浏览器，登录会走 openai，并未做其他任何处理。

**Comment by yongtaof** [comment]
你好请教下系统内置浏览器是哪个啊，大佬可以内置一个chrome之类吗？全局代理太麻烦了，因为还有国内的网站，还有公司内网配置好麻烦，谢谢了。

**Comment by lencx** [comment]
@yongtaof 目前并没有相关 api 可以修改内置浏览器，mac 默认是 safari，windows 默认是 edge。

**Comment by Distruptors** [comment]
Cool

**Comment by rainbow401** [comment]
Verify your phone number
OpenAI's services are not available in your country.
