### ISSUE TITLE
Can't open after the latest Homebrew update

### ISSUE THREAD

**Issue by QYQSDTC** [lencx/ChatGPT#496]
### Version

0.11.0

### Bug description

<img width="262" alt="CleanShot-jNgHCM6J@2x" src="https://user-images.githubusercontent.com/15608306/221098790-765e7418-df13-4d84-9aa3-8fe76a88983d.png">

### OS

macOS Ventura 13.1

**Comment by lencx** [comment]
https://github.com/lencx/ChatGPT/issues/461
