### ISSUE TITLE
[Feature]Latex渲染，多脚本管理

### ISSUE THREAD

**Issue by fangyuan99** [lencx/ChatGPT#498]
### Feature description

1.在网页版中可以通过:[ChatGPT LaTeX Auto Render (OpenAI, you, bing, etc.)](https://greasyfork.org/zh-CN/scripts/456049-chatgpt-latex-auto-render-openai-you-bing-etc)等脚本实现渲染Latex公式的功能，但用本客户端还是无法渲染或者白屏，建议可以**内置功能或者适配一下脚本**。
2.希望对于**脚本注入**的功能可以增强一下，如果**多脚本**的话不太好管理

**Comment by micchickenburger** [comment]
Related issue: #432

**Comment by lencx** [comment]
这个项目以学习为主（不会接入更加复杂的功能了，因为国内已经出现了大量使用这个项目二次打包牟取私利的事情），我会在新项目中考虑插件化，你可以理解为 ChatGPT 将是新项目的一个子模块，它将提供更加通用的能力。
