### ISSUE TITLE
无法真正退出应用程序

### ISSUE THREAD

**Issue by Crazyokd** [lencx/ChatGPT#51]
1. 右键任务栏上的程序图标，点击关闭窗口无效。
![image](https://user-images.githubusercontent.com/74645100/208403731-2b4dea42-8f5e-4a06-b1e1-f1ffabb03bdc.png)

2. 点击关闭按钮并没有任何提示（仅最小化这种），但实际并没有真正关闭应用程序，还挂在任务栏上。
3. 任务栏右侧的程序小图标点击也无反应
4. 菜单栏Quit有效。

**Comment by Crazyokd** [comment]
刚刚下载使用了[最新版本](https://github.com/lencx/ChatGPT/releases/tag/v0.5.0)，发现第3点已经修复。

**Comment by lencx** [comment]
关闭窗口并不是真正的关闭，是为了防止误操作。需要用 Quit 来退出，这是专门设计的。因为一旦主窗口关闭，整个系统就会退出（包括系统托盘）。

**Comment by Crazyokd** [comment]
那能否在交互上优化一下，程序第一次运行点击关闭按钮时提示仅是最小化窗口这样

**Comment by lencx** [comment]
据我了解 tauri 目前暂未对 windows 提供支持，如果你了解到相关信息可以提供。

**Comment by RookieXwc** [comment]
> 据我了解 tauri 目前暂未对 windows 提供支持，如果你了解到相关信息可以提供。

@lencx ，你好，请问这个需求现在可以实现吗？像Crazyokd描述的那样，tauri在windows上关闭窗口后，任务栏不显示图标，仅系统托盘存在。我问了下chatgpt，回答是可以的，不知道这是否真的可行呢？感谢~


chatgpt回答内容：
是的，Tauri可以在Windows上实现在关闭窗口后，任务栏不显示图标，仅系统托盘存在。要实现这一功能，可以在Tauri应用程序中使用系统托盘库，如tauri-sys-tray，来创建系统托盘图标。然后，可以在应用程序的窗口关闭时，将窗口隐藏而不是关闭它，以保持托盘图标的存在。这样，即使关闭了窗口，应用程序仍将在后台运行，并且可以通过托盘图标访问。

以下是一个示例代码片段，演示了如何使用tauri-sys-tray库来创建系统托盘图标，并在窗口关闭时隐藏窗口：
```use tauri::SystemTray;

fn main() {
  let system_tray = SystemTray::new().unwrap();

  // 创建系统托盘图标
  system_tray
    .add_entry("myapp", "path/to/icon.png", "My App")
    .unwrap();

  // 创建应用程序窗口等操作...

  // 在窗口关闭时隐藏窗口，而不是关闭它
  window.on_close(|_| {
    window.hide().unwrap();
    Ok(())
  });

  // 运行应用程序
  tauri::Builder::default()
    .setup(|webview, _window| {
      // 在应用程序启动时执行的代码
      Ok(())
    })
    .run();
}
```
