### ISSUE TITLE
[Feature] 支持上传文件让 ChatGPT 学习

### ISSUE THREAD

**Issue by yuanzhixiang** [lencx/ChatGPT#514]
### Feature description

当前用 ChatGPT 只能依赖于 2021 以前的数据库，如果可以在聊天页面直接上传选中的文件让 ChatGPT 学习，那么可以大大增加 ChatGPT 的使用范围，比如我们自己写的小项目，我们就可以上传给 ChatGPT 让他学习，然后再问他想要的建议，比如说帮我们修改代码或者优化代码，在有上下文的情况下 ChatGPT 能够很好地完成这项工作。

另外既然如果我们能支持上传本地文件，那么上传指定的网页也可以实现，可以在 client 端将指定网页内容先下载下来，然后上传到 ChatGPT 让他学习，我们再提问相关的问题。

**Comment by allinprogram** [comment]
本项目只是chatGPT三方客户端，chatGPT为商业项目，你在这里发这个是毫无作用的。

**Comment by fengzhiyuan959** [comment]
目前chatgpt的临时情景记忆能力不够大，所以并不可行。除非把文件直接投喂进语料库，让chatgpt彻底理解并且永久记忆进数据库，但是这是不可能的，chatgpt不允许第三方直接投喂语料，因为这会让教坏chatgpt。但是以后随着算力的解放，的确可以大大提升临时记忆能力，到时候直接粘贴给它几百篇论文，让他总结文献综述还是挺不错的

**Comment by yuanzhixiang** [comment]
> 本项目只是chatGPT三方客户端，chatGPT为商业项目，你在这里发这个是毫无作用的。



> 目前chatgpt的临时情景记忆能力不够大，所以并不可行。除非把文件直接投喂进语料库，让chatgpt彻底理解并且永久记忆进数据库，但是这是不可能的，chatgpt不允许第三方直接投喂语料，因为这会让教坏chatgpt。但是以后随着算力的解放，的确可以大大提升临时记忆能力，到时候直接粘贴给它几百篇论文，让他总结文献综述还是挺不错的

在现在的项目上支持读取本地文件并通过聊天框发给 chatGPT 不就行了，只是省了手动拷贝的工作量。临时记忆的容量是个问题，不过我目前在一个聊天框上用了很长时间，也发过很多内容了，并没有出现 chatGPT 断开聊天重开的情况所以容量问题是需要测试的，不知道这个容量具体是多少，也有可能是因为我开了 plus 所以容量比较大。

这个需求你只要当成通过聊天框将文件代码读取出来并发给 chatGPT 就可以了，并没有多不切实际，请不要限制自己的想象力，把一些简单的事情想象的难如登天。

**Comment by yuanzhixiang** [comment]
更进一步说，这个需求只是在现在环境下的简单尝试，对写代码的完美辅助还是需要 IDE 集成 AGI，直接 IDE 内描述需求，AGI 读取完整代码库并理解再根据需求写出对应代码。人工只需要验证逻辑是否正确并 review 代码以及做微调即可。这样的功能我们一两年内就可能会在 IDE 内看到。

**Comment by fengzhiyuan959** [comment]
> 

关键就在于那个临时记忆，容量已经有人测试了，就是几千个字，不会再多了。如果你多次发送总计几万字的文字信息，记忆容量爆掉不会直接断掉聊天链接，而是会遗忘，最前面的细节他就记不得了，他只会记得你最近发送的几千个字

**Comment by yuanzhixiang** [comment]
> > 
> 
> 关键就在于那个临时记忆，容量已经有人测试了，就是几千个字，不会再多了。如果你多次发送总计几万字的文字信息，记忆容量爆掉不会直接断掉聊天链接，而是会遗忘，最前面的细节他就记不得了，他只会记得你最近发送的几千个字

如果是这样的话确实不行，需要等 AGI 后面的迭代才可能支持这样的功能

**Comment by fengzhiyuan959** [comment]
你连续给它发几篇网络小说，字数一旦超过记忆限制，再问第一章讲的啥啊，他就不记得了。像一条记忆只有七秒钟的鱼。这是属于硬件级别的缓存限制，毕竟几百万人的超级应用，每个人分配的缓存不可能太高。但是不排除后续有专门定制服务，来解除缓存限制，但是估计会很贵

**Comment by yuanzhixiang** [comment]
> 你连续给它发几篇网络小说，字数一旦超过记忆限制，再问第一章讲的啥啊，他就不记得了。像一条记忆只有七秒钟的鱼。这是属于硬件级别的缓存限制，毕竟几百万人的超级应用，每个人分配的缓存不可能太高。但是不排除后续有专门定制服务，来解除缓存限制，但是估计会很贵

是的，我试了下，我前面的提问已经忘了，只记得最近的提问，确实是差不多几万字的容量

**Comment by fengzhiyuan959** [comment]
牛蛙，plus就是不一样，一般用户就几千字的容量

**Comment by yuanzhixiang** [comment]
> 牛蛙，plus就是不一样，一般用户就几千字的容量

毕竟 20 刀一个月

**Comment by yuanzhixiang** [comment]
> 牛蛙，plus就是不一样，一般用户就几千字的容量

我数了下，也没有几万，也就几千，plus 用户这块没优势
