### ISSUE TITLE
[Bug] - Mac App not working/connecting. 

### ISSUE THREAD

**Issue by SandeepSAulakh** [lencx/ChatGPT#525]
### Version

0.11.0

### Bug description

MAC app is not connecting to server. Noting happening on screen. Not letting me logout or anything. Seems like Feb 09 version broke app or something.

### OS

MacOS Vantura - 13.2.1

**Comment by mingyanxizao** [comment]
some situation

**Comment by mingyanxizao** [comment]
same situation

**Comment by superniucong** [comment]
same situation

**Comment by rdewolff** [comment]
same error, rigged. Tried clean config folder and re-install, nothing works.

**Comment by SandeepSAulakh** [comment]
Seems like already fixed. Just tried it out and it is working just fine. Automagically!!
