### ISSUE TITLE
have the {q} tag in Edit to support where we put the caret

### ISSUE THREAD

**Issue by vlad-terin** [lencx/ChatGPT#54]
First, thank you for building this wonderful addon for chatgpt. 

I was wondering if it's in roadmap to support the prompt expansion, so your caret goes directly to the input field (similar how snippets work) 

Example: 

/prompt_title TAB -> prompt description "{q} (place where you enter your query)"

**Comment by lencx** [comment]
Thanks, that's a great idea, it seems like a lot of trouble if there are too many variables, I'll think about how to implement it.

**Comment by vlad-terin** [comment]
> Thanks, that's a great idea, it seems like a lot of trouble if there are too many variables, I'll think about how to implement it.

I think 1 variable is enough for now. Just the query placement. as right now - majority of the prompts from 
https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv

are something like this: 

I want you to act as an English translator, spelling corrector and improver. I will speak to you in any language and you will detect the language, translate it and answer in the corrected and improved version of my text, in English. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary. I want you to only reply the correction, the improvements and nothing else, do not write explanations. My first sentence is "istanbulu cok seviyom burada olmak cok guzel"

You would have to get away from keyboard to manually scroll right, delete the default prompt and input yours.
