### ISSUE TITLE
[Bug]生成答案后save到pdf&markdown&pic的选项会和reregenerate response一起连续闪烁【作者已答复】

### ISSUE THREAD

**Issue by dooozo** [lencx/ChatGPT#540]
### Version

Version 0.11.0 (20230216.160724)

### Bug description

您好，在生成答案后save到pdf&markdown&pic的选项会和reregenerate response一起连续闪烁。

### OS

macos 13.2.1 (22D68)

**Comment by wanzhiyu** [comment]
我也是同样的问题

**Comment by tk103331** [comment]
![GIF 2023-3-3 10-37-08](https://user-images.githubusercontent.com/4404609/222617471-41e18495-79db-4c21-a4d2-83604dac4d3e.gif)

**Comment by zimplexing** [comment]
+1 同样的问题

**Comment by zimplexing** [comment]
是不是可以把 issue 标题重新描述下，让作者和更多的人看到

**Comment by zjx14250** [comment]
我也是 windows 10

**Comment by juanjuanx5** [comment]
同样问题

**Comment by ZScai** [comment]
win11 一样的问题

**Comment by shakyun** [comment]
同样的问题

**Comment by lencx** [comment]
应该是 openai 修改了页面结构，导致部分代码不工作了

**Comment by lencx** [comment]
ref: #541
