### ISSUE TITLE
[Bug]Unable to load conversation

### ISSUE THREAD

**Issue by qiyuanchu** [lencx/ChatGPT#542]
### Version

v0.11.0

### Bug description

Before, you didn't need to use a proxy. Now you must, and when you go in and close the proxy, you are prompted Unable to load conversation.Here is a page that does not use a proxy:
![image](https://user-images.githubusercontent.com/96879316/222635012-7b030dbb-1cf3-4113-b7f6-1d8b91f19526.png)

### OS

win11

**Comment by ttimasdf** [comment]
Can't you Chinese guys just **SEARCH THOURH THE REPO WITHOUT SPAMMING THE ISSUES**???

I do that for you: https://github.com/lencx/ChatGPT/discussions/133#discussioncomment-5185557

**Comment by qiyuanchu** [comment]
> 难道你们中国人不能在不**发送问题的情况下搜索回购**吗???
> 
> 我为你这样做：[#133（评论）](https://github.com/lencx/ChatGPT/discussions/133#discussioncomment-5185557)

Sorry，I didn't notice that.I'll pay attention to that next time

**Comment by gulugulugulu9** [comment]
> Can't you Chinese guys just **SEARCH THOURH THE REPO WITHOUT SPAMMING THE ISSUES**???
> 
> I do that for you: [#133 (comment)](https://github.com/lencx/ChatGPT/discussions/133#discussioncomment-5185557)

thanks
