### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by GamerTronky** [lencx/ChatGPT#543]
### Version

v0.11

### Bug description

Every and each second when I'm chatting with ChatGPT, if ChatGPT doesn't write, the gui above where I can write
![image](https://user-images.githubusercontent.com/110632033/222641953-b408677a-57b6-44e2-9add-fba49a09b24f.png)
changes from 
![image](https://user-images.githubusercontent.com/110632033/222642005-34368ca9-1f07-457f-84af-5ce0bbb3093e.png)
to 
![image](https://user-images.githubusercontent.com/110632033/222642039-f8cf0903-6bb2-4e5a-8b2a-cb9d7f5551e8.png)
This is likely a bug.

### OS

Windows 10

**Comment by ttimasdf** [comment]
duplicate with #541
