### ISSUE TITLE
[Bug] The export button will dance 😭 (有图有真相)

### ISSUE THREAD

**Issue by h4rk8s** [lencx/ChatGPT#544]
### Version

latest

### Bug description

![Snapshot 2023-03-03 at 16 37 33](https://user-images.githubusercontent.com/63350517/222672612-e70ea892-82b3-4327-a357-d4a9b9e6dd8f.gif)

### OS

macOS 13.2.1 (22D68)

**Comment by akahello** [comment]
me too

**Comment by 7rikka** [comment]
我也是

**Comment by PengShaoLei1997** [comment]
me too

**Comment by AjianYo** [comment]
俺也一样

**Comment by jxxvxs** [comment]
Edition = Windows 11 Home Single Language
Version = 22H2
Installed on = 16 ‎Feb ‎2023
OS build = 22621.1265
Experience = Windows Feature Experience Pack 1000.22638.1000.0
![tes](https://user-images.githubusercontent.com/82653898/222703052-1633bf46-cae7-4ecf-8087-8a18c5927fce.gif)

**Comment by ahmed951** [comment]
me too 
os : windows 11

**Comment by dimitri-vs** [comment]
If you just want to hide the other three buttons to stop the flashing open up your console and run the code below.

Keep in mind his is a super hacky way to solve this problem, but it will do until a proper fix is implemented.

```
// Select the container element that holds the buttons
const container = document.querySelector('.btn').parentNode;

// Create a MutationObserver too look for changes
const observer = new MutationObserver(mutations => {
  mutations.forEach(mutation => {
    // Check if the added node is one of the buttons
    if (mutation.addedNodes && mutation.addedNodes.length > 0) {
      mutation.addedNodes.forEach(node => {
        if (node.id === 'download-markdown-button' || node.id === 'download-png-button' || node.id === 'download-pdf-button') {
          // Hide the button
          node.style.display = 'none';
        }
      });
    }
  });
});

// Start observing the container element for changes
observer.observe(container, { childList: true });
```

**Comment by andyyx41** [comment]
the same bug
os:win10

**Comment by 46135413** [comment]
控制台输入[dimitri-vs]的代码，是有效的，就是每次打开都要输入一下，麻烦一点，希望作者尽快fix

**Comment by biggujo** [comment]
same on Windows 10

**Comment by MicrowaveJak** [comment]
> If you just want to hide the other three buttons to stop the flashing open up your console and run the code below.
> 
> Keep in mind his is a super hacky way to solve this problem, but it will do until a proper fix is implemented.
> 
> ```
> // Select the buttons that you want to hide
> const buttons = document.querySelectorAll('#download-markdown-button, #download-png-button, #download-pdf-button');
> 
> // Create a new MutationObserver
> const observer = new MutationObserver(mutations => {
>   mutations.forEach(mutation => {
>     if (mutation.addedNodes) {
>       mutation.addedNodes.forEach(node => {
>         if (node.nodeType === Node.ELEMENT_NODE && node.matches('#download-markdown-button, #download-png-button, #download-pdf-button')) {
>           node.style.display = 'none';
>         }
>       });
>     }
>   });
> });
> 
> // Start observing the whole document for changes
> observer.observe(document, { childList: true, subtree: true });
> 
> // Hide the buttons that are already in the document
> buttons.forEach(button => button.style.display = 'none');
> ```
> 
> EDIT: Updated the code above to make the "fix" persist between change.

This worked great as a stop-gap so I could continue using the app while we wait for a fix. Thank you!

**Comment by lencx** [comment]
ref: #541

**Comment by RMatushkin** [comment]
https://github.com/lencx/ChatGPT/releases/tag/v0.11.1

**Comment by h4rk8s** [comment]
> > If you just want to hide the other three buttons to stop the flashing open up your console and run the code below.
> > Keep in mind his is a super hacky way to solve this problem, but it will do until a proper fix is implemented.
> > ```
> > // Select the buttons that you want to hide
> > const buttons = document.querySelectorAll('#download-markdown-button, #download-png-button, #download-pdf-button');
> > 
> > // Create a new MutationObserver
> > const observer = new MutationObserver(mutations => {
> >   mutations.forEach(mutation => {
> >     if (mutation.addedNodes) {
> >       mutation.addedNodes.forEach(node => {
> >         if (node.nodeType === Node.ELEMENT_NODE && node.matches('#download-markdown-button, #download-png-button, #download-pdf-button')) {
> >           node.style.display = 'none';
> >         }
> >       });
> >     }
> >   });
> > });
> > 
> > // Start observing the whole document for changes
> > observer.observe(document, { childList: true, subtree: true });
> > 
> > // Hide the buttons that are already in the document
> > buttons.forEach(button => button.style.display = 'none');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > EDIT: Updated the code above to make the "fix" persist between change.
> 
> This worked great as a stop-gap so I could continue using the app while we wait for a fix. Thank you!

thanks @MicrowaveJak
