### ISSUE TITLE
Ability to consume custom .csv prompt

### ISSUE THREAD

**Issue by vlad-terin** [lencx/ChatGPT#55]
Could you provide an ability to consume custom prompt links? 

If i have a personal repo where I gather all of my prompts - it would be great to point to that repo. 

Thanks!

**Comment by lencx** [comment]
This is a great suggestion and can be added in the next version.

**Comment by DancinDirk** [comment]
Are there instructions on how to use this feature? All I can find is sync prompts from the [awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts) repo, I don't see any instructions in the readme or help on how to add your own personal slash commands or point to a repo or use a csv. Any help would be appreciated!

**Comment by devnoname120** [comment]
@DancinDirk `ChatGPT` → `Preferences` → `Control Center` → `Prompts` → `Sync Custom` → `Add Prompt` → `URL` field → put `raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv`.
