### ISSUE TITLE
[Feature] Autofocus on text input area when activating window w/ hotkey

### ISSUE THREAD

**Issue by dsernst** [lencx/ChatGPT#550]
### Feature description

It would be a bit smoother and easier if the main ChatGPT text input box was autofocused as soon as the window is opened with the hotkey.

### Motivation

Smoother and easier way to invoke chatgpt, more like the default `Cmd+Space` Spotlight search on Mac.

### Alternatives

Thinking this could be possible with some custom javascript to find the element and focus on it. Something like:

```js
function focusOnInput () {
  // This currently works because there is only a single `<textarea>` element on the ChatGPT UI page.
  document.getElementsByTagName("textarea")[0].focus()
}
```

1. And then calling this function when the Open Window hotkey is pressed.

2. Or Perhaps another option would be to hook into `document.addEventListener("visibilitychange", focusOnInput)`, if the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) works for this sort of application. Unclear if this would work when bringing the window into focus, but if it does, it would work for opening the window with a mouse or using the Application Switcher too (Cmd + Tab).

**Comment by dsernst** [comment]
Got this working! By adding to the `main.js` custom user script file:

```js
document.addEventListener('visibilitychange', () => {
  document.getElementsByTagName('textarea')[0].focus()
})
```

**Comment by dsernst** [comment]
Looking into where in the code this file is written, as a PR so others can benefit from this as a new default, looks like here?

https://github.com/lencx/ChatGPT/blob/e2969b07e80f20591f2aef03b654ca3566a1034c/src-tauri/src/utils.rs#L50

**Comment by lencx** [comment]
Thank you for the suggestion. This file is created during the application initialization and will not take effect for existing users since `main.js` already exists. I can consider adding it to the core script in the next version.
