### ISSUE TITLE
[Security] Potential Malware Version 0.11.1

### ISSUE THREAD

**Issue by razvanazamfirei** [lencx/ChatGPT#559]
### Description

Potential malware in windows version. See link for analysis.

http://www.hybrid-analysis.com/sample/fc1e1c107ce5abed0793c1fda89baa841bb52e431fa2c3bb5a621b9ab249c37c

**Comment by razvanazamfirei** [comment]
Exec from obtained from the lencx/ChatGPT repo. 
hxxps://github.com/lencx/ChatGPT/releases/download/v0.11.1/ChatGPT_0.11.1_windows_x86_64.msi

**Comment by mike-lowski** [comment]
Same with v0.12.0

https://www.hybrid-analysis.com/sample/ed09b660a16215844f5072e6ea4821c17dcaa3eb9e3a48e864d9428850d48973

**Comment by GreenTeaBD** [comment]
This is the 2nd time this has happened. The last time it happened I got a malware alert from a version obtained by using the auto update in the program.
