### ISSUE TITLE
Copy/paste issue?

### ISSUE THREAD

**Issue by Aerasyn** [lencx/ChatGPT#56]
I copy some things out of the bot sometimes and when I copy from this program into microsoft word, it always produces a large text box around the pasted text. I hadn't seen this before and it's a little frustrating when I go to copy the paste from the word document. Is this intended behavior? Is there a way to disable this? Doesn't do it with other text editors, but their issue is formatting. I prefer how word formats text. I asked the bot but it had never heard of this program ;)

**Comment by Aerasyn** [comment]
![image](https://user-images.githubusercontent.com/933664/208571371-d62b0b89-3822-40e9-913e-097062bbb7ad.png)

**Comment by Aerasyn** [comment]
Doesn't do it with other text editors, but their issue is formatting. I prefer how word formats text.

**Comment by lencx** [comment]
Do you mean to copy the results from chatgpt app to microsoft word and encounter this problem? This problem may not be caused by the app, have you tried copying the results directly from `chat.openai.com`?

**Comment by Aerasyn** [comment]
Confirmed that it doesn't show the boxes when copied from the site directly:
![image](https://user-images.githubusercontent.com/933664/208579230-fe570b41-75bd-471a-b75b-2188c165a6f3.png)

**Comment by lencx** [comment]
Sorry, I can't reproduce the problem on my end. The application didn't do anything strange to the site.
