### ISSUE TITLE
[Build Error]

### ISSUE THREAD

**Issue by Kayce001** [lencx/ChatGPT#568]
### Error message

chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by chat-gpt)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by chat-gpt)
chat-gpt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libwebkit2gtk-4.0.so.37)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libwebkit2gtk-4.0.so.37)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libwebkit2gtk-4.0.so.37)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libwebkit2gtk-4.0.so.37)
chat-gpt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libwebkit2gtk-4.0.so.37)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libgtk-3.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libgdk-3.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libcairo.so.2)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libgio-2.0.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libgio-2.0.so.0)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libjavascriptcoregtk-4.0.so.18)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libjavascriptcoregtk-4.0.so.18)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libjavascriptcoregtk-4.0.so.18)
chat-gpt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libjavascriptcoregtk-4.0.so.18)
chat-gpt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libjavascriptcoregtk-4.0.so.18)
chat-gpt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_chat-gXpe7u3/usr/lib/libglib-2.0.so.0)

### OS

ubuntu20.04

**Comment by arthurwolf** [comment]
same here, no reply in a month...

**Comment by nikosT** [comment]
deb or appimage are not working either

**Comment by lencx** [comment]
ref: https://github.com/tauri-apps/tauri/issues/4707
