### ISSUE TITLE
Some minor issues with the 0.5.1 update process

### ISSUE THREAD

**Issue by PianoMastR64** [lencx/ChatGPT#58]
The installer was in Chinese for some reason. It looked like it tried to close the two ChatGPT windows I had open, but they minimized instead, so I had to close them manually via `Quit`, then the installation proceeded automatically. I would rather the installer communicated to me in English that I need to close the windows before it can proceed and then I press a button to manually continue the installation.

**Comment by whizyre** [comment]
Yeah I saw that its in chinese too I thought I was tripping. Its fine but at least I want to know why. I know lencx is from China so he probably just push the update on git using his normal installation on his side.

**Comment by lencx** [comment]
Is it a windows system, maybe it has something to do with a configuration I changed?

**Comment by PianoMastR64** [comment]
Windows 10

**Comment by lencx** [comment]
Please try v0.6.1 version.

**Comment by PianoMastR64** [comment]
I've updated a number of times and haven't seen these issues again. ...besides the lack of permission asking if I want to close the windows, but that's just my personal preference. That one doesn't even matter anymore anyway since we can access chat history now.
