### ISSUE TITLE
[Bug] Refresh Page Btn clears all chat conversation 

### ISSUE THREAD

**Issue by Purplishmoon** [lencx/ChatGPT#582]
### Version

v0.12.0

### Bug description

When I click the refresh page button, and after page refreshed, my all conversation at the sidebar cleared, this is not what I want to happen. After that I cant create new conversation, it can't generate new chat topic. I dont know why it also affects my chatgpt in web browser.

### OS

Windows 10 22H2

**Comment by wanzhiyu** [comment]
左侧对话列表完全消失，同样的问题。

**Comment by eshack94** [comment]
I am experiencing the same issue. Running v0.12.0 on MacOS.

@Purplishmoon Can you please update your bug title description to accurately summarize the issue?

**Comment by Toton-MAX** [comment]
![Uploading Screenshot_7.jpg…]()
Same issue. Running on Windows. Have the application open for less than an hour. Can't create new chats and there isn't even the default button of clear chats.

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/584#issuecomment-1459575027

**Comment by franjim10334** [comment]
Same thing happened to me when I Hit Ctrl + R, everything cleared

**Comment by lencx** [comment]
OpenAI has fixed this issue, log out of your account, then log back in and you'll see the chat history.
