### ISSUE TITLE
[Feature] chatgpt侧边栏不再显示历史对话

### ISSUE THREAD

**Issue by UntaggedRui** [lencx/ChatGPT#584]
### Feature description

chatgpt侧边栏不再显示历史对话，但是系统仍然保存了历史对话只是没有给用户提供入口进入，仍然可以通过conversation_id访问已经有的对话，例如我自己可以访问我的对话：https://chat.openai.com/chat/81ea48e1-5309-479f-8f32-51f243024a22。
希望在客户端的某个地方（例如菜单栏的某个子菜单里）能够提供历史对话的入口。

**Comment by Maxiah** [comment]
我也是，甚至网页版的侧边栏对话也消失了。离谱

**Comment by li-zihang** [comment]
相同情况。
如果浏览器也无法显示历史对话，这是不是OpenAI的bug？

**Comment by eshack94** [comment]
It appears that this is an OpenAI bug. See also: https://discord.com/channels/974519864045756446/1047565374645870743

**Comment by eshack94** [comment]
I do not think this is a bug with this client.

**Comment by UntaggedRui** [comment]
很明显这不是client的bug 因为这个项目只不过是一个网页套了壳，是chatgpt官方的问题。
但我觉得也许不是bug而是官方有意而为之？如果过了两天还没有恢复，也许就没有可以查看历史会话的功能了。

**Comment by lleiwork** [comment]
不是触发了无痕模式

**Comment by lleiwork** [comment]
是不是触发了无痕模式

**Comment by Jasonwu123** [comment]
chatgpt is currently under maintenance, and as a result, your chats may be temporarily missing.

a website under maintenance is like a pit stop for a race car—it's necessary to keep the car running smoothly, but it temporarily takes the car out of the race. similarly, website maintenance keeps the website functioning well, but it may disrupt its normal operations temporarily.

thanks for your patience!

**Comment by lencx** [comment]
English: https://github.com/lencx/ChatGPT/discussions/581#discussioncomment-5237163
中文：https://mp.weixin.qq.com/s/JE1M9lWpGBXQiTWXsBkjzA

**Comment by SmallCrankyLittleBird** [comment]
历史记录确实是没有了  而且也不能新建new chat  是官方的bug还是win系统的问题呀

**Comment by CFDreamer** [comment]
浏览器和客户端都没有

**Comment by yyxx1997** [comment]
我也是，web和pc都消失了！真的逆天这个bug！QAQ

**Comment by CFDreamer** [comment]
谁知道是官方的bug 还是官方封了这个功能呢

**Comment by lencx** [comment]
OpenAI 已经修复了这个问题，退出账号，再重新登录就可以了。

**Comment by wanghua-lei** [comment]
yes. logout restart

**Comment by cyx951211** [comment]
我依然有一样的问题。求是怎么解决的啊？？？？
