### ISSUE TITLE
[Bug] 无法显示侧边栏的历史对话，也无法创建新对话

### ISSUE THREAD

**Issue by Maxiah** [lencx/ChatGPT#585]
### Version

v0.12.0

### Bug description

客户端及网页都无法显示侧边栏的历史对话，也无法创建新对话
但是我在网页能根据历史记录找到我的历史对话

### OS

windows 10

**Comment by li-zihang** [comment]
与 https://github.com/lencx/ChatGPT/issues/584 重复了。
