### ISSUE TITLE
[Bug] [Fixed] Chat Conversation History Cleared with new update

### ISSUE THREAD

**Issue by northaven** [lencx/ChatGPT#586]
### Version

0.12.0

### Bug description

Loaded up ChatGPT tonight and all conversations have been cleared. I logged out and logged back in with no change. I tried to look in every section of the Configuration and couldn't find any of the conversations anywhere.

### OS

Windows 10

**Comment by khmt-khapro** [comment]
It's not a bug of chatgpt client. the problem seems to be caused by chatgpt api. You can log in on the web and find that the chat histories are gone

**Comment by allusernamestakenexceptthis** [comment]
After saw all history gone on openai,  I came searching for app that can keep history locally. if not already implemented, can we add it? what's the best place in code to start? I have never developed in rust before, so I appreciate guidance. thanks

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/584#issuecomment-1459575027

**Comment by MikeCee69** [comment]
Yes, all gone. In the client and on the web. This is a massive pain.

**Comment by mrpastewart** [comment]
+1 I lost a ton of work

**Comment by lencx** [comment]
OpenAI has fixed this issue, log out of your account, then log back in and you'll see the chat history.

**Comment by KenjutsuGH** [comment]
The issue seems to be resolved now

**Comment by northaven** [comment]
Confirmed fixed here. Whew! :) Thank you all!

**Comment by MikeCee69** [comment]
Yes, fantastic. Thank you.

**Comment by minhhungit** [comment]
it works after re-login, thanks
