### ISSUE TITLE
[Bug] start failed

### ISSUE THREAD

**Issue by Oliverwqcwrw** [lencx/ChatGPT#588]
### Version

0.12.0

### Bug description

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/31796988/223668932-70cdfd17-6223-4e02-85ce-48e4c783640b.png">

### OS

Mac OS 12.6

**Comment by ianzhang221** [comment]
We have detected suspicious login behavior and further attempts will be blocked. Please contact the administrator

**Comment by jettbriggs** [comment]
Yeah, the desktop app won't open.
