### ISSUE TITLE
是否可以新增API密钥登录

### ISSUE THREAD

**Issue by nowhash6120** [lencx/ChatGPT#590]
### Feature description

多添加一个登录的选项，可以使用api密钥登录的入口。可以使用户通过自己的api密钥更快速的访问OpenAI，避免访问断开、访问被拒绝，IP限制等问题。

当然，常规情况下，可以正常使用官方接口访问，紧急必要的情况，可以使用密钥切换。

### Motivation

避免访问断开、访问被拒绝，IP限制等问题。

**Comment by lencx** [comment]
全部在这里讨论：https://github.com/lencx/ChatGPT/issues/553

**Comment by lencx** [comment]
Support API Key: https://github.com/lencx/nofwl
