### ISSUE TITLE
[Bug] Chat History does not load

### ISSUE THREAD

**Issue by openfist** [lencx/ChatGPT#593]
### Version

Version 0.12.0 (20230305.043006)

### Bug description

Chat History does not load

![Markup on 2023-03-08 at 22:41:44](https://user-images.githubusercontent.com/11617249/223743054-b3a1a302-71df-449e-9475-fabb4de09449.png)

Previously all out chat histories would be present in the sidebar.

Thank you.

### OS

OSX 13.2 (22D49)

**Comment by forgetmetoo** [comment]
I also encountered the same problem

**Comment by einsof-creator** [comment]
This happened to me also this morning before and after the recent update. I had to log out and log back in to fix the issue and have my old chatlogs reappear.

**Comment by schmooster** [comment]
reporting in - same issue, chat-gpt desktop won't show history, after the event at OpenAI which stopped histories showing. when history was restored on the openai site, the desktop client still had trouble showing history. Logging out & logging in again, I saw 1 "unable to load history, retry" and on retry my history was loaded. 
Summary, as mentioned in previous comment, - log out & in again, retry history, it should show.

**Comment by panezhang** [comment]
same issue, `https://chat.openai.com/backend-api/conversations?offset=0&limit=20` failed with error:

```
{
    "detail": {
        "message": "Incorrect API key provided: undefined. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
```

**Comment by Simbazuva** [comment]
> reporting in - same issue, chat-gpt desktop won't show history, after the event at OpenAI which stopped histories showing. when history was restored on the openai site, the desktop client still had trouble showing history. Logging out & logging in again, I saw 1 "unable to load history, retry" and on retry my history was loaded. Summary, as mentioned in previous comment, - log out & in again, retry history, it should show.

not woking

**Comment by MartinGonzalez** [comment]
Same:
* Logged out and in again not working
* Reinstalling not working
* Clearing the config.json not working

**Comment by RebelYoung** [comment]
The history has reloaded in Explorer on website, but hasn't recovered in client.
Client:
![image](https://user-images.githubusercontent.com/59256512/223913386-e6c32e73-9d39-4ef9-999f-cdffb34fffb3.png)
Website:
![image](https://user-images.githubusercontent.com/59256512/223913541-a01a7e10-f760-4f52-9ef2-bf6a61915f5c.png)

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/584#issuecomment-1459575027

**Comment by msebastian100** [comment]
Same problem
