### ISSUE TITLE
Mac (Arm) says app is damaged

### ISSUE THREAD

**Issue by ifuchs** [lencx/ChatGPT#595]
### Error message

“ChatGPT.app” is damaged and can’t be opened. You should move it to the Trash.

### OS

Mac OS 13.2.1 Ventura

**Comment by xmwa** [comment]
same with monterey 12.5.1 for aarch version, althrough x64 version works.

**Comment by Swiftsss** [comment]
> ### Error message
> “ChatGPT.app” is damaged and can’t be opened. You should move it to the Trash.
> 
> ### OS
> Mac OS 13.2.1 Ventura
> 
> ### Environment
> _No response_

https://github.com/lencx/ChatGPT/issues/461#issuecomment-1451965759

**Comment by AKACC** [comment]
1. Open your terminal
2. Go to the `Applications` directory. My is `/Applications`
3. Run `xattr -cr ChatGPT.app` and open the app again

Use `xattr` can ignore the error. The `-c` flag removes all attributes, whereas `-r` applies recursively for the entire targeted .app directory contents. Please make sure you download from reliable sources.

**Comment by jaxsnjohnson** [comment]
Issue has reappeared today after an update.  The commands above resolve the issue.  Wanted to bring it devs attention if it is a packaging issue or something.
