### ISSUE TITLE
The app is broken

### ISSUE THREAD

**Issue by etherealxx** [lencx/ChatGPT#61]
So about an hour ago, the ChatGPT server goes down. When i opened the app at that moment, it shows this
<img src="https://user-images.githubusercontent.com/64251396/209297925-2e9d3b93-1777-4395-b63b-ee237a201c64.jpg" alt="209297925-2e9d3b93-1777-4395-b63b-ee237a201c64" width="600"/>

And now the server is back online and accessible via browser, yet the app doesn't shows up the site.
<img src="https://user-images.githubusercontent.com/64251396/209298512-5517ecb1-918d-4bf3-9952-566c5c9a4246.jpg" alt="209298512-5517ecb1-918d-4bf3-9952-566c5c9a424" width="600"/>
<img src="https://user-images.githubusercontent.com/64251396/209298518-5c472a60-a705-4557-b5c5-bf7494a67322.jpg" alt="209298518-5c472a60-a705-4557-b5c5-bf7494a67322" width="600"/>

I tried to reinstall, but no luck. The device is WIndows 11.

**Comment by lencx** [comment]
Are you a Chinese user? This problem often occurs in China. It's because of the network.

**Comment by etherealxx** [comment]
Problem solved somehow.
