### ISSUE TITLE
The history of chats is empty

### ISSUE THREAD

**Issue by VgherdaV** [lencx/ChatGPT#613]
### Version

v0.12.0

### Bug description

The history of chats is empty, despite that I did not delete anything and I still have subscription on chatGPT

### OS

Windows 10 pro license

**Comment by hosteren** [comment]
Logging out and back in solved this for me.

**Comment by robazprogrammer** [comment]
Logging out and back in also solved this for me.

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/691#issuecomment-1480544435
