### ISSUE TITLE
[Security]ChatGPT报错“Too many requests in 1 hour.Try again later“

### ISSUE THREAD

**Issue by MrGongqi** [lencx/ChatGPT#625]
### Description

每次使用的时候就会跳出ChatGPT报错“Too many requests in 1 hour.Try again later“的问题，结果我让别人（和我用的是不同的VPN软件）用我的账号试了一下有完全没问题，我一使用就出现该问题，登网页版也是同样的报错

**Comment by ZaynJarvis** [comment]
和这个客户端没关系，是 ChatGPT 本身的API限流，网页端访问会有一样的错误

**Comment by luckysunle** [comment]
解决了吗？我最近也遇到这个问题了

**Comment by soft-air** [comment]
我也遇见了，很恶心。问了一个问题之后，再问第二个问题，就弹出来这个报错
![image](https://github.com/lencx/ChatGPT/assets/83157751/3626f13e-4f0c-48fd-9c4c-1786702773fe)

**Comment by solmyr118** [comment]
换个IP似乎就可以了

**Comment by riven13738072387** [comment]
好像

> 换个IP似乎就可以了

不行啊，换了节点还是不行，从PC网页换成手机网页就又可以了

**Comment by liucx1201** [comment]
> 解决了吗？我最近也遇到这个问题了
