### ISSUE TITLE
v0.6.1 can't sync prompts (seems like it can't access config file

### ISSUE THREAD

**Issue by Reself-C** [lencx/ChatGPT#64]
Thank you for such great APP, it's much better than its offcial web version. Here is a problem:
for v0.6.1 in Win 10, I can't use prompt cmd "/", sync awesome list (no response), and even store my custom prompt. I restart ChatGPT after each operation. Is that a bug or my mistake.

**Comment by lencx** [comment]
What is your region? The inability to sync could also be due to the network. It requires a reboot under windows, which I can't verify at the moment (I only have a mac)

**Comment by Reself-C** [comment]
China, but on VPN, but it seems like it can't access config file, i can't import or write in local file as well

**Comment by lencx** [comment]
I'm releasing v0.6.2 because the file write failed due to path permission problem.

**Comment by lencx** [comment]
> I'm releasing v0.6.2 because the file write failed due to path permission problem.

😭 I failed again, the online build and my local build, don't seem to be the same.

**Comment by Reself-C** [comment]
> 

lol, patpat, u r the best !

**Comment by roshanravan** [comment]
stocked on 0.6.2 update and does nothing

**Comment by lencx** [comment]
I'm in the process of releasing a new version, and the first two fixes failed.

**Comment by nhan000** [comment]
I'm having the same problem. Only 0.5.1 works for me. From 0.6.0-0.6.4 they didn't work. I'm on Windows 10.

**Comment by lencx** [comment]
I tried seven builds, but they all failed. Currently waiting for a response from them https://github.com/tauri-apps/tauri/issues/5907

**Comment by lencx** [comment]
I tried seven builds, but they all failed. Currently waiting for a response from them https://github.com/tauri-apps/tauri/issues/5907

**Comment by lencx** [comment]
Please try v0.6.9 version

**Comment by nhan000** [comment]
still not working :(

**Comment by lencx** [comment]
I tried is good, are you clicking the sync button is what state?

**Comment by nhan000** [comment]
It appears to be loading but doesn't do anything. I just uninstalled and reinstalled 0.6.9
![image](https://user-images.githubusercontent.com/85216095/209449417-6d756e4a-1256-4b50-a16a-ce0a92e41129.png)

**Comment by nhan000** [comment]
I clicked it and it doesn't do anything. I just uninstalled, downloaded and reinstalled 0.6.9.
![image](https://user-images.githubusercontent.com/85216095/209449453-9ed98997-f701-46d8-be7d-389946bfcc7b.png)

**Comment by nhan000** [comment]
I saw a comment about [kaspersky blocking](https://github.com/lencx/ChatGPT/issues/76#issuecomment-1364573439). I'm using Kaspersky and will check it now.

**Comment by nhan000** [comment]
This is what happen in the console when I click the "Sync Prompts" tab and then "Sync". Idk if this is helpful.
![image](https://user-images.githubusercontent.com/85216095/209449945-9e14886b-6eca-4c72-ad00-42b070d75eb7.png)

**Comment by lencx** [comment]
It seems a bit complicated on Windows, and I don't have a computer to verify it. I will try to modify it again and need your help to verify it.

**Comment by lencx** [comment]
@nhan000 Please try v0.6.10 version

**Comment by nhan000** [comment]
it works finally! Thank you so much!

![image](https://user-images.githubusercontent.com/85216095/209454573-b772114c-213c-4011-b23c-4fa992e82874.png)
