### ISSUE TITLE
[Bug]can't sync prompt

### ISSUE THREAD

**Issue by lanson07** [lencx/ChatGPT#646]
### Version

0.12.0

### Bug description

Sync prompts from f/awesome-chatgpt-prompts/prompts.csv failed!
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/29429038/225806415-8ad03af4-d60f-4269-9190-759b082f9e86.png">

### OS

macOS

**Comment by fangker** [comment]
Replacing the cache file did not display the prompts

**Comment by lanson07** [comment]
> 

Thanks a lot! It works.

**Comment by delvindonn** [comment]
> > 
> 
> Thanks a lot! It works.

sorry, i don't understand how to replace it , is that means delete the chatgpt_prompts.json file or any other action ?

**Comment by delvindonn** [comment]
i have slove the problem, i use a clash vpn, indeed you need turn to the **Enhanced mode**.

> > > 
> > 
> > 
> > Thanks a lot! It works.
> 
> @lanson07 sorry, i don't understand how to replace it , is that means delete the chatgpt_prompts.json file or any other action ?
