### ISSUE TITLE
[Feature] v2ray协议的魔法会被除你武器

### ISSUE THREAD

**Issue by Sola1Go** [lencx/ChatGPT#649]
### Feature description

chrome://flags/#enable-quic
把该选项设置为Disabled网页就可以访问openai了, 否则会被Access denied

此时, 我的浏览器可以访问
![image](https://user-images.githubusercontent.com/33821622/225877310-ce40cecd-6600-4ebc-a00b-68c7d0766249.png)
但是客户端寄了
![image](https://user-images.githubusercontent.com/33821622/225877354-6a04a3ca-a5f9-4cc8-92b4-510c575ca4cb.png)

**Comment by Gaoyukun** [comment]
在代理里同时代理UDP流量, 或者在防火墙里拒绝443端口, 80端口的UDP流量, 可以解决这个问题

**Comment by LoveClears** [comment]
> 在代理里同步代理UDP流量，或者者在防火墙里拒绝443端口，80端口的UDP流量，可以解决这个问题

openwrt可以操作吗 大佬可以教一下吗
