### ISSUE TITLE
[Bug] dark theme does not effort

### ISSUE THREAD

**Issue by Similarityoung** [lencx/ChatGPT#652]
### Version

v0.12.0

### Bug description

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/94664304/225918069-b1391c40-20f7-413a-9ca7-96f8ff6ce80c.png">
when I switch to the dark theme, and after I restart the application, it still keeps the light theme.

### OS

windows11

**Comment by drhouse** [comment]
+1 same issue

**Comment by noxy-k** [comment]
+1 same problem.

**Comment by Suntz246** [comment]
+1 same issue

**Comment by menawi** [comment]
@Similarityoung Try this https://github.com/menawi/Desktop-ChatGPT-Dark-Mode-Styling
