### ISSUE TITLE
[Bug] Custom prompts synced，但是没有任何prompts被加载进去

### ISSUE THREAD

**Issue by linjunshi** [lencx/ChatGPT#656]
### Version

0.12.0

### Bug description

您好，想反馈下这个问题，我加进了https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv 作为PATH，sync之后显示成功，但是点View按钮进去却什么也没加载进去

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/14053321/226094966-bbcfb8c5-e4bc-4f59-9f6e-464efe142fbc.png">
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/14053321/226095034-ad9bdbeb-7f9a-459d-b925-43c0f878b6cc.png">

### OS

Mac OS Ventura 13.0.1

### Environment

M1 Macbook Pro

**Comment by subaiwen** [comment]
+1

**Comment by lencx** [comment]
你输入的地址是错误的，需要的静态资源文件地址，而不是 github 文件地址 https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv。

**Comment by linjunshi** [comment]
明白了，感谢

**Comment by linjunshi** [comment]
您好，放进这个静态文件网址之后会出现报错
<img width="925" alt="image" src="https://user-images.githubusercontent.com/14053321/226951684-85b1612b-8eff-466f-ac9b-4acae34758ae.png">

**Comment by lincome** [comment]
中文cmd解析有问题
![image](https://user-images.githubusercontent.com/7379732/229980373-8074305c-8387-427d-b028-c1f0ccff6476.png)
