### ISSUE TITLE
Bad gateway 502

### ISSUE THREAD

**Issue by joshgpurvis** [lencx/ChatGPT#673]
### Version

4

### Bug description

Bad gateway
The web server reported a bad gateway error.

Ray ID: 7ab160c02b5ddb96
Your IP address: [deleted]
Error reference number: 502
Cloudflare Location: Los Angeles

### OS

MacOS 13.2.1 (22D68)

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/671
