### ISSUE TITLE
[Bug] No Conversation History again

### ISSUE THREAD

**Issue by lishuhang** [lencx/ChatGPT#678]
### Version

v0.12.0

### Bug description

之前是有的，即使在官网没有对话记录的时候这里也有。但是今天就没有了
Before today, conversation history could be found in the app even if ChatGPT web page didn't. Today it disappaered in the app, either.

![Screenshot](https://lishuhang.me/img/2023/03/20230321121413.png)

### OS

Windows 11

**Comment by CrankyKing** [comment]
me too !And when i login by  chatGPT.exe it did not have any response ,but when i login by website,it can use !

**Comment by lencx** [comment]
ref: https://github.com/lencx/ChatGPT/issues/691#issuecomment-1480544435
