### ISSUE TITLE
Application can not be close  [Bug]

### ISSUE THREAD

**Issue by iam-rajesh-patnala** [lencx/ChatGPT#679]
### Version

V0.12.0

### Bug description

Application can not be close after clicking Close button, it is minimizes

### OS

windows 10

**Comment by Melyyn** [comment]
I have the same issue as well, a work around is either to click on chatgpt tool bar & click "quit", or going to the system tray bar & right clicking then quit

**Comment by lencx** [comment]
`Menu - Control Center - Settings - Main Window - Close Exit`
