### ISSUE TITLE
[Bug] 导入中文prompts后指令无法显示中文

### ISSUE THREAD

**Issue by hsw15192617273** [lencx/ChatGPT#704]
### Version

0.12.0

### Bug description

导入了该prompts: https://raw.githubusercontent.com/PlexPt/awesome-chatgpt-prompts-zh/main/prompts-zh.json

cmd执行中中文用下划线显示
![image](https://user-images.githubusercontent.com/77371957/227495385-541ed028-5406-4786-a3b7-5d355d5a6dc8.png)

在聊天界面输入命令时也是显示下划线
![image](https://user-images.githubusercontent.com/77371957/227495580-3b3ce9bc-98eb-4916-a97d-bd2c0ff5d19b.png)

### OS

macOS 12.5.1

**Comment by deardeer7** [comment]
> @hsw15192617273 这是本身中文prompts那个文件没写cmd，你可以自己补上~

你好，我给补全了，然后也可以正确解析出来，图1，但是在chatGPT对话中cmd还是原来的那些，图2
![image](https://user-images.githubusercontent.com/42965045/235297490-2c681f60-d250-4b8d-9c02-d91dd0e47544.png)
![image](https://user-images.githubusercontent.com/42965045/235297532-3462e195-719e-4c2d-b84c-1164b636b33a.png)

**Comment by RushQ** [comment]
> > @hsw15192617273 这是本身中文prompts那个文件没写cmd，你可以自己补上~
> 
> 你好，我给补全了，然后也可以正确解析出来，图1，但是在chatGPT对话中cmd还是原来的那些，图2 ![image](https://user-images.githubusercontent.com/42965045/235297490-2c681f60-d250-4b8d-9c02-d91dd0e47544.png) ![image](https://user-images.githubusercontent.com/42965045/235297532-3462e195-719e-4c2d-b84c-1164b636b33a.png)

你搞定了么
