### ISSUE TITLE
[Feature]能不能加个自动刷新功能，让它过几分钟自动刷新，让它随时可用

### ISSUE THREAD

**Issue by zhouxinxin19920802** [lencx/ChatGPT#712]
### Feature description

加一个功能，是否自动刷新，开启的话，过几分钟窗口会自动刷新。

### Motivation

chatgpt的窗口几分钟不用的话，再提问的话，就会报something wrong，不能像new bing一直可用，总是得refresh一下，比较烦人。

**Comment by LinearFalcon** [comment]
👍

**Comment by fbmusou** [comment]
最近频繁something wrong，有点难受啊

**Comment by GeassAng** [comment]
https://poe.com/chatgpt，可以试试这个，每天还能一次GPT4问答，没有烦人的刷新。美中不足的就是没有代码排版

**Comment by lencx** [comment]
这是个伪需求，不可能一刀切的，自动刷新会导致正常用户页面频繁更新。之所以出现这种问题是因为网络问题或服务限流。

**Comment by zhouxinxin19920802** [comment]
嗯嗯
