### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by dmfurlan** [lencx/ChatGPT#716]
### Version

ChatGPT_0.12.0_windows_x86_64

### Bug description

I did a clean install, never having used it and it simply won't open after installing it.
I click on the icon created on the desktop, but nothing happens.

### OS

Windows 10

**Comment by BENZEMA216** [comment]
+1

**Comment by Yurun-LI** [comment]
+1 for MacOSX

**Comment by SalsaDura** [comment]
I have the same problem. It doesn't open anymore. I have to use web browser version  instead.

**Comment by lduperval** [comment]
> I removed the folder 'C:\Users\xxx.chatgpt' fixed the issue.

Excellent, thanks! It fixed it for me also

**Comment by dmfurlan** [comment]
This folder do not exists in my windows :(

**Comment by lduperval** [comment]
If you use your current usernam, it would be: C:\Users\dmfurlan\.chatgpt

Rename it if you saved notes in there, and you should be OK.

**Comment by dmfurlan** [comment]
![Untitled](https://user-images.githubusercontent.com/128944993/228983985-74781a44-937d-4832-a02c-a0aa44f34439.png)

**Comment by lduperval** [comment]
go into furlan

**Comment by lduperval** [comment]
Sorry, I made a typo:

C:\Users\dmfurlan\.chatgpt

**Comment by procobain** [comment]
I deleted the folder 'C:\Users\ {your user name} \xxx.chatgpt' and it still isn't opening

Any other solution?

**Comment by lduperval** [comment]
Did you literally include the "xxx"? If so, remove it. The folder is called ".chatgpt"

**Comment by dmfurlan** [comment]
I really don't found this folder in my laptop pc.
is there any log I can collect to know what the problem is?

**Comment by lduperval** [comment]
Yes, there is a ChatGPT Log in the Help menu. Maybe see there?

L

**Comment by lduperval** [comment]
But of course, you need to be able to start the app to see it... the file name is ChatGPT.log. Maybe if you search for it you will find the correct folder.

L

**Comment by procobain** [comment]
I found a palliative solution.

1 - Delete the C:\Users\YOUR_USER\.chatgpt folder
2 - Open powershell as administrator
3 - Open the Chatgpt folder using the command cd 'C:\Program Files\ChatGPT\'
4 - Run the command repeatedly until it opens .\ChatGPT.exe (to run it multiple times, just press the "up arrow and enter"

![powershell_CObvWpZVRU](https://user-images.githubusercontent.com/31631530/230740536-7c5936bc-df8f-4d65-ade1-a40eacde3ed0.png)

**Comment by dmfurlan** [comment]
Running the CMD and going to the ChatGPT folder in C:\Program Files\ChatGPT and running chatgpt.exe from here, it ran normally.
If I click through explorer on the executable, nothing happens.
To solve my problem, I created a .bat file with the commands:
cd C:\Program Files\ChatGPT
ChatGPT.exe

Now I can use it normally!

**Comment by procobain** [comment]
No, you will have problems again.

Opening chatgpt by shortcut, using the mouse, or clicking directly on the .exe is exactly the same thing as opening it through Powershell. The difference is that in powershell you can machine-gun the keyboard by pressing the up arrow and enter, until the program opens. Sometimes I open it with 10 attempts, sometimes with 40 attempts, so the powershell only serves to facilitate the clicks.

**Comment by dmfurlan** [comment]
Well, in my case we clearly see that it's not the same thing, because in one place it works and in the other it doesn't.
And I didn't need to fire it several times, just once was enough for it to work.

**Comment by user4298539** [comment]
After a few months of working properly ChatGPT on windows 10 also after updating to 22H2..
I have the same problem with ChatGPT to the desktop, despite the update to version 1.0. gives,
deleting files from User .chatcgpt also. 

The same here as well [ https://github.com/lencx/ChatGPT/issues/17 ]

I`am checking without which probrams the application does not work and automatically shuts down after startup,
also. because the day before yesterday I removed, for example, microsoft edge, and some other unnecessary programs.... I can only see that in this I might have been at fault.... but I shouldn't be....

i am working on it for the second day and it irritates my autism terribly. if i do not find a way i will be further irritated :) give your support autistic activists :P

I will add that the icon appears when you click on the .exe, unfortunately when you click on the start bar (by the clock) on the icon makes it disappear.... and so for the 2nd day now.... there are few such problems and their solutions equal zero....

**Comment by user4298539** [comment]
[Installation_Log.txt](https://github.com/lencx/ChatGPT/files/11642410/Installation_Log.txt)

**Comment by user4298539** [comment]
@lencx commented You can re-download and install WebView2 here (https://developer.microsoft.com/en-us/microsoft-edge/webview2), then restart the application.

@lencx SOLVED! Yes, I had webview from Adobe, but you're right that I also removed it with the removal of microsoft edge. You are my mentor! Thank you,

**Comment by diegozl** [comment]
I figured it runs through cmd as suggested by dmfurlan, so I opened a text file and typed:

```
cd "C:\Program Files\ChatGPT"
start ChatGPT.exe
```

Then, I saved it as bat, went to the shortcut located at _C:\ProgramData\Microsoft\Windows\Start Menu\Programs\ChatGPT_ and redirected the path to bat.

Now, just double click at the shortcut :)

**Comment by asheroto** [comment]
Same issue after using latest WebView2. Worked before that.

**Comment by asheroto** [comment]
Similar to #1130, #271, #528, #173
