### ISSUE TITLE
“ChatGPT”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by luoky69** [lencx/ChatGPT#738]
### Error message

“ChatGPT”已损坏，无法打开。 你应该将它移到废纸篓。

### OS

mac

**Comment by JadeCong** [comment]
For my MacBook pro m2 pro, I got the same problem, so could someone give us some advices to figure it out?

**Comment by zhanghaha416** [comment]
终端命令行授权就行了
