### ISSUE TITLE
Can't add new prompts

### ISSUE THREAD

**Issue by NosferatuZoddd** [lencx/ChatGPT#74]
I add prompts, go to the chat and nothing works, I return to the page for adding prompts and everything disappears there

**Comment by NosferatuZoddd** [comment]
P.S. version 0.6.8

**Comment by lencx** [comment]
Currently consulting with officials because of path permission issues. Waiting for their reply.

**Comment by ylber-gashi** [comment]
same for me too

**Comment by lencx** [comment]
Please try v0.6.9 version

**Comment by NosferatuZoddd** [comment]
> Please try v0.6.9 version

nah, it didn't change anything

**Comment by ylber-gashi** [comment]
> Please try v0.6.9 version

Same. `Uncaught (in promise) path not allowed on the configured scope: \C:\Users\xxxxx\.chatgpt\cache_model\user_custom.json`

**Comment by lencx** [comment]
It doesn't seem to work on Windows, I'll check the code again.

**Comment by lencx** [comment]
@NosferatuZoddd @ylber-gashi Please try v0.6.10 version.

**Comment by ylber-gashi** [comment]
Now it is working. Well done! Thank you!
