### ISSUE TITLE
[Build Error]mac电脑，下载图片/PDF后提示在

### ISSUE THREAD

**Issue by pangkaifeng-create** [lencx/ChatGPT#750]
### Error message

显示在第一张图片路径，但是进去后没有找到.Chatgpt文件
![image](https://user-images.githubusercontent.com/129295709/229055261-05236c58-2d55-4fb0-93b6-1a508b3d0f99.png)
<img width="653" alt="image" src="https://user-images.githubusercontent.com/129295709/229055379-ca4c3199-12d0-4a7b-a17b-ec860eded488.png">

### OS

MAC M1 11.6版本

**Comment by lencx** [comment]
这是一个隐藏目录，麻烦你自行搜索一下，如何查看隐藏文件夹。
