### ISSUE TITLE
“ChatGPT.app”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by zk-webdev** [lencx/ChatGPT#751]
### Version

ChatGPT_0.12.0_macos_aarch64.dmg

### Bug description

macos 13.1
<img width="260" alt="image" src="https://user-images.githubusercontent.com/128571235/229268324-34f31750-b513-4eb7-8dc2-cc742ba2c90b.png">

### OS

macos 13.1

**Comment by simontv1998** [comment]
Same here

**Comment by chajiuqqq** [comment]
same to me. 

macos 12.5

Air M1

**Comment by BinZhiZhu** [comment]
+1

**Comment by BinZhiZhu** [comment]
> ### Version
> ChatGPT_0.12.0_macos_aarch64.dmg
> 
> ### Bug description
> macos 13.1 <img alt="image" width="260" src="https://user-images.githubusercontent.com/128571235/229268324-34f31750-b513-4eb7-8dc2-cc742ba2c90b.png">
> 
> ### OS
> macos 13.1
> 
> ### Environment
> _No response_

看我楼下回复

**Comment by lencx** [comment]
打开终端执行以下命令：

```bash
xattr -cr /YOUR_PATH/NoFWL.app
```

同样的问题不要一直问，这个在 README.md 里已经写过了。请阅读一下好吗？
