### ISSUE TITLE
Hmmm… can't reach this page

### ISSUE THREAD

**Issue by easyspace** [lencx/ChatGPT#76]
The previous version was working just fine. Don't know what happened with this one. 
Could someone direct me to the older version please?

![Screenshot 2022-12-24 213347](https://user-images.githubusercontent.com/49119116/209443466-8be84fe0-7d7e-4030-b12b-cc3ef10923b4.png)

**Comment by lencx** [comment]
Please use this version, the recent update has encountered some problems, I am working on it. https://github.com/lencx/ChatGPT/releases/tag/v0.5.1

**Comment by easyspace** [comment]
Sure, sure. Thank you. 0.5.1 is working perfectly. 

Really good work by you!

**Comment by lencx** [comment]
Please try v0.6.9, the problem should be fixed.

**Comment by easyspace** [comment]
Ok, I installed it. The same error is still present.

**Comment by easyspace** [comment]
Ok, I installed it. The same error is still present.

**Comment by lencx** [comment]
This problem looks like a network reason, are you sure v0.5.1 is working? Because they are the same way of working.

**Comment by easyspace** [comment]
You are right. I am using Kaspersky and it is notorious for causing these
Firewall blockade issues.
Though 0.5.1 was not blocked at all, 0.6.9 was blocked. I've unblocked it
however.

Thanks for your insight.

**Comment by lencx** [comment]
So currently 0.6.9 is working? Then you can use the sync feature too, it should work now.

**Comment by easyspace** [comment]
Yes, it is working. Thanks again!
