### ISSUE TITLE
[Suggest] 没有OPENAI_API_KEY或无法直连的同学可以看看这里

### ISSUE THREAD

**Issue by saimirgx** [lencx/ChatGPT#785]
### Feature description

http://chat-gpt-api.cn 这个网站提供了一个 OpenAI 的镜像 `Endpoint` 和 `API Key`，只要设置好相关环境变量，即可稳定使用。

亲测好用，推荐一下

**Comment by ttimasdf** [comment]
商业模式看起来就是白嫖别人的 API key。
