### ISSUE TITLE
[Bug] 程序无法启动（win64）

### ISSUE THREAD

**Issue by emako** [lencx/ChatGPT#796]
### Version

v0.12.0

### Bug description

![image](https://user-images.githubusercontent.com/24737061/230875892-c023b28d-f399-4607-8aa4-0c4367f71368.png)

一直显示的是这个奇怪的窗口，没有任何动静，任务栏或者托盘图标右键都关不掉，只能任务管理器杀掉。

![image](https://user-images.githubusercontent.com/24737061/230876788-e5baac4b-a040-4563-9343-10f0ffac5d90.png)

### OS

Windows 11 专业版 21H2 22000.613

**Comment by billowssun** [comment]
我也是一样的问题，win10系统。

**Comment by li1243893836** [comment]
我的也一样，macOS

**Comment by Yu-Hang-Z** [comment]
我也一样，macOS：修改一个配置之后重启就无法打开软件了，brew卸载重装也无法解决。

**Comment by XnCluster** [comment]
macos arm M1, 文件损坏无法打开

**Comment by doubleLLL3** [comment]
配置文件的问题，路径是`~/.chatgpt/chat.conf.json`。

观察之前配置和默认配置的区别如下图，发现罪魁祸首是`"hide_dock_icon": true`，所以：
1. 配置改为`"hide_dock_icon": false`，
2. 重新启动，注意要先去任务管理器里把ChatGPT退出。
<img width="2526" alt="image" src="https://user-images.githubusercontent.com/44157339/231908946-2b5e4948-5977-4c4b-ad8c-c7997373417b.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/44157339/231908505-ac2a4243-a19b-48a2-aca6-e7be60ef5f53.png">

---
如果还是不行，可以将`~/.chatgpt`这个文件夹「改名作为备份或者删掉」。

**Comment by doubleLLL3** [comment]
> macos arm M1, 文件损坏无法打开

这是另外一个问题，README里写了，命令行运行即可：
`sudo xattr -r -d com.apple.quarantine /YOUR_PATH/ChatGPT.app`

参考https://github.com/lencx/ChatGPT#mac

**Comment by Yu-Hang-Z** [comment]
可以，完美解决

**Comment by XnCluster** [comment]
> macos arm M1, 文件损坏无法打开

已在主页找到解决方案，无需回答

**Comment by emako** [comment]
问题是买回来的新机安装软件就出这个问题。

**Comment by KamToHung** [comment]
> 配置文件的问题，路径是`~/.chatgpt/chat.conf.json`。（Note：**.chatgpt文件夹默认是隐藏的**）
> 
> 观察自己改和默认的配置文件的区别如下图，发现罪魁祸首是`"hide_dock_icon": true`，所以：
> 
> 1. 配置改为`"hide_dock_icon": false`，
> 2. 重新启动，注意要先去任务管理器里把ChatGPT退出。
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/44157339/231908946-2b5e4948-5977-4c4b-ad8c-c7997373417b.png">
> 
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/44157339/231908505-ac2a4243-a19b-48a2-aca6-e7be60ef5f53.png">
> 
> 如果还是不行，可以将`~/.chatgpt`这个文件夹「改名作为备份或者删掉」。

谢谢了···不小心设置了下就失败了，这个hide dock对于mac有什么用的

**Comment by doubleLLL3** [comment]
@KamToHung 字面意思，就是ChatGPT图标不会显示在Mac的拓展坞dock里
