### ISSUE TITLE
mac m1

### ISSUE THREAD

**Issue by lanson07** [lencx/ChatGPT#80]
.dmg seems not to satisify m1/m2 chip for mac? how to fix it? 
thanks a lot.

**Comment by lencx** [comment]
I am now the Mac M1 and it is working

**Comment by BrutalCoding** [comment]
I can confirm it works on M1, can you explain exactly what issue you are facing? Include screenshots if that helps to clarify the problem.

**Comment by lanson07** [comment]
thanks. I have fix this prob through homebrew script in mac(air m2). But .dmg is still not work.

**Comment by ylluminate** [comment]
This should actually follow the Electron Mail pattern for release so that there is a true Apple Silicon release:
* https://github.com/vladimiry/ElectronMail/releases
* https://github.com/vladimiry/ElectronMail/issues/357#issuecomment-1185389181

**Comment by yixinBC** [comment]
> This should actually follow the Electron Mail pattern for release so that there is a true Apple Silicon release:
> 
>     * https://github.com/vladimiry/ElectronMail/releases
> 
>     * [Apple Silicon/M1 Support vladimiry/ElectronMail#357 (comment)](https://github.com/vladimiry/ElectronMail/issues/357#issuecomment-1185389181)

So how can we migrate that **[electron](https://github.com/electron/electron)** solution to this **[tauri](https://github.com/tauri-apps/tauri)** app?
