### ISSUE TITLE
[Feature] How to set proxy in mac ? Docs ?

### ISSUE THREAD

**Issue by lyy289065406** [lencx/ChatGPT#823]
### Feature description

How to set proxy in mac ? Docs ?

**Comment by Mikemansour** [comment]
us Clash for macos

**Comment by zhheo** [comment]
我也想问一下

**Comment by Mikemansour** [comment]
> 我也想问一下

What kind of proxy are you using ? And are you using it in China ?

**Comment by lyy289065406** [comment]
> useClash for macos
ClashX works, thx
