### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by staycanuca** [lencx/ChatGPT#85]
Latest version 0.7.0  x64 can't be run run on windows 10 x64.
What I try:
- simple upgrade
- uninstall and the reinstall
- delete config file and then reinstall

Version 0.6.10 is working ok.

**Comment by lencx** [comment]
Run a direct exit?

**Comment by staycanuca** [comment]
> Run a direct exit?

no. I will try

**Comment by lencx** [comment]
I checked the code and did not change anything related to the configuration, is the application not clickable at all?

**Comment by staycanuca** [comment]
the application is not clickable at all

**Comment by mtw20** [comment]
After starting the binary, tray icon appear, but the app is immediately closed.
Here you can see process exit details.
![logs](https://user-images.githubusercontent.com/114318928/209702773-f90fa165-841a-4867-9a57-dc064e037fc7.png)

**Comment by lencx** [comment]
Please try v0.7.1

**Comment by mtw20** [comment]
v0.7.1 is crashing too, the log file is not filled.

**Comment by lencx** [comment]
I don't have a windows computer for debugging, so if you can, I'd like you to clone the project and I can assist you with the build. https://github.com/lencx/ChatGPT#how-do-i-build-it

**Comment by mtw20** [comment]
@lencx I left you a private message on Twitter.

**Comment by fstanley** [comment]
Just chiming in, same problem for me on Windows 11. I am a new user, never installed. 0.7.0 and 0.7.1 fail to start. I uninstalled and installed 0.6.10 and it works fine.

**Comment by lencx** [comment]
Please try v0.7.2 version.

**Comment by mtw20** [comment]
It works! Thank you for fixing it.
