### ISSUE TITLE
Custom functionality?

### ISSUE THREAD

**Issue by Shikamaru5** [lencx/ChatGPT#867]
### Feature description

So it has a chatgpt users guide and dalle2 but when you click on them they flash a window for a millisecond and then vanish, if you click on them enough the app closes. I'm just trying to figure out the different things that you can do with it, like it says in preferences inject_script and it gives you a main.js script wherever you want it like sublime or VSC. However, I can't seem to get the new function test to do anything in the program. So I'm wondering maybe main.js isn't where I should be putting it, like there is a user_custom.json in the language model part of the control center, and in the chatgpt folders. Maybe that's where I'm supposed to put the new test script? The current test is pretty simple all it does is adds in a custom prompt and when the prompt is said the model is supposed to output the expected response.
### Additional context
This is the script that I'm trying to inject:

    (function() {
      console.log('🤩 Hello ChatGPT!!!');
    
      class ChatGPT_new {
        constructor() {
          this.short_term_memory = {};
          this.long_term_memory = {};
        }

    remember(input_text, output_text) {
      this.short_term_memory[input_text] = output_text;

      // Store the short-term memory in the long-term memory
      for (let [key, value] of Object.entries(this.short_term_memory)) {
        this.long_term_memory[key] = value;
      }

      // Add custom response for "duck"
      if (input_text === 'duck') {
        this.long_term_memory[input_text] = 'where?';
      }
    }

    recall(input_text) {
      // Try to recall from short-term memory
      if (input_text in this.short_term_memory) {
        return this.short_term_memory[input_text];
      }

      // Try to recall from long-term memory
      else if (input_text in this.long_term_memory) {
        return this.long_term_memory[input_text];
      }

      // If no memory exists, return null
      else {
        return null;
      }
     }
    }

      new ChatGPT_new();
    })();
    _No response_

**Comment by Shikamaru5** [comment]
It's ok nevermind, I got it working, and was able to successfully get it to check the current time.

**Comment by Shikamaru5** [comment]
@Droyk Oh I'm sorry I scrapped that project for the use of the chatgpt api in console, since the downloadable chatgpt that you can run locally also uses the api if you're making calls like this. So it was more versatile, and I even made an ok virtual assistant that could write basic scripts on my computer locally it's just that it got confused for larger scale projects.

**Comment by Droyk** [comment]
@Shikamaru5 No problem, and please don't apologize again for something that wasn't your fault. Just let me know if you remember how you managed to inject the script into the program.
