### ISSUE TITLE
[Bug] Application can be configured such that it's invisible.

### ISSUE THREAD

**Issue by pedramamini** [lencx/ChatGPT#868]
### Version

0.12.0

### Bug description

Somehow I've managed to get the settings on the app such that on launch, while it's in the process table, it does not appear in the Dock nor menu.  Deleting the following directory of plist files being removed:

`/Library/Saved Application State/com.lencx.chatgpt.savedState`

### OS

OSX Ventura

**Comment by anegoda1995** [comment]
I fixed it in next steps:
1. Stop process in Activity Monitor;
2. Download previous version;
3. On start allow to download latest version (0.12 for now)
4. Profit!

**Comment by bqiu86** [comment]
You can also edit the "chat.conf.json"  in "/Users/{username}/.chatgpt/" to fix the issue.

**Comment by pedramamini** [comment]
@bqiu86 has the right path. That's the fix!
