### ISSUE TITLE
Tray icon in dark mode is almost not visible

### ISSUE THREAD

**Issue by mtw20** [lencx/ChatGPT#87]
![chatgpt_icon](https://user-images.githubusercontent.com/114318928/209684048-6e823faa-2048-412c-95af-6f64c2e9fc86.png)

**Comment by lencx** [comment]
Please try v0.7.1

**Comment by mtw20** [comment]
Icon changed, but the quality compared to any other app is heavily degradated.
![icq](https://user-images.githubusercontent.com/114318928/209703590-7e46e9e2-e2fd-4218-8b8b-807207977bd0.png)

**Comment by lencx** [comment]
Next version can reduce the size of icons. What do you mean by quality? Is it too fuzzy, or is it the size?

**Comment by mtw20** [comment]
The edges of the icon are very jagged / not a circle.
The size is ok, but maybe the base icon size is too large and causing it?

**Comment by lencx** [comment]
Maybe the shadows on the edges are causing rendering problems, I shouldn't add shadows.
