### ISSUE TITLE
[Bug]MAC OS下桌面版打开以后没反应，显示Free Research Preview. ChatGPT may produce inaccurate information about people, places, or facts. ChatGPT May 3 Version

### ISSUE THREAD

**Issue by renshengzi** [lencx/ChatGPT#887]
### Version

v 0.12.0

### Bug description

MAC OS下桌面版打开以后没反应，显示Free Research Preview. ChatGPT may produce inaccurate information about people, places, or facts. ChatGPT May 3 Version。网页打开chatgpt是正常的，所以机场没问题。此外尝试重新卸载（直接卸载和app cleaner卸载）之后安装依然是同样的问题。

### OS

mac os

**Comment by renshengzi** [comment]
如图所示：
<img width="794" alt="截屏2023-05-10 16 31 30" src="https://github.com/lencx/ChatGPT/assets/127164745/f6a89169-5a24-4970-8498-37a3eac874e7">

**Comment by jessicalailai** [comment]
请问最后是怎么解决的？

**Comment by keidododo** [comment]
解决了吗？

**Comment by jessicalailai** [comment]
okay 啦，已經解決了，謝謝～～～




Jessica&nbsp;Lai
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "lencx/ChatGPT"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Oct 26, 2023 07:37 PM
***@***.***&gt;;
Cc:&nbsp;"Jessica ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [lencx/ChatGPT] [Bug]MAC OS下桌面版打开以后没反应，显示Free Research Preview. ChatGPT may produce inaccurate information about people, places, or facts. ChatGPT May 3 Version (Issue #887)





 
解决了吗？
