### ISSUE TITLE
Add support for debian stable

### ISSUE THREAD

**Issue by HumanG33k** [lencx/ChatGPT#89]
There is an issue with libssl at start on debian stable.

**Comment by lencx** [comment]
I've updated the github action for building the app and changed some of the dependencies, you can try it by installing `v0.7.1`.

**Comment by Lenglemetz** [comment]
The problem is also present in the latest version of Ubuntu.

**Comment by lencx** [comment]
Please try to install v0.7.4 and check if `~/.chatgpt/chatgpt.log` exists.
