### ISSUE TITLE
[Bug]windows can't export

### ISSUE THREAD

**Issue by UserJTZhang** [lencx/ChatGPT#902]
### Version

v0.12.0

### Bug description

Window 11, all export buttons are useless

1. Markdown is exported as blank, with a file size of 0kb
![image](https://github.com/lencx/ChatGPT/assets/45026028/59dbc898-b715-46a6-b47a-0d2fa9cd7925)

2. When exporting PDF and images, the page becomes longer after clicking the finish button, and there are input box in the middle, but no files have been saved, and the file path has not been saved like a markup

![image](https://github.com/lencx/ChatGPT/assets/45026028/5ead263b-373a-4e42-8db1-fb89182fe7cf)

### OS

windows 11

**Comment by UserJTZhang** [comment]
I tried different versions for Windows includ v0.12.0 v0.11.1 v0.11.0 v0.10.3, they also have this bug.
 v0.10.3 can export markdown, but pdf and png are not work

**Comment by Minghua5** [comment]
I have also encountered this problem, the saved markdown file is blank

**Comment by JiangLongLiu** [comment]
me too

**Comment by JiangLongLiu** [comment]
> I have also encountered this problem, the saved markdown file is blank

me too

**Comment by li010116** [comment]
同样遇到问题导出显示0kb
