### ISSUE TITLE
[Feature] Option to turn off (the buggy) export keys

### ISSUE THREAD

**Issue by realliyifei** [lencx/ChatGPT#911]
### Feature description

How to turn off these export keys? 

(1) They are buggy now, as indicated by other issues here 
(2) I don’t use them frequently

So it is better to provide an option of turn off them (we can export via the menu bar instead)

<img width="72" alt="image" src="https://github.com/lencx/ChatGPT/assets/32441766/c59c4dd0-f2ba-4404-9fb9-355af0bf5707">

**Comment by lencx** [comment]
download v1.0.0
