### ISSUE TITLE
[Bug] “ChatGPT” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by azataiot** [lencx/ChatGPT#924]
### Version

v1.0

### Bug description

“ChatGPT” is damaged and can’t be opened. You should move it to the Trash.

![2023-05-27-at-07 15 58](https://github.com/lencx/ChatGPT/assets/8280770/4252676c-7ba9-4bf4-9170-85cba1c2729b)

It was running when i updated with homebrew yesterday, after I restart the machine today, it shows an error like this. 

昨天用brew 更新前一切正常，今天就打不开了，我也尝试着用brew 重装了一遍，没啥卵用。

### OS

macOS 13.3.1 (a)

**Comment by lencx** [comment]
麻烦读一读 readme 好吗，这个问题在 readme 里一直有写
