### ISSUE TITLE
[Bug]应用已损坏，无法使用

### ISSUE THREAD

**Issue by mayaa6** [lencx/ChatGPT#928]
### Version

v 1.0.0

### Bug description

<img width="259" alt="image" src="https://github.com/lencx/ChatGPT/assets/3221154/815ebba3-a5ea-4e31-b873-3c73a0902b6a">

是用github上官方地址下载的，macos-arch64版本的dmg，重复试了四次，都是一样的结果。下载windows版本一切正常。

### OS

macOS 13.3.1 (a)

**Comment by lencx** [comment]
麻烦看一下 readme，早已写过解决办法。
