### ISSUE TITLE
[Improvement] Hide to tray upon closing

### ISSUE THREAD

**Issue by mtw20** [lencx/ChatGPT#93]
ChatGPT isn't used constantly, but mostly when required, so having it in tray instead of taskbar would be the more comfortable option.

Could you add an option which makes hiding in tray when clicking close button, as an option?
There's a option now to hide, but it's in menu, means more user actions is needed.

**Comment by lencx** [comment]
There is currently no API for hiding taskbar icons on platforms other than mac.

**Comment by mtw20** [comment]
The app is moved to tray with hide option, and disappear from taskbar, so the API is available.
Just the behavior of using a close button could be different from now, so the user would make fewer clicks to achieve it.

**Comment by lencx** [comment]
The hidden window is the main process of the chatgpt app, and if it exits, the app will exit.

**Comment by mtw20** [comment]
It doesn't need to exit, it's a common standard for many Windows apps to stay only in tray (ex. Telegram, Caprine, Discord, Skype, Slack). They are handling the close button behavior differently than default app exit action.

**Comment by lencx** [comment]
But none of them are based on tauri implementation. I am not currently able to solve the problem you describe, you can tell me by checking the tauri documentation, I would be happy to implement this feature.

**Comment by mtw20** [comment]
This may be helpful. It appears that you can attach hiding main window + tray on exit.
https://github.com/tauri-apps/tauri/discussions/2684

**Comment by lencx** [comment]
That's how it's handled now, and it's not the problem you want to solve. https://github.com/lencx/ChatGPT/blob/main/src-tauri/src/main.rs#L77-L91

**Comment by mtw20** [comment]
Also https://tauri.app/v1/guides/features/system-tray/

We have both:
1. Closing with [x] - it hides main window, but keep on taskbar
2. ChatpGPT -> Hide (ctrl+H) - it hides main window, and remove from taskbar

What was requested is handling [x] like in 2.

**Comment by lencx** [comment]
You can hide the window in 2, but you cannot remove it from the taskbar.

**Comment by mtw20** [comment]
The (2) option is removing from taskbar.

**Comment by lencx** [comment]
Removing it from the taskbar will kill the program.

**Comment by mtw20** [comment]
No, the program is still running, and can be opened from tray.

**Comment by lencx** [comment]
I see what you're saying, it's hidden on windows, but it won't work on mac.

**Comment by bokkoman** [comment]
Can't the Hide (ctrl+h) not be the X for closing? Cause this is quite annoying as it is now.
The shortcut doesn't work for me, no idea why. But when I hide it, and then click the tray icon, it opens the window again together with the smaller tray window.

**Comment by lencx** [comment]
> Can't the Hide (ctrl+h) not be the X for closing? Cause this is quite annoying as it is now. The shortcut doesn't work for me, no idea why. But when I hide it, and then click the tray icon, it opens the window again together with the smaller tray window.

You can now tap [x] to exit the application (`Control Center -> Settings -> Main Window -> Close Exit`).

**Comment by bokkoman** [comment]
> 

This doesn't work. Well it does, but it closes the whole process, so even the tray icon is closed.

**Comment by SnowPowerCore** [comment]
+1, close button only hides the main window, but on Windows most of the times expected behavior is to close GUI window, but keep the tray process. Would be really amazing to have a behavior like that.
