### ISSUE TITLE
连接外接屏时，窗口出现位置错误

### ISSUE THREAD

**Issue by Jinl-k** [lencx/ChatGPT#94]
![图像](https://user-images.githubusercontent.com/39037760/209753145-e3bd7d46-177e-43a6-b849-3a6028fa498e.jpeg)

当我点击菜单栏上的chatgpt时，窗口出现在上方。

**Comment by lencx** [comment]
连接外屏后重新打开试试，这个是在打开时计算位置的

**Comment by Jinl-k** [comment]
还是不行> 连接外屏后重新打开试试，这个是在打开时计算位置的

**Comment by lencx** [comment]
你是设置的上下屏，还是左右屏？

**Comment by Jinl-k** [comment]
> 你是设置的上下屏，还是左右屏？

上下屏

**Comment by lencx** [comment]
如果是上下屏我理解这个计算是没问题的（这些计算来源于一个插件，不是我实现的，我猜测这个位置计算是把它们作为一个整体了），你可以尝试左右屏，看还有没有类似问题。这个问题暂时可能无解，自己计算位置会很复杂。

**Comment by Jinl-k** [comment]
> 如果是上下屏我理解这个计算是没问题的（这些计算来源于一个插件，不是我实现的，我猜测这个位置计算是把它们作为一个整体了），你可以尝试左右屏，看还有没有类似问题。这个问题暂时可能无解，自己计算位置会很复杂。

好吧，看来只能这样了
