### ISSUE TITLE
win10启动报错

### ISSUE THREAD

**Issue by edisonyan** [lencx/ChatGPT#95]
version  0.6.10 - 0.7.2

![image](https://user-images.githubusercontent.com/3954670/209788695-283926df-f2b8-4e7e-b07d-259d4cb4a57b.png)
![image](https://user-images.githubusercontent.com/3954670/209788788-f8060234-5cbc-46dc-8b34-60b5d3dbf945.png)

**Comment by lencx** [comment]
麻烦问一下 0.6.10 之前的版本呢？都出现不兼容吗？

**Comment by yixinBC** [comment]
@zs1621 see:https://github.com/tauri-apps/tauri/issues/4659

**Comment by lencx** [comment]
Compatibility mode can work normally. https://github.com/tauri-apps/tauri/issues/5833#issuecomment-1352700584

**Comment by qingmeipve** [comment]
> > Compatibility mode can work normally. [tauri-apps/tauri#5833 (comment)](https://github.com/tauri-apps/tauri/issues/5833#issuecomment-1352700584)
> 
> ![image](https://user-images.githubusercontent.com/1854527/221785567-3f780bbb-9084-4c0e-98ef-e8b9e63431b4.png)
> 
> it works ~~ thanks @lencx @yixinBC

我通过这个方法解决了这个问题，但是不知道会有什么后果
