### ISSUE TITLE
[Doc] 请问如何回车发送消息呢？

### ISSUE THREAD

**Issue by Tcyily** [lencx/ChatGPT#950]
### Provide a description of requested docs changes

现在回车的逻辑只有换行，和网页端并不一致。使用起来还是有一些不方便

**Comment by oneHTZ** [comment]
尝试 Shift+Enter

**Comment by Tcyily** [comment]
> 尝试 Shift+Enter
不行。纯enter、shift+enter、ctrl+enter都是换行
