### ISSUE TITLE
[Bug] SMS code not received by ChatGPT to activate my account 

### ISSUE THREAD

**Issue by Antoinemr77** [lencx/ChatGPT#966]
### Version

v 1.0.0

### Bug description

Here's what it displays:

We've detected suspicious behavior from phone numbers similar to yours. Please try again later or contact us through our help center at help.openai.com.

Thanks in advance for the help

### OS

Windows 11

**Comment by asheroto** [comment]
That's not an issue with the package, it's an issue with ChatGPT. You should be able to close this issue.

This package is basically a web browser that points to ChatGPT, so it can't correct any issues that ChatGPT has.

**Comment by asheroto** [comment]
Hello, can you please close this Issue?

**Comment by Antoinemr77** [comment]
All worked now.
