### ISSUE TITLE
[BUG] Can't seem to use custom path

### ISSUE THREAD

**Issue by vlad-terin** [lencx/ChatGPT#98]
https://github.com/vlad-terin/awesome-chatgpt-prompts/blob/main/prompts.csv

Forked the main chatgpt prompts repo, trying to sync
![image](https://user-images.githubusercontent.com/5722749/209833798-ed8a29bc-fce2-4717-94dd-384f9e3d068c.png)

The tool closes upon hitting sync without saving the progress. 

Maybe i'm doing something wrong?

**Comment by vlad-terin** [comment]
![image](https://user-images.githubusercontent.com/5722749/209834042-823ba20a-9d63-46f9-9c25-76f96a8be8e2.png)

Tried with a different path - still an error.

**Comment by lencx** [comment]
Your configuration is wrong, it needs the static file path. `https://raw.githubusercontent.com/vlad-terin/awesome-chatgpt-prompts/main/prompts.csv`

**Comment by vlad-terin** [comment]
Thanks for adding this feature.

I have a small issue: When using "space" to input a sentence for a query, it expands the query without changing the contents of a query. (second example used "space" to input a sentence into curly brackets, didn't work

![image](https://user-images.githubusercontent.com/5722749/210386464-54dae5a3-e9df-400c-a4ad-331c06a2f443.png)
![image](https://user-images.githubusercontent.com/5722749/210386519-3a5d6ff4-1e10-4c1f-817a-6343d6bc8547.png)

**Comment by lencx** [comment]
What does the content of the curly brackets mean? Do you need to replace the variables, or what?

**Comment by vlad-terin** [comment]
Example query: 

Write a novel with a title being in curly brackets: {title goes here}

As I hit TAB, I can enter 1 word for a title. the moment i hit "Space" - the query expands with original value {title goes here}
