### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by atoll27** [lencx/ChatGPT#980]
### Version

Chat gpt may 24 version Version 1.0.0

### Bug description

I asked for a simple mathematical problem (using french language) to Chatgpt 4 with plugins aigpt, copilot and wolfram
Here is the problem: Jérôme said to his father:"the digits of my age is the same that your age."
His father answers: "last year, my age was the double of yours". How old is the father?
Chatgpt try to resolve this problem with the wolfram plugin but it says first that wolfram doesn't work for this plug and it try to solve manually the problem.At first it found 13 and 31.
I answered that 30 isn't the double of 12.
it tried again and it found 12 and 24.
I answered that 23 isn't the double of 11.
it tried again and it is going to repeat always the same sentences without giving any response....Here is it long last response:
Je m'excuse pour l'erreur. Vous avez absolument raison, 23 n'est pas le double de 11. Je suis désolé pour la confusion. 

En fait, si l'âge du père était le double de celui de Jérôme l'année précédente, cela signifie que l'âge du père cette année est le double de l'âge de Jérôme plus 1 (car ils ont tous deux vieilli d'un an). 

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent. 

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2. L'année précédente, l'âge de P était le double de celui de J.

Cela signifie que nous cherchons deux nombres tels que P = 2J + 1 et que les chiffres de P et J sont les mêmes mais dans un ordre différent.

Je vais recalculer cela.

Je m'excuse pour les erreurs précédentes. Vous avez raison, mes calculs étaient incorrects. Laissez-moi corriger cela.

Nous cherchons deux nombres, l'âge de Jérôme (J) et l'âge de son père (P), qui satisfont deux conditions :

1. Les chiffres de J sont les mêmes que ceux de P, mais pas nécessairement dans le même ordre.
2
![ChatGPT_2023_06_28-214529](https://github.com/lencx/ChatGPT/assets/32414908/77b791ee-4a61-4aa4-9bc2-ffbc43447351)

### OS

windows 10

### Environment

I used desktop chatgpt newest version

**Comment by asheroto** [comment]
Hello, this issue appears to be unrelated to the package and is an issue with OpenAI's ChatGPT.

This package is basically a web browser that points to ChatGPT, so it can't correct any issues that ChatGPT has.

**Comment by JoelAzaria** [comment]
@atoll27 This github project is just a wrapper around ChatGPT.   It does not affect answers you get.   I suggest you report that to openai at openai.com.

Please someone close this issue as wontfix.
ty.
