### ISSUE TITLE
Stuck when restart window

### ISSUE THREAD

**Issue by cfbsks** [lencx/ChatGPT#99]
![image](https://user-images.githubusercontent.com/76492899/209854844-84f06df3-450d-447d-a246-a3b232a1de14.png)

**Comment by lencx** [comment]
Quit the app and reopen it, does it always do that?

**Comment by cfbsks** [comment]
No, it will happen when you leave the window for a while.

**Comment by cfbsks** [comment]
![image](https://user-images.githubusercontent.com/76492899/209906702-c0b35b6c-371a-4f89-8248-0bea90d9269e.png)
If the program becomes stuck, you have to use the Task Manager to end the task.

**Comment by cfbsks** [comment]
And I'm using Windows 11 latest.

**Comment by lencx** [comment]
Some platform-related compatibility, I have not found a solution for the time being.
